import type { OutboxEntry, OutboxEntryInput } from '@/shared/electron-api.types';

/* eslint-disable @typescript-eslint/require-await -- no-op async IPC stubs for browser dev */
const noop = (): void => {};
const noopUnsub = (): (() => void) => () => {};
const noopAsync = async (): Promise<void> => {};

function stubOutboxEntry(entry: OutboxEntryInput): OutboxEntry {
  const now = Date.now();
  return {
    id: 0,
    attemptCount: 0,
    createdAt: now,
    updatedAt: now,
    ...entry,
  };
}

/** No-op electronAPI for Vite browser dev when Electron preload is unavailable. */
export function createDevElectronApiStub(): typeof window.electronAPI {
  return {
    db: {
      saveMessage: noopAsync,
      getMessages: async () => [],
      saveNode: noopAsync,
      saveNodePath: noopAsync,
      getNodes: async () => [],
      clearMessages: noopAsync,
      clearNodes: noopAsync,
      deleteNode: noopAsync,
      updateMessageStatus: noopAsync,
      exportDb: async () => null,
      importDb: async () => null,
      deleteNodesByAge: noopAsync,
      deleteNodesNeverHeard: async () => 0,
      pruneNodesByCount: async () => ({ changes: 0 }),
      pruneMessagesByCount: async () => ({ changes: 0 }),
      pruneMeshcoreMessagesByCount: async () => ({ changes: 0 }),
      deleteNodesBatch: async () => 0,
      clearMessagesByChannel: noopAsync,
      getMessageChannels: async () => [],
      setNodeFavorited: noopAsync,
      getNodeNote: async () => null,
      setNodeNote: noopAsync,
      deleteNodesBySource: async () => 0,
      migrateRfStubNodes: async () => 0,
      deleteNodesWithoutLongname: async () => 0,
      prunePositionHistory: async () => 0,
      prunePositionHistoryPerNode: async () => 0,
      clearNodePositions: noopAsync,
      updateMessageReceivedVia: noopAsync,
      updateMessagePacketId: noopAsync,
      getMeshcoreMessages: async () => [],
      getReticulumMessages: async () => [],
      saveReticulumMessage: noopAsync,
      markStaleReticulumOutbound: async () => ({ changes: 0 }),
      vacuumReticulumTables: async () => ({ ok: true }),
      getReticulumDestinations: async () => [],
      upsertReticulumDestination: noopAsync,
      searchMessages: async () => [],
      searchMeshcoreMessages: async () => [],
      getMeshcoreContacts: async () => [],
      saveMeshcoreMessage: noopAsync,
      updateMeshcoreMessageSender: noopAsync,
      saveMeshcoreContact: noopAsync,
      saveMeshcoreContactsBatch: async () => 0,
      updateMeshcoreContactRfTransport: noopAsync,
      updateMeshcoreContactAdvert: noopAsync,
      updateMeshcoreContactType: noopAsync,
      updateMeshcoreContactLastRf: noopAsync,
      updateMeshcoreMessageStatus: noopAsync,
      updateMeshcoreMessageStatusByKey: async () => ({ changes: 1 }),
      deleteMeshcoreContact: noopAsync,
      clearMeshcoreMessages: noopAsync,
      getMeshcoreMessageChannels: async () => [],
      clearMeshcoreMessagesByChannel: noopAsync,
      clearMeshcoreContacts: noopAsync,
      deleteMeshcoreContactsNeverAdvertised: noopAsync,
      deleteMeshcoreContactsByAge: noopAsync,
      pruneMeshcoreContactsByCount: async () => ({ changes: 0 }),
      clearMeshcoreRepeaters: noopAsync,
      markAllMeshcoreContactsOffRadio: noopAsync,
      getMeshcoreContactCount: async () => 0,
      deleteMeshcoreContactsWithoutPubkey: async () => ({ deleted: 0, excludedStubCount: 0 }),
      offloadAllMeshcoreContacts: async () => 0,
      getMeshcoreContactById: async () => undefined,
      updateMeshcoreContactNickname: noopAsync,
      updateMeshcoreContactFavorited: noopAsync,
      savePositionHistory: noopAsync,
      getPositionHistory: async () => [],
      clearPositionHistory: noopAsync,
      saveMeshcoreHopHistory: async () => true,
      getMeshcoreHopHistory: async () => null,
      getAllMeshcoreHopHistory: async () => [],
      saveMeshcoreTraceHistory: async () => true,
      getMeshcoreTraceHistory: async () => [],
      pruneMeshcorePathHistory: async () => true,
      upsertMeshcorePathHistory: async () => true,
      recordMeshcorePathOutcome: async () => true,
      getMeshcorePathHistory: async () => [],
      getAllMeshcorePathHistory: async () => [],
      deleteMeshcorePathHistoryForNode: async () => true,
      deleteAllMeshcorePathHistory: async () => true,
      getContactGroups: async () => [],
      createContactGroup: async () => 1,
      updateContactGroup: noopAsync,
      deleteContactGroup: noopAsync,
      addContactToGroup: noopAsync,
      removeContactFromGroup: noopAsync,
      getContactGroupMembers: async () => [],
    },
    mqtt: {
      connect: noopAsync,
      disconnect: noopAsync,
      powerResume: noopAsync,
      powerSuspend: noopAsync,
      onStatus: noopUnsub,
      onError: noopUnsub,
      onWarning: noopUnsub,
      onNodeUpdate: noopUnsub,
      onMessage: noopUnsub,
      onBrokerRaw: noopUnsub,
      onTraceRouteReply: noopUnsub,
      onClientId: noopUnsub,
      getClientId: async () => '',
      getCachedNodes: async () => [],
      updateChannelKeys: noopAsync,
      publish: async () => 1,
      publishProxy: noopAsync,
      publishNodeInfo: async () => 1,
      publishPosition: async () => 1,
      publishWaypoint: async () => 1,
      publishMeshcore: noopAsync,
      publishMeshcorePacketLog: noopAsync,
      onMeshcoreChat: noopUnsub,
      refreshMeshcoreToken: async () => null,
      updateMeshcoreToken: noopAsync,
      onRequestTokenRefresh: noopUnsub,
    },
    onNobleBleAdapterState: noopUnsub,
    onNobleBleDeviceDiscovered: noopUnsub,
    onNobleBleConnected: noopUnsub,
    onNobleBleDisconnected: noopUnsub,
    onNobleBleConnectAborted: noopUnsub,
    onNobleBleFromRadio: noopUnsub,
    startNobleBleScanning: noopAsync,
    stopNobleBleScanning: noopAsync,
    connectNobleBle: async () => ({ ok: true }),
    disconnectNobleBle: noopAsync,
    isNobleBleConnected: async () => false,
    nobleBleToRadio: noopAsync,
    onSerialPortsDiscovered: noopUnsub,
    selectSerialPort: noop,
    cancelSerialSelection: noop,
    onBluetoothDevicesDiscovered: noopUnsub,
    selectBluetoothDevice: noop,
    cancelBluetoothSelection: noop,
    bluetoothUnpair: noopAsync,
    bluetoothStartScan: noopAsync,
    bluetoothStopScan: noopAsync,
    bluetoothPair: noopAsync,
    bluetoothConnect: noopAsync,
    bluetoothUntrust: noopAsync,
    bluetoothGetInfo: async () => '',
    onBluetoothPinRequired: noopUnsub,
    provideBluetoothPin: noop,
    cancelBluetoothPairing: noop,
    resetBlePairingRetryCount: noop,
    clearSessionData: noopAsync,
    getLinuxBleCapabilityStatus: async () => ({
      platform: 'other' as const,
      hasCapNetRaw: false,
      detail: 'browser dev stub',
    }),
    getGpsFix: async () => ({ lat: 0, lon: 0, source: 'ip' as const }),
    update: {
      check: noopAsync,
      download: noopAsync,
      install: noopAsync,
      openReleases: noopAsync,
      onAvailable: noopUnsub,
      onNotAvailable: noopUnsub,
      onChecking: noopUnsub,
      onProgress: noopUnsub,
      onDownloaded: noopUnsub,
      onError: noopUnsub,
    },
    notifyDeviceConnected: noop,
    notifyDeviceDisconnected: noop,
    setTrayUnread: noop,
    quitApp: noopAsync,
    getPlatform: () => 'linux',
    showEmojiPanel: noopAsync,
    clipboard: {
      writeText: noopAsync,
    },
    notify: {
      show: noopAsync,
    },
    safeStorage: {
      encrypt: async () => null,
      decrypt: async () => null,
      isAvailable: async () => false,
    },
    appSettings: {
      getLoginItem: async () => ({ openAtLogin: false }),
      setLoginItem: noopAsync,
      getAll: async () => ({}),
      set: async () => ({ changes: 1 }),
    },
    onPowerSuspend: noopUnsub,
    onPowerResume: noopUnsub,
    onSpellcheckReplace: noopUnsub,
    meshcore: {
      tcp: {
        connect: noopAsync,
        write: noopAsync,
        disconnect: noopAsync,
        onData: noopUnsub,
        onDisconnected: noopUnsub,
      },
      openJsonFile: async () => null,
    },
    http: {
      preflight: noopAsync,
      connect: noopAsync,
      write: noopAsync,
      disconnect: noopAsync,
      onData: noopUnsub,
    },
    chat: {
      export: async () => ({ success: false }),
      saveReticulumAttachment: async () => ({ success: false }),
      showItemInFolder: async () => ({ ok: true }),
      linkPreview: {
        fetch: async () => null,
      },
      outbox: {
        list: async () => [],
        add: async (entry: OutboxEntryInput) => stubOutboxEntry(entry),
        updateStatus: noopAsync,
        remove: noopAsync,
      },
    },
    meshtasticXmodem: {
      pickUploadFile: async () => null,
      saveDownloadFile: async () => ({ success: false }),
    },
    log: {
      getPath: async () => '/tmp/dev-browser.log',
      getRecentLines: async () => [],
      clear: noopAsync,
      export: async () => null,
      onLine: noopUnsub,
      logDeviceConnection: noopAsync,
    },
    tak: {
      start: noopAsync,
      stop: noopAsync,
      getStatus: async () => ({ running: false, port: 8089, clientCount: 0 }),
      getConnectedClients: async () => [],
      generateDataPackage: noopAsync,
      regenerateCertificates: noopAsync,
      pushNodeUpdate: noopAsync,
      onStatus: noopUnsub,
      onClientConnected: noopUnsub,
      onClientDisconnected: noopUnsub,
    },
  } as unknown as typeof window.electronAPI;
}

/** Install a no-op bridge when opening the Vite dev server in a plain browser tab. */
export function installDevElectronApiStubIfNeeded(): boolean {
  if (typeof window.electronAPI !== 'undefined') return false;
  if (!import.meta.env.DEV) return false;
  window.electronAPI = createDevElectronApiStub();
  console.debug(
    '[dev] Installed browser electronAPI stub — use the Electron window for RF, SQLite, and IPC',
  );
  return true;
}
