import type { OutboxEntry, OutboxEntryInput } from '@/shared/electron-api.types';
import type { TakStyleSettings } from '@/shared/tak-types';

/* eslint-disable @typescript-eslint/require-await -- no-op async IPC stubs for browser dev */
const noop = (): void => {};
const noopUnsub = (): (() => void) => () => {};
const noopAsync = async (): Promise<void> => {};

function stubOutboxEntry(entry: OutboxEntryInput, id: number): OutboxEntry {
  const now = Date.now();
  return {
    id,
    attemptCount: 0,
    createdAt: now,
    updatedAt: now,
    ...entry,
    priority: entry.priority === 'emergency' ? 'emergency' : 'normal',
  };
}

/** No-op electronAPI for Vite browser dev when Electron preload is unavailable. */
export function createDevElectronApiStub(): typeof window.electronAPI {
  let nextOutboxId = 1;

  return {
    db: {
      saveMessage: noopAsync,
      getMessages: async () => [],
      listMeshtasticDmPeers: async () => [],
      saveNode: noopAsync,
      saveNodePath: noopAsync,
      getNodes: async () => [],
      clearMessages: noopAsync,
      clearNodes: noopAsync,
      deleteNode: noopAsync,
      updateMessageStatus: noopAsync,
      exportDb: async () => null,
      importDb: async () => null,
      deleteNodesByAge: noopAsync,
      deleteNodesNeverHeard: async () => 0,
      pruneNodesByCount: async () => ({ changes: 0 }),
      pruneMessagesByCount: async () => ({ changes: 0 }),
      pruneMeshcoreMessagesByCount: async () => ({ changes: 0 }),
      deleteNodesBatch: async () => 0,
      clearMessagesByChannel: noopAsync,
      getMessageChannels: async () => [],
      getBlockedContacts: async () => [],
      blockContact: async () => ({ changes: 1 }),
      unblockContact: async () => ({ changes: 1 }),
      setNodeFavorited: noopAsync,
      getNodeNote: async () => null,
      setNodeNote: noopAsync,
      deleteNodesBySource: async () => 0,
      migrateRfStubNodes: async () => 0,
      deleteNodesWithoutLongname: async () => 0,
      prunePositionHistory: async () => 0,
      prunePositionHistoryPerNode: async () => 0,
      clearNodePositions: noopAsync,
      updateMessageReceivedVia: noopAsync,
      updateMessagePacketId: noopAsync,
      getMeshcoreMessages: async () => [],
      listMeshcoreDmPeers: async () => [],
      searchMessages: async () => [],
      searchMeshcoreMessages: async () => [],
      getMeshcoreContacts: async () => [],
      saveMeshcoreMessage: noopAsync,
      updateMeshcoreMessageSender: noopAsync,
      saveMeshcoreContact: noopAsync,
      saveMeshcoreContactsBatch: async () => 0,
      updateMeshcoreContactRfTransport: noopAsync,
      updateMeshcoreContactAdvert: noopAsync,
      updateMeshcoreContactType: noopAsync,
      updateMeshcoreContactLastRf: noopAsync,
      updateMeshcoreMessageStatus: noopAsync,
      updateMeshcoreMessageStatusByKey: async () => ({ changes: 1 }),
      deleteMeshcoreContact: noopAsync,
      clearMeshcoreMessages: noopAsync,
      getMeshcoreMessageChannels: async () => [],
      clearMeshcoreMessagesByChannel: noopAsync,
      clearMeshcoreContacts: noopAsync,
      deleteMeshcoreContactsNeverAdvertised: noopAsync,
      deleteMeshcoreContactsByAge: noopAsync,
      pruneMeshcoreContactsByCount: async () => ({ changes: 0 }),
      clearMeshcoreRepeaters: noopAsync,
      markAllMeshcoreContactsOffRadio: noopAsync,
      getMeshcoreContactCount: async () => 0,
      deleteMeshcoreContactsWithoutPubkey: async () => ({ deleted: 0, excludedStubCount: 0 }),
      offloadAllMeshcoreContacts: async () => 0,
      markMeshcoreContactOffRadio: async () => ({ changes: 0 }),
      getMeshcoreContactById: async () => null,
      updateMeshcoreContactNickname: noopAsync,
      updateMeshcoreContactFavorited: noopAsync,
      savePositionHistory: noopAsync,
      getPositionHistory: async () => [],
      clearPositionHistory: noopAsync,
      saveEnvironmentTelemetry: async () => ({ changes: 0 }),
      getEnvironmentTelemetry: async () => [],
      clearEnvironmentTelemetry: async () => ({ changes: 0 }),
      pruneEnvironmentTelemetry: async () => 0,
      saveMeshcoreHopHistory: async () => true,
      getMeshcoreHopHistory: async () => null,
      getAllMeshcoreHopHistory: async () => [],
      saveMeshcoreTraceHistory: async () => true,
      getMeshcoreTraceHistory: async () => [],
      pruneMeshcorePathHistory: async () => true,
      upsertMeshcorePathHistory: async () => true,
      recordMeshcorePathOutcome: async () => true,
      getMeshcorePathHistory: async () => [],
      getAllMeshcorePathHistory: async () => [],
      deleteMeshcorePathHistoryForNode: async () => true,
      deleteAllMeshcorePathHistory: async () => true,
      getContactGroups: async () => [],
      createContactGroup: async () => 1,
      updateContactGroup: noopAsync,
      deleteContactGroup: noopAsync,
      addContactToGroup: noopAsync,
      removeContactFromGroup: noopAsync,
      getContactGroupMembers: async () => [],
    },
    mqtt: {
      connect: noopAsync,
      disconnect: noopAsync,
      powerResume: noopAsync,
      powerSuspend: noopAsync,
      onStatus: noopUnsub,
      onError: noopUnsub,
      onWarning: noopUnsub,
      onNodeUpdate: noopUnsub,
      onMessage: noopUnsub,
      onBrokerRaw: noopUnsub,
      onTraceRouteReply: noopUnsub,
      onClientId: noopUnsub,
      getClientId: async () => '',
      getCachedNodes: async () => [],
      getChannelNameToIndex: async () => ({}),
      updateChannelKeys: noopAsync,
      updateTopicPrefix: noopAsync,
      publish: async () => 1,
      publishProxy: noopAsync,
      publishNodeInfo: async () => 1,
      publishPosition: async () => 1,
      publishWaypoint: async () => 1,
      publishMeshcore: noopAsync,
      publishMeshcorePacketLog: noopAsync,
      onMeshcoreChat: noopUnsub,
      refreshMeshcoreToken: async () => null,
      updateMeshcoreToken: noopAsync,
      onRequestTokenRefresh: noopUnsub,
    },
    onGattAdapterState: noopUnsub,
    onGattDeviceDiscovered: noopUnsub,
    onGattLinkRssi: noopUnsub,
    onGattConnected: noopUnsub,
    onGattDisconnected: noopUnsub,
    onGattConnectAborted: noopUnsub,
    onGattIssue: noopUnsub,
    onGattFromRadio: noopUnsub,
    startGattScanning: async () => ({ ok: true as const }),
    stopGattScanning: noopAsync,
    connectGatt: async () => ({ ok: true }),
    disconnectGatt: noopAsync,
    releaseGattBleCentral: noopAsync,
    clearGattBondRecoveryExclusive: noopAsync,
    isGattConnected: async () => false,
    gattToRadio: noopAsync,
    gattPairState: async () => ({ ok: false as const, code: 'unsupported', error: 'dev stub' }),
    gattPair: async () => ({ ok: false as const, code: 'unsupported', error: 'dev stub' }),
    gattUnpair: async () => ({ ok: false as const, code: 'unsupported', error: 'dev stub' }),
    onSerialPortsDiscovered: noopUnsub,
    selectSerialPort: noop,
    cancelSerialSelection: noop,
    bluetoothUnpair: noopAsync,
    bluetoothStartScan: noopAsync,
    bluetoothStopScan: noopAsync,
    bluetoothPair: noopAsync,
    bluetoothConnect: noopAsync,
    bluetoothUntrust: noopAsync,
    bluetoothGetInfo: async () => '',
    onBluetoothPinRequired: noopUnsub,
    provideBluetoothPin: noop,
    cancelBluetoothPairing: noop,
    resetBlePairingRetryCount: noop,
    clearSessionData: noopAsync,
    getGpsFix: async () => ({ lat: 0, lon: 0, source: 'ip' as const }),
    update: {
      check: noopAsync,
      download: noopAsync,
      install: noopAsync,
      openReleases: noopAsync,
      onAvailable: noopUnsub,
      onNotAvailable: noopUnsub,
      onChecking: noopUnsub,
      onProgress: noopUnsub,
      onDownloaded: noopUnsub,
      onError: noopUnsub,
      onOffline: noopUnsub,
    },
    serviceAnnouncements: {
      fetch: async () => ({ status: 'offline' as const }),
      openUrl: async () => false,
    },
    offlineMaps: {
      estimate: async () => ({ tileCount: 0, sizeEstimateBytes: 0, withinCaps: true }),
      download: async () => ({ jobId: 'stub' }),
      cancel: async () => ({ cancelled: true }),
      status: async () => ({
        activeJobs: [],
        stats: { tileCount: 0, diskBytes: 0 },
        regions: [],
        sources: {},
      }),
      clear: async () => ({ ok: true }),
      onProgress: noopUnsub,
      onDone: noopUnsub,
      onError: noopUnsub,
    },
    notifyDeviceConnected: noop,
    notifyDeviceDisconnected: noop,
    setTrayUnread: noop,
    quitApp: noopAsync,
    restartApp: noopAsync,
    getPlatform: () => 'linux',
    showEmojiPanel: noopAsync,
    clipboard: {
      writeText: noopAsync,
    },
    notify: {
      show: noopAsync,
    },
    safeStorage: {
      encrypt: async () => null,
      decrypt: async () => null,
      isAvailable: async () => false,
    },
    appSettings: {
      getLoginItem: async () => ({ openAtLogin: false }),
      setLoginItem: noopAsync,
      getAll: async () => ({}),
      set: async () => ({ changes: 1 }),
    },
    onPowerSuspend: noopUnsub,
    onPowerResume: noopUnsub,
    sendRendererHeartbeat: async () => {},
    getProcessUptimeSec: async () => 0,
    app: {
      getRendererLiveness: async () => ({
        mainUptimeSec: 0,
        lastRendererHeartbeatAgeMs: null,
        rendererUnresponsiveSeen: false,
        rss: 0,
        heapUsed: 0,
      }),
      focusWindow: noopAsync,
      requestAttention: noopAsync,
    },
    onSpellcheckReplace: noopUnsub,
    meshcore: {
      tcp: {
        connect: noopAsync,
        write: noopAsync,
        disconnect: noopAsync,
        onData: noopUnsub,
        onDisconnected: noopUnsub,
      },
      openJsonFile: async () => null,
    },
    http: {
      preflight: noopAsync,
      connect: noopAsync,
      write: noopAsync,
      disconnect: noopAsync,
      onData: noopUnsub,
    },
    hostLink: {
      probeHttpRtt: async () => null,
      probeTcpRtt: async () => null,
      getSessionMeter: async () => null,
    },
    meshtastic: {
      tcp: {
        connect: noopAsync,
        write: noopAsync,
        disconnect: noopAsync,
        onData: noopUnsub,
        onDisconnected: noopUnsub,
      },
    },
    mecp: {
      appendReceived: async () => ({ ok: true as const }),
      exportReceivedLog: async () => ({ success: false }),
    },
    chat: {
      export: async () => ({ success: false }),
      linkPreview: {
        fetch: async () => null,
      },
      outbox: {
        list: async () => [],
        add: async (entry: OutboxEntryInput) => stubOutboxEntry(entry, nextOutboxId++),
        updateStatus: noopAsync,
        remove: noopAsync,
      },
    },
    meshtasticXmodem: {
      pickUploadFile: async () => null,
      saveDownloadFile: async () => ({ success: false }),
    },
    support: {
      exportBundle: async () => null,
    },
    log: {
      getPath: async () => '/tmp/dev-browser.log',
      getRecentLines: async () => [],
      clear: noopAsync,
      export: async () => null,
      onLine: noopUnsub,
      logDeviceConnection: noopAsync,
    },
    tak: {
      start: noopAsync,
      stop: noopAsync,
      getStatus: async () => ({ running: false, port: 8089, clientCount: 0 }),
      getConnectedClients: async () => [],
      generateDataPackage: noopAsync,
      regenerateCertificates: noopAsync,
      pushNodeUpdates: noopAsync,
      onStatus: noopUnsub,
      onClientConnected: noopUnsub,
      onClientDisconnected: noopUnsub,
      onClientUpdated: noopUnsub,
      getContacts: () => Promise.resolve([]),
      onContacts: noopUnsub,
      remoteStart: noopAsync,
      remoteStop: noopAsync,
      remoteGetStatus: async () => ({ state: 'disconnected' as const, host: '', port: 8089 }),
      remoteGetSettings: async () => null,
      remoteGetCredentials: async () => ({ caSubjects: [] }),
      remoteImportCredentials: async () => null,
      remoteEnroll: async () => ({ caSubjects: [] }),
      remoteClearCredentials: async () => ({ caSubjects: [] }),
      onRemoteStatus: noopUnsub,
      getStyleSettings: async () => ({ filters: [], sendUnmatched: true }),
      setStyleSettings: async (settings: TakStyleSettings) => settings,
      pushChatMessage: async () => {},
    },
    bleCoexistence: {
      register: async () => ({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      unregister: async () => ({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      assertCanConnect: async () => ({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      getState: async () => ({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      acquireScan: async () => ({
        ok: true as const,
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      releaseScan: async () => ({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
    },
  } as unknown as typeof window.electronAPI;
}

const DEV_STUB_MARK = Symbol.for('mesh-client.devElectronApiStub');

/**
 * True when the renderer runs in a plain browser on the no-op bridge. There is no main process
 * behind it, so nothing serves its custom schemes (`mesh-tiles:`) and such a request can only fail.
 */
export function isDevElectronApiStub(api: unknown = window.electronAPI): boolean {
  return typeof api === 'object' && api !== null && DEV_STUB_MARK in api;
}

/** Install a no-op bridge when opening the Vite dev server in a plain browser tab. */
export function installDevElectronApiStubIfNeeded(): boolean {
  if (typeof window.electronAPI !== 'undefined') return false;
  if (!import.meta.env.DEV) return false;
  const stub = createDevElectronApiStub();
  Object.defineProperty(stub, DEV_STUB_MARK, { value: true });
  window.electronAPI = stub;
  console.debug(
    '[dev] Installed browser electronAPI stub — use the Electron window for RF, SQLite, and IPC',
  );
  return true;
}
