; electron-builder NSIS include — post-extract guard for silent partial installs (WoA).
; customFinish is not invoked by electron-builder; customInstall runs after files land.
; schema-upgrade-notice.nsh is generated by scripts/write-schema-upgrade-notice.mjs when
; this build bumps CURRENT_SCHEMA_VERSION vs the last published release.

!include /NONFATAL "${BUILD_RESOURCES_DIR}\schema-upgrade-notice.nsh"

!macro customInstall
  IfFileExists "$INSTDIR\Mesh-client.exe" finish_ok 0
    SetErrorLevel 2
    MessageBox MB_ICONSTOP|MB_OK "Installation incomplete: Mesh-client.exe is missing from $INSTDIR.$\r$\nPlease report this at github.com/Colorado-Mesh/mesh-client/issues." /SD IDOK
    Abort
  finish_ok:
  !ifdef MESH_CLIENT_SCHEMA_UPGRADE_NOTICE
    MessageBox MB_ICONEXCLAMATION|MB_OK "${MESH_CLIENT_SCHEMA_UPGRADE_NOTICE}" /SD IDOK
  !endif
!macroend
