import type {
  SettingSearchEntry,
  SettingsSearchContext,
  SettingsSearchSurface,
} from '../settingsSearch';

// AppPanel renders some blocks per protocol; these mirror those blocks with capability flags.
const hasNodeDbRetention = (ctx: SettingsSearchContext) => ctx.capabilities.hasNodeDbReset;
const hasContactRetention = (ctx: SettingsSearchContext) =>
  ctx.capabilities.nodeListTabUsesContactsLabel;
const hasDestinationRetention = (ctx: SettingsSearchContext) =>
  ctx.capabilities.hasReticulumPeersList;

const DANGER = 'appPanel.dangerZoneSection';
const RETENTION = 'appPanel.retentionLimitsHeading';

const appEntries: readonly SettingSearchEntry[] = [
  {
    id: 'app.protocols.enabled',
    slot: 'App',
    labelKey: 'appPanel.protocolsSection',
    keywords: ['meshtastic', 'meshcore', 'reticulum', 'enable', 'hide', 'protocol'],
  },
  {
    id: 'app.logPanel.showLogPanel',
    slot: 'App',
    labelKey: 'appPanel.showLogPanel',
    sectionKey: 'appPanel.logPanelSection',
    keywords: ['log', 'debug', 'console'],
  },
  {
    id: 'app.floodAdvert.schedule',
    slot: 'App',
    labelKey: 'appPanel.floodAdvertScheduleLabel',
    sectionKey: 'appPanel.floodAdvertSection',
    keywords: ['advert', 'advertise', 'interval', 'flood'],
    visible: (ctx) => ctx.capabilities.hasCompanionContactManagementConfig,
  },
  {
    id: 'app.floodAdvert.type',
    slot: 'App',
    labelKey: 'appPanel.floodAdvertTypeLabel',
    sectionKey: 'appPanel.floodAdvertSection',
    keywords: ['advert', 'zero hop', 'flood'],
    visible: (ctx) => ctx.capabilities.hasCompanionContactManagementConfig,
  },
  {
    id: 'app.gps.shareLocation',
    slot: 'App',
    labelKey: 'appPanel.shareMyLocation',
    sectionKey: 'appPanel.gpsSection',
    keywords: ['gps', 'location', 'position', 'privacy'],
  },
  {
    id: 'app.gps.savedLocations',
    slot: 'App',
    labelKey: 'locationPrompt.listHeading',
    sectionKey: 'appPanel.gpsSection',
    keywords: ['gps', 'fixed', 'static', 'location', 'home'],
  },
  {
    id: 'app.gps.refreshInterval',
    slot: 'App',
    labelKey: 'appPanel.autoRefreshInterval',
    sectionKey: 'appPanel.gpsSection',
    keywords: ['gps', 'interval', 'refresh'],
  },
  {
    id: 'app.gps.coordinateFormat',
    slot: 'App',
    labelKey: 'appPanel.coordinateFormat',
    sectionKey: 'appPanel.gpsSection',
    keywords: ['mgrs', 'decimal', 'latitude', 'longitude', 'coordinates'],
  },
  {
    id: 'app.gps.refreshNow',
    slot: 'App',
    labelKey: 'appPanel.gpsRefreshNow',
    sectionKey: 'appPanel.gpsSection',
    keywords: ['gps', 'location'],
  },
  {
    id: 'app.mapFilter.distantNodes',
    slot: 'App',
    labelKey: 'appPanel.filterDistantNodesCheckbox',
    sectionKey: 'appPanel.mapFilterSection',
    keywords: ['distance', 'filter', 'map'],
  },
  {
    id: 'app.mapFilter.maxDistance',
    slot: 'App',
    labelKey: 'appPanel.maxDistanceLabel',
    sectionKey: 'appPanel.mapFilterSection',
    keywords: ['distance', 'miles', 'km', 'unit'],
  },
  {
    id: 'app.mapFilter.hideMqttOnly',
    slot: 'App',
    labelKey: 'appPanel.hideMqttOnlyNodes',
    sectionKey: 'appPanel.mapFilterSection',
    keywords: ['mqtt', 'filter'],
  },
  {
    id: 'app.mapFilter.movementPaths',
    slot: 'App',
    labelKey: 'appPanel.showMovementPaths',
    sectionKey: 'appPanel.mapFilterSection',
    keywords: ['trail', 'track', 'map', 'history'],
  },
  {
    id: 'app.mapFilter.historyWindow',
    slot: 'App',
    labelKey: 'appPanel.positionHistoryWindowLabel',
    sectionKey: 'appPanel.mapFilterSection',
    keywords: ['trail', 'track', 'history'],
  },
  {
    id: 'app.retention.autoPruneNodes',
    slot: 'App',
    labelKey: 'appPanel.autoPruneNodesOlderThan',
    sectionKey: RETENTION,
    keywords: ['prune', 'cleanup', 'old nodes'],
    visible: hasNodeDbRetention,
  },
  {
    id: 'app.retention.pruneUnnamedNodes',
    slot: 'App',
    labelKey: 'appPanel.removeUnnamedNodesLabel',
    sectionKey: RETENTION,
    keywords: ['prune', 'unnamed', 'cleanup'],
    visible: hasNodeDbRetention,
  },
  {
    id: 'app.retention.nodeCap',
    slot: 'App',
    labelKey: 'appPanel.capTotalNodesLabel',
    sectionKey: RETENTION,
    keywords: ['limit', 'max nodes'],
    visible: hasNodeDbRetention,
  },
  {
    id: 'app.retention.positionHistoryPrune',
    slot: 'App',
    labelKey: 'appPanel.autoPrunePositionHistoryLabel',
    sectionKey: RETENTION,
    keywords: ['prune', 'position', 'history'],
    visible: hasNodeDbRetention,
  },
  {
    id: 'app.retention.neverAdvertisedContacts',
    slot: 'App',
    labelKey: 'appPanel.meshcoreRemoveNeverAdvertisedLabel',
    sectionKey: RETENTION,
    keywords: ['prune', 'advert', 'cleanup'],
    visible: hasContactRetention,
  },
  {
    id: 'app.retention.autoPruneContacts',
    slot: 'App',
    labelKey: 'appPanel.autoPruneUnheardContactsLabel',
    sectionKey: RETENTION,
    keywords: ['prune', 'cleanup', 'old contacts'],
    visible: hasContactRetention,
  },
  {
    id: 'app.retention.contactCap',
    slot: 'App',
    labelKey: 'appPanel.capTotalContactsLabel',
    sectionKey: RETENTION,
    keywords: ['limit', 'max contacts'],
    visible: hasContactRetention,
  },
  {
    id: 'app.retention.autoPruneDestinations',
    slot: 'App',
    labelKey: 'appPanel.reticulumAutoPruneDestinationsLabel',
    sectionKey: RETENTION,
    keywords: ['prune', 'peers', 'cleanup'],
    visible: hasDestinationRetention,
  },
  {
    id: 'app.retention.destinationCap',
    slot: 'App',
    labelKey: 'appPanel.reticulumCapDestinationsLabel',
    sectionKey: RETENTION,
    keywords: ['limit', 'peers'],
    visible: hasDestinationRetention,
  },
  {
    id: 'app.retention.messageLimit',
    slot: 'App',
    labelKey: 'appPanel.limitMessagesLoadedLabel',
    sectionKey: RETENTION,
    keywords: ['messages', 'history', 'load'],
  },
  {
    id: 'app.retention.meshtasticMessageCap',
    slot: 'App',
    labelKey: 'appPanel.capStoredMessagesLabel',
    sectionKey: RETENTION,
    keywords: ['messages', 'retention', 'database'],
    visible: hasNodeDbRetention,
  },
  {
    id: 'app.retention.meshcoreMessageCap',
    slot: 'App',
    labelKey: 'appPanel.capStoredMessagesLabel',
    sectionKey: RETENTION,
    keywords: ['messages', 'retention', 'database'],
    visible: hasContactRetention,
  },
  {
    id: 'app.retention.reticulumMessageCap',
    slot: 'App',
    labelKey: 'appPanel.capStoredMessagesLabel',
    sectionKey: RETENTION,
    keywords: ['messages', 'retention', 'database'],
    visible: hasDestinationRetention,
  },
  {
    id: 'app.retention.rrcMessageCap',
    slot: 'App',
    labelKey: 'appPanel.capStoredRrcMessagesLabel',
    sectionKey: RETENTION,
    keywords: ['rrc', 'rooms', 'retention'],
    visible: (ctx) => ctx.capabilities.hasRrcPanel,
  },
  {
    id: 'app.retention.compactMessages',
    slot: 'App',
    labelKey: 'appPanel.compactMessages',
    sectionKey: RETENTION,
    keywords: ['chat', 'density', 'compact'],
  },
  {
    id: 'app.retention.alwaysShowMessageActions',
    slot: 'App',
    labelKey: 'appPanel.alwaysShowMessageActions',
    sectionKey: RETENTION,
    keywords: ['chat', 'reply', 'react', 'actions'],
  },
  {
    id: 'app.retention.storeForwardHistory',
    slot: 'App',
    labelKey: 'appPanel.storeForwardAutoFetchHistory',
    sectionKey: RETENTION,
    keywords: ['store and forward', 's&f', 'history'],
    visible: (ctx) => ctx.capabilities.hasStoreForward,
  },
  {
    id: 'app.retention.storeForwardProfile',
    slot: 'App',
    labelKey: 'appPanel.storeForwardHistoryProfileLabel',
    sectionKey: RETENTION,
    keywords: ['store and forward', 's&f', 'aggressive', 'conservative'],
    visible: (ctx) => ctx.capabilities.hasStoreForward,
  },
  {
    id: 'app.retention.shareLocationWaypoint',
    slot: 'App',
    labelKey: 'appPanel.shareLocationSendWaypoint',
    sectionKey: RETENTION,
    keywords: ['waypoint', 'location', 'share'],
    visible: hasNodeDbRetention,
  },
  {
    id: 'app.support.exportForGitHub',
    slot: 'App',
    labelKey: 'appPanel.exportForGitHubButton',
    sectionKey: 'appPanel.supportSection',
    keywords: ['bug', 'report', 'support bundle', 'logs'],
  },
  {
    id: 'app.support.exportForDeveloper',
    slot: 'App',
    labelKey: 'appPanel.exportForDeveloperButton',
    sectionKey: 'appPanel.supportSection',
    keywords: ['bug', 'report', 'support bundle', 'logs'],
  },
  {
    id: 'app.data.exportDatabase',
    slot: 'App',
    labelKey: 'appPanel.exportDatabaseButton',
    sectionKey: 'appPanel.dataManagementSection',
    keywords: ['backup', 'database', 'sqlite'],
  },
  {
    id: 'app.data.copyDebugSnapshot',
    slot: 'App',
    labelKey: 'appPanel.copyDebugSnapshotButton',
    sectionKey: 'appPanel.dataManagementSection',
    keywords: ['debug', 'diagnostics', 'clipboard'],
  },
  {
    id: 'app.data.importMerge',
    slot: 'App',
    labelKey: 'appPanel.importMergeButton',
    sectionKey: 'appPanel.dataManagementSection',
    keywords: ['restore', 'database', 'import'],
  },
  {
    id: 'app.appearance.reduceMotion',
    slot: 'App',
    labelKey: 'appPanel.reduceMotion',
    sectionKey: 'appPanel.appearanceSection',
    keywords: ['animation', 'accessibility'],
  },
  {
    id: 'app.appearance.use24HourTime',
    slot: 'App',
    labelKey: 'appPanel.use24HourTime',
    sectionKey: 'appPanel.appearanceSection',
    keywords: ['clock', 'time format'],
  },
  {
    id: 'app.appearance.fontSize',
    slot: 'App',
    labelKey: 'appPanel.fontSize',
    sectionKey: 'appPanel.appearanceSection',
    keywords: ['text size', 'zoom', 'scale', 'accessibility'],
  },
  {
    id: 'app.appearance.themePresets',
    slot: 'App',
    labelKey: 'appPanel.themePresets.heading',
    sectionKey: 'appPanel.appearanceSection',
    keywords: ['theme', 'colors', 'accent', 'dark'],
  },
  {
    id: 'app.appearance.colorScheme',
    slot: 'App',
    labelKey: 'appPanel.colorScheme',
    sectionKey: 'appPanel.appearanceSection',
    keywords: ['theme', 'colors', 'custom'],
  },
  {
    id: 'app.appearance.messageActionsBackground',
    slot: 'App',
    labelKey: 'appPanel.messageActionsBarBgVisible',
    sectionKey: 'appPanel.colorScheme',
    keywords: ['message actions', 'background'],
  },
  {
    id: 'app.appearance.saveTheme',
    slot: 'App',
    labelKey: 'appPanel.saveThemeButton',
    sectionKey: 'appPanel.colorScheme',
    keywords: ['theme', 'restore', 'reset colors'],
  },
  {
    id: 'app.notifications.sound',
    slot: 'App',
    labelKey: 'appPanel.soundNotifications',
    sectionKey: 'appPanel.notificationsSection',
    keywords: ['sound', 'audio', 'alert'],
  },
  {
    id: 'app.notifications.sounds',
    slot: 'App',
    labelKey: 'notificationSounds.title',
    sectionKey: 'appPanel.notificationsSection',
    keywords: ['tone', 'volume', 'ringtone'],
  },
  {
    id: 'app.notifications.nodeSilenceAlert',
    slot: 'App',
    labelKey: 'appPanel.nodeSilenceAlertMinutes',
    sectionKey: 'appPanel.opsAlertsHeading',
    keywords: ['silent', 'offline', 'alert'],
  },
  {
    id: 'app.notifications.batteryLow',
    slot: 'App',
    labelKey: 'appPanel.nodeBatteryLowThreshold',
    sectionKey: 'appPanel.opsAlertsHeading',
    keywords: ['battery', 'alert'],
  },
  {
    id: 'app.notifications.linkDown',
    slot: 'App',
    labelKey: 'appPanel.notifyOnLinkDown',
    sectionKey: 'appPanel.opsAlertsHeading',
    keywords: ['disconnect', 'alert'],
  },
  {
    id: 'app.notifications.rrcUnreadAll',
    slot: 'App',
    labelKey: 'appPanel.rrcUnreadAllRoomMessages',
    sectionKey: 'appPanel.notificationsSection',
    keywords: ['rrc', 'rooms', 'unread'],
    visible: (ctx) => ctx.capabilities.hasRrcPanel,
  },
  {
    id: 'app.translation',
    slot: 'App',
    labelKey: 'chatTranslation.settingsTitle',
    keywords: ['translation', 'translate', 'language', 'offline', 'libretranslate'],
  },
  {
    id: 'app.translation.enabled',
    slot: 'App',
    labelKey: 'chatTranslation.enabled',
    keywords: ['translation', 'translate', 'language', 'offline', 'libretranslate'],
  },
  {
    id: 'app.translation.target',
    slot: 'App',
    labelKey: 'chatTranslation.target',
    keywords: ['translation', 'translate', 'language', 'offline', 'libretranslate'],
  },
  {
    id: 'app.translation.readLanguages',
    slot: 'App',
    labelKey: 'chatTranslation.readLanguages',
    keywords: ['translation', 'translate', 'language', 'offline', 'libretranslate'],
  },
  {
    id: 'app.translation.auto',
    slot: 'App',
    labelKey: 'chatTranslation.auto',
    keywords: ['translation', 'translate', 'language', 'offline', 'libretranslate'],
  },
  {
    id: 'app.translation.packs',
    slot: 'App',
    labelKey: 'chatTranslation.packs',
    keywords: ['translation', 'translate', 'language', 'offline', 'libretranslate'],
  },
  {
    id: 'app.translation.libre',
    slot: 'App',
    labelKey: 'chatTranslation.serverUrl',
    keywords: ['translation', 'translate', 'language', 'offline', 'libretranslate'],
  },
  {
    id: 'app.translation.removeAll',
    slot: 'App',
    labelKey: 'chatTranslation.removeAll',
    keywords: ['translation', 'translate', 'language', 'offline', 'libretranslate'],
  },
  {
    id: 'app.mecp.showComposeButton',
    slot: 'App',
    labelKey: 'mecp.section.showComposeButton',
    sectionKey: 'mecp.section.title',
    keywords: ['mecp', 'emergency', 'report'],
  },
  {
    id: 'app.mecp.standingAlert',
    slot: 'App',
    labelKey: 'mecp.section.standingAlert',
    sectionKey: 'mecp.section.title',
    keywords: ['mecp', 'mayday', 'urgent', 'banner', 'eoc', 'incident command', 'alert'],
  },
  {
    id: 'app.mecp.repeatAlert',
    slot: 'App',
    labelKey: 'appPanel.mecpRepeatAlertMinutes',
    sectionKey: 'mecp.section.title',
    keywords: ['mecp', 'mayday', 'urgent', 'repeat', 'siren', 'alert'],
  },
  {
    id: 'app.mecp.blockedSenders',
    slot: 'App',
    labelKey: 'mecp.block.listTitle',
    sectionKey: 'mecp.section.title',
    keywords: ['mecp', 'block', 'spam', 'mayday', 'unblock'],
  },
  {
    id: 'app.blockedNodes',
    slot: 'App',
    labelKey: 'appPanel.loraBlocklist.title',
    sectionKey: 'appPanel.loraBlocklist.title',
    keywords: ['block', 'unblock', 'spam', 'ignore', 'node'],
    visible: (ctx) => !ctx.capabilities.hasReticulumInterfaceConfig,
  },
  {
    id: 'app.mecp.exportLog',
    slot: 'App',
    labelKey: 'mecp.exportLog',
    sectionKey: 'mecp.section.title',
    keywords: ['mecp', 'emergency', 'audit'],
  },
  {
    id: 'app.mecp.rebroadcast',
    slot: 'App',
    labelKey: 'mecp.rebroadcast.title',
    sectionKey: 'mecp.section.title',
    keywords: ['mecp', 'emergency', 'relay', 'bridge'],
  },
  {
    id: 'app.danger.resetDiagnostics',
    slot: 'App',
    labelKey: 'appPanel.resetDiagnostics',
    sectionKey: DANGER,
    keywords: ['clear', 'diagnostics'],
  },
  {
    id: 'app.danger.clearGpsData',
    slot: 'App',
    labelKey: 'appPanel.clearGpsData',
    sectionKey: DANGER,
    keywords: ['gps', 'location', 'delete'],
  },
  {
    id: 'app.danger.clearPositionHistory',
    slot: 'App',
    labelKey: 'appPanel.clearPositionHistory',
    sectionKey: DANGER,
    keywords: ['trail', 'track', 'delete'],
  },
  {
    id: 'app.danger.deleteOldNodes',
    slot: 'App',
    labelKey: 'appPanel.deleteOldNodes',
    sectionKey: DANGER,
    keywords: ['prune', 'delete', 'cleanup'],
  },
  {
    id: 'app.danger.pruneMqttOnlyNodes',
    slot: 'App',
    labelKey: 'appPanel.pruneMqttOnlyNodes',
    sectionKey: DANGER,
    keywords: ['mqtt', 'delete', 'cleanup'],
  },
  {
    id: 'app.danger.pruneUnnamedNodes',
    slot: 'App',
    labelKey: 'appPanel.pruneUnnamedNodes',
    sectionKey: DANGER,
    keywords: ['unnamed', 'delete', 'cleanup'],
  },
  {
    id: 'app.danger.pruneNoFixNodes',
    slot: 'App',
    labelKey: 'appPanel.pruneNoFixNodesTitle',
    sectionKey: DANGER,
    keywords: ['gps', 'delete', 'cleanup'],
  },
  {
    id: 'app.danger.pruneDistantNodes',
    slot: 'App',
    labelKey: 'appPanel.pruneDistantNodesTitle',
    sectionKey: DANGER,
    keywords: ['distance', 'delete', 'cleanup'],
  },
  {
    id: 'app.danger.pruneOfflineNodes',
    slot: 'App',
    labelKey: 'appPanel.pruneOfflineNodesTitle',
    sectionKey: DANGER,
    keywords: ['offline', 'delete', 'cleanup'],
  },
  {
    id: 'app.danger.clearAllNodes',
    slot: 'App',
    labelKey: 'appPanel.clearAllNodesButton',
    sectionKey: DANGER,
    keywords: ['delete', 'wipe', 'nodes'],
  },
  {
    id: 'app.danger.deleteContactsWithoutPubkeys',
    slot: 'App',
    labelKey: 'appPanel.deleteContactsNoPubkeysTitle',
    sectionKey: DANGER,
    keywords: ['public key', 'delete', 'cleanup'],
    visible: hasContactRetention,
  },
  {
    id: 'app.danger.clearReticulumContacts',
    slot: 'App',
    labelKey: 'appPanel.clearReticulumContactsButton',
    sectionKey: DANGER,
    keywords: ['delete', 'peers', 'wipe'],
    visible: hasDestinationRetention,
  },
  {
    id: 'app.danger.clearMessages',
    slot: 'App',
    labelKey: 'appPanel.clearMessagesCount',
    sectionKey: DANGER,
    keywords: ['delete', 'chat', 'history', 'wipe'],
  },
  {
    id: 'app.danger.clearAllRepeaters',
    slot: 'App',
    labelKey: 'appPanel.clearAllRepeaters',
    sectionKey: DANGER,
    keywords: ['delete', 'repeaters'],
    visible: (ctx) => ctx.capabilities.modulesTabUsesRepeatersLabel,
  },
  {
    id: 'app.danger.clearAllLocalData',
    slot: 'App',
    labelKey: 'appPanel.clearAllLocalData',
    sectionKey: DANGER,
    keywords: ['reset', 'factory', 'wipe', 'delete everything'],
  },
];

export const appSurface: SettingsSearchSurface = {
  entries: appEntries,
  files: [
    { path: 'src/renderer/components/AppPanel.tsx', sweepAllKeys: true },
    { path: 'src/renderer/components/AppTranslationSection.tsx', sweepAllKeys: true },
  ],
  exempt: {
    'chatTranslation.offlinePrivacy':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.optInDescription':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.enable':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.installed':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.yourLanguages':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.readLanguagesHint':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.autoTitle':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.autoDescription':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.autoNeedsPacks':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.neededTitle':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.pivotHint':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.neededComplete':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.neededSummary':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.downloadNeeded':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.allPacks':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.searchLanguages':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.noLanguagesMatch':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.packLanguage':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.intoEnglish':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.fromEnglish':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.unavailable':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.queued':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.downloadFailed':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.retry':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.downloadSize':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.engine':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.progress':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.cancelPack':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.cancel':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.deletePack':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.downloadPack':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.delete':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.onlinePrivacy':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.apiKey':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.savedKey':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.onlineEnabled':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.test':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.testSuccess':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.clearKey':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.diskUsage':
      'Translation section help, status, or child action; its parent setting is indexed',
    'chatTranslation.settingsError':
      'Translation section help, status, or child action; its parent setting is indexed',

    'appPanel.*Hint': 'help text under a control; the control is indexed',
    'appPanel.*Desc': 'description text; its control is indexed',
    'appPanel.*Aria': 'accessible-name variant of an indexed control',
    'appPanel.*Confirm*': 'confirmation dialog copy for an indexed action',
    'appPanel.*Title': 'confirmation dialog title for an indexed action',
    'appPanel.*Subtitle': 'second line of an indexed Danger Zone row',
    'appPanel.*Failed': 'error toast, not a control',
    'appPanel.dangerZone*': 'Danger Zone sub-headings and intro; each action row is indexed',
    'appPanel.gpsInterval*': 'option values of the indexed GPS refresh interval',
    'appPanel.gpsSource*': 'status text showing where the position came from',
    'appPanel.historyWindow*': 'option values of the indexed position history window',
    'appPanel.floodAdvertEvery*': 'option values of the indexed flood advert schedule',
    'appPanel.floodAdvertType*': 'option values of the indexed flood advert type',
    'appPanel.coordFormat*': 'option values of the indexed coordinate format',
    'appPanel.distanceUnit*': 'option values of the indexed max distance unit',
    'appPanel.storeForwardHistoryProfile*': 'option values of the indexed S&F history profile',
    'appPanel.theme*Kept': 'theme toast, not a control',
    'appPanel.no*': 'empty-result toast or status text, not a control',
    'appPanel.title': 'panel heading; the launcher already lists the App panel',
    'appPanel.protocolEnabled': 'per-protocol checkbox name inside the indexed Protocols card',
    'appPanel.protocolLastEnabled': 'tooltip on the last enabled protocol',
    'appPanel.logPanelHelp': 'help text for the indexed log panel toggle',
    'appPanel.floodAdvertHelp': 'help text for the indexed flood advert schedule',
    'appPanel.failedSaveRetention': 'error toast, not a control',
    'appPanel.destructiveActions': 'Danger Zone disclosure summary; each action row is indexed',
    'appPanel.shareMyLocationOffInfo': 'status text for the indexed share location toggle',
    'appPanel.autoRefreshDisabledStatic': 'status text for the indexed GPS refresh interval',
    'appPanel.gpsRefreshing': 'busy label of the indexed GPS refresh button',
    'appPanel.filterDistantNodes': 'accessible name of the indexed distant-node filter',
    'appPanel.unitLabel': 'unit label beside the indexed max distance field',
    'appPanel.requiresGpsFix': 'help text for the indexed distance filter',
    'appPanel.removeUnnamedNodes': 'accessible name of the indexed unnamed-node toggle',
    'appPanel.capTotalNodes': 'accessible name of the indexed node cap',
    'appPanel.autoPrunePositionHistory': 'accessible name of the indexed position-history prune',
    'appPanel.removeContactsNeverAdvertised':
      'accessible name of the indexed never-advertised toggle',
    'appPanel.autoPruneUnheardContacts': 'accessible name of the indexed contact auto-prune',
    'appPanel.capTotalContacts': 'accessible name of the indexed contact cap',
    'appPanel.reticulumAutoPruneDestinations': 'accessible name of the indexed destination prune',
    'appPanel.reticulumCapDestinations': 'accessible name of the indexed destination cap',
    'appPanel.reticulumDestinationsUnit': 'unit beside the indexed destination cap',
    'appPanel.messagesLoadLimitIntro': 'card intro; its rows are indexed',
    'appPanel.limitMessagesLoaded': 'accessible name of the indexed message load limit',
    'appPanel.capStoredMessages': 'accessible name of the indexed stored-message caps',
    'appPanel.capStoredRrcMessages': 'accessible name of the indexed RRC message cap',
    'appPanel.supportSectionDesc': 'section prose, no control',
    'appPanel.exportForGitHub': 'accessible name of the indexed GitHub export button',
    'appPanel.exportForDeveloper': 'accessible name of the indexed developer export button',
    'appPanel.exportForDeveloperWarning': 'warning text under the indexed developer export',
    'appPanel.exportedTo': 'success toast, not a control',
    'appPanel.unknownError': 'error toast fallback, not a control',
    'appPanel.exportDatabase': 'accessible name of the indexed export button',
    'appPanel.copyDebugSnapshot': 'accessible name of the indexed debug snapshot button',
    'appPanel.debugSnapshotCopied': 'success toast, not a control',
    'appPanel.importMerge': 'accessible name of the indexed import button',
    'appPanel.dbMerged': 'success toast, not a control',
    'appPanel.importSchemaTooNew': 'error toast, not a control',
    'appPanel.decreaseFontSize': 'stepper button of the indexed font size control',
    'appPanel.increaseFontSize': 'stepper button of the indexed font size control',
    'appPanel.resetFontSize': 'reset link of the indexed font size control',
    'appPanel.saveTheme': 'accessible name of the indexed save theme button',
    'appPanel.restoreTheme': 'theme snapshot button grouped under the indexed save theme row',
    'appPanel.restoreThemeButton': 'theme snapshot button grouped under the indexed save theme row',
    'appPanel.resetAllColors': 'theme button grouped under the indexed save theme row',
    'appPanel.resetAllColorsButton': 'theme button grouped under the indexed save theme row',
    'appPanel.themeSaved': 'success toast, not a control',
    'appPanel.themeRestored': 'success toast, not a control',
    'appPanel.colorsReset': 'success toast, not a control',
    'appPanel.nodeSilenceAlertMinutesPlaceholder': 'placeholder of the indexed node silence alert',
    'appPanel.mecpRepeatAlertMinutesPlaceholder':
      'placeholder of the indexed MECP repeat-alert interval',
    'appPanel.roomMessages': 'channel option label in the Danger Zone clear-messages picker',
    'appPanel.channelOption': 'channel option label in the Danger Zone clear-messages picker',
    'appPanel.channelOptionUnnamed':
      'channel option label in the Danger Zone clear-messages picker',
    'appPanel.allChannelsOption': 'channel option label in the Danger Zone clear-messages picker',
    'appPanel.clearChannelLabel': 'channel picker label of the indexed clear-messages action',
    'appPanel.messagesSection': 'Danger Zone sub-heading; the clear-messages action is indexed',
    'appPanel.actionCompleted': 'toast, not a control',
    'appPanel.deleteNodesOlderThanLabel': 'field label of the indexed delete-old-nodes action',
    'appPanel.pruneNoFixNodes': 'accessible name of the indexed no-fix prune row',
    'appPanel.pruneDistantNodes': 'accessible name of the indexed distant prune row',
    'appPanel.pruneOfflineNodes': 'accessible name of the indexed offline prune row',
    'appPanel.daySingular': 'unit word inside a confirmation message',
    'appPanel.deleteNodesWithoutPubkeys': 'accessible name of the indexed no-pubkey cleanup row',
    'appPanel.deletedContactsNoPubkey': 'success toast, not a control',
    'chatPanel.clearChannelMessagesChanged': 'warning toast, not a control',
    'chatPanel.clearChannelMessagesRadioChanged': 'warning toast, not a control',
    'radioPanel.directMessages': 'channel option label in the Danger Zone clear-messages picker',
    'mecp.section.hint': 'section prose, no control',
    'mecp.section.showComposeButtonHint': 'help text for the indexed MECP compose toggle',
    'mecp.section.standingAlertHint': 'help text for the indexed standing-alert toggle',
    'mecp.section.learnMore': 'external documentation link',
    'mecp.section.protocolSource': 'external source link',
    'mecp.exportLog*': 'result toasts of the indexed MECP log export',
  },
};
