import type {
  SettingSearchEntry,
  SettingsSearchContext,
  SettingsSearchSurface,
} from '../settingsSearch';

const hasMqtt = (ctx: SettingsSearchContext) => ctx.capabilities.hasMqttConnectionPanel;
const hasMeshtasticMqtt = (ctx: SettingsSearchContext) => ctx.capabilities.hasMqttHybrid;
const hasMeshcoreMqtt = (ctx: SettingsSearchContext) =>
  ctx.capabilities.hasMqttConnectionPanel && !ctx.capabilities.hasMqttHybrid;
// HTTP/TCP host fields: Meshtastic nodes on Wi-Fi vs MeshCore companion TCP.
const hasNetworkNodeAddress = (ctx: SettingsSearchContext) => ctx.capabilities.hasWifiConfig;
const hasCompanionTcpHost = (ctx: SettingsSearchContext) => !ctx.capabilities.hasWifiConfig;

const RADIO = 'connectionPanel.radioConnection';
const MQTT = 'connectionPanel.mqttConnection';
const LAST = 'connectionPanel.lastConnectionLabel';

const connectionEntries: readonly SettingSearchEntry[] = [
  {
    id: 'connection.radio.connectionType',
    slot: 'Connection',
    labelKey: 'connectionPanel.connectionType',
    sectionKey: RADIO,
    keywords: ['bluetooth', 'ble', 'serial', 'usb', 'wifi', 'http', 'tcp', 'transport'],
  },
  {
    id: 'connection.radio.httpAddress',
    slot: 'Connection',
    labelKey: 'connectionPanel.deviceAddress',
    sectionKey: RADIO,
    keywords: ['http', 'wifi', 'ip', 'host', 'meshtastic.local'],
    visible: hasNetworkNodeAddress,
  },
  {
    id: 'connection.radio.tcpAddress',
    slot: 'Connection',
    labelKey: 'connectionPanel.deviceAddress',
    sectionKey: RADIO,
    keywords: ['tcp', 'ip', 'host', '4403'],
    visible: hasNetworkNodeAddress,
  },
  {
    id: 'connection.radio.meshcoreHost',
    slot: 'Connection',
    labelKey: 'connectionPanel.meshcoreHost',
    sectionKey: RADIO,
    keywords: ['tcp', 'wifi', 'ip', 'address'],
    visible: hasCompanionTcpHost,
  },
  {
    id: 'connection.radio.meshcorePort',
    slot: 'Connection',
    labelKey: 'connectionPanel.meshcorePort',
    sectionKey: RADIO,
    keywords: ['tcp', 'port'],
    visible: hasCompanionTcpHost,
  },
  {
    id: 'connection.radio.connect',
    slot: 'Connection',
    labelKey: 'connectionPanel.connectButton',
    sectionKey: RADIO,
    keywords: ['connect radio', 'pair', 'device'],
  },
  {
    id: 'connection.lastConnection.reconnect',
    slot: 'Connection',
    labelKey: 'connectionPanel.reconnect',
    sectionKey: LAST,
    keywords: ['last device', 'reconnect', 'recent'],
  },
  {
    id: 'connection.lastConnection.forget',
    slot: 'Connection',
    labelKey: 'connectionPanel.forgetDevice',
    sectionKey: LAST,
    keywords: ['last device', 'remove', 'clear'],
  },
  {
    id: 'connection.mqtt.meshtasticPreset',
    slot: 'Connection',
    labelKey: 'connectionPanel.networkPreset',
    sectionKey: MQTT,
    keywords: ['mqtt', 'broker', 'profile', 'official', 'liam', 'server'],
    visible: hasMeshtasticMqtt,
  },
  {
    id: 'connection.mqtt.meshcorePreset',
    slot: 'Connection',
    labelKey: 'connectionPanel.networkPreset',
    sectionKey: MQTT,
    keywords: ['mqtt', 'broker', 'letsmesh', 'meshmapper', 'ripple', 'colorado'],
    visible: hasMeshcoreMqtt,
  },
  {
    id: 'connection.mqtt.switchProfile',
    slot: 'Connection',
    labelKey: 'mqttProfiles.switchLabel',
    sectionKey: MQTT,
    keywords: ['mqtt', 'profile', 'switch'],
    visible: hasMeshtasticMqtt,
  },
  {
    id: 'connection.mqtt.meshcoreCaBroker',
    slot: 'Connection',
    labelKey: 'connectionPanel.meshcoreCaBroker',
    sectionKey: MQTT,
    keywords: ['mqtt', 'broker', 'primary', 'backup', 'canada'],
    visible: hasMeshcoreMqtt,
  },
  {
    id: 'connection.mqtt.letsMeshRegion',
    slot: 'Connection',
    labelKey: 'connectionPanel.letsMeshRegion',
    sectionKey: MQTT,
    keywords: ['mqtt', 'region', 'us', 'eu', 'europe'],
    visible: hasMeshcoreMqtt,
  },
  {
    id: 'connection.mqtt.server',
    slot: 'Connection',
    labelKey: 'connectionPanel.server',
    sectionKey: MQTT,
    keywords: ['mqtt', 'broker', 'host'],
    visible: hasMqtt,
  },
  {
    id: 'connection.mqtt.port',
    slot: 'Connection',
    labelKey: 'connectionPanel.port',
    sectionKey: MQTT,
    keywords: ['mqtt', '1883', '8883'],
    visible: hasMqtt,
  },
  {
    id: 'connection.mqtt.tls',
    slot: 'Connection',
    labelKey: 'connectionPanel.mqttTlsEnabled',
    sectionKey: MQTT,
    keywords: ['mqtt', 'ssl', 'encryption', 'secure'],
    visible: hasMqtt,
  },
  {
    id: 'connection.mqtt.tlsInsecure',
    slot: 'Connection',
    labelKey: 'connectionPanel.mqttTlsInsecure',
    sectionKey: MQTT,
    keywords: ['mqtt', 'self-signed', 'certificate', 'ssl'],
    visible: hasMqtt,
  },
  {
    id: 'connection.mqtt.webSocket',
    slot: 'Connection',
    labelKey: 'connectionPanel.useWebSocket',
    sectionKey: MQTT,
    keywords: ['mqtt', 'ws', 'wss', 'websocket'],
    visible: hasMqtt,
  },
  {
    id: 'connection.mqtt.meshcorePacketLogger',
    slot: 'Connection',
    labelKey: 'connectionPanel.meshcorePacketLogger.label',
    sectionKey: MQTT,
    keywords: ['mqtt', 'packet logger', 'analyzer', 'meshcoretomqtt'],
    visible: hasMeshcoreMqtt,
  },
  {
    id: 'connection.mqtt.username',
    slot: 'Connection',
    labelKey: 'connectionPanel.username',
    sectionKey: MQTT,
    keywords: ['mqtt', 'login', 'credentials', 'user'],
    visible: hasMqtt,
  },
  {
    id: 'connection.mqtt.password',
    slot: 'Connection',
    labelKey: 'connectionPanel.password',
    sectionKey: MQTT,
    keywords: ['mqtt', 'login', 'credentials'],
    visible: hasMqtt,
  },
  {
    id: 'connection.mqtt.topicPrefix',
    slot: 'Connection',
    labelKey: 'connectionPanel.topicPrefix',
    sectionKey: MQTT,
    keywords: ['mqtt', 'topic', 'root', 'msh', 'iata'],
    visible: hasMqtt,
  },
  {
    id: 'connection.mqtt.maxRetries',
    slot: 'Connection',
    labelKey: 'connectionPanel.maxRetries',
    sectionKey: MQTT,
    keywords: ['mqtt', 'reconnect', 'attempts', 'retry'],
    visible: hasMqtt,
  },
  {
    id: 'connection.mqtt.channelPsks',
    slot: 'Connection',
    labelKey: 'connectionPanel.channelPsks',
    sectionKey: MQTT,
    keywords: ['mqtt', 'psk', 'key', 'encryption', 'decrypt', 'channel'],
    visible: hasMeshtasticMqtt,
  },
  {
    id: 'connection.mqtt.autoConnect',
    slot: 'Connection',
    labelKey: 'connectionPanel.autoConnect',
    sectionKey: MQTT,
    keywords: ['mqtt', 'auto launch', 'startup'],
    visible: hasMqtt,
  },
  {
    id: 'connection.mqtt.connect',
    slot: 'Connection',
    labelKey: 'connectionPanel.connectMqtt',
    sectionKey: MQTT,
    keywords: ['mqtt', 'connect broker'],
    visible: hasMqtt,
  },
  {
    id: 'connection.mqtt.disconnect',
    slot: 'Connection',
    labelKey: 'connectionPanel.disconnectMqtt',
    sectionKey: MQTT,
    keywords: ['mqtt', 'disconnect broker'],
    visible: hasMqtt,
  },
];

export const connectionSurface: SettingsSearchSurface = {
  entries: connectionEntries,
  files: [{ path: 'src/renderer/components/ConnectionPanel.tsx', sweepAllKeys: true }],
  exempt: {
    'connectionPanel.*Hint': 'help text under a control; the control is indexed',
    'connectionPanel.*Placeholder': 'placeholder of an indexed field',
    'connectionPanel.*Warning': 'warning text, not a control',
    'connectionPanel.*Failed': 'error message, not a control',
    'connectionPanel.*Password': 'show/hide toggle of the indexed password field',
    'connectionPanel.*PresetConfirm': 'confirmation prompt of the indexed network preset',
    'connectionPanel.*ServerNote': 'note under the indexed network preset',
    'connectionPanel.error.*': 'connection error messages, not controls',
    'connectionPanel.hint*': 'per-transport connection tips, not controls',
    'connectionPanel.stage*': 'connection progress status text',
    'connectionPanel.tiles.*': 'read-only status tiles',
    'connectionPanel.picker*': 'accessible names of devices in the connect-time picker',
    'connectionPanel.scanning*': 'connect-time device picker status',
    'connectionPanel.select*': 'connect-time device picker heading',
    'connectionPanel.autoConnecting*': 'auto-connect progress status text',
    'connectionPanel.autoReconnectInProgress': 'reconnect status banner',
    'connectionPanel.connecting': 'connection progress status text',
    'connectionPanel.stayOnTab': 'connection progress note',
    'connectionPanel.devicesFound': 'device picker count',
    'connectionPanel.noSerialPorts': 'device picker empty state',
    'connectionPanel.bleRssiDbm': 'signal strength readout in the device picker',
    'connectionPanel.enterPin': 'BLE pairing PIN prompt shown only during pairing',
    'connectionPanel.pinPlaceholder': 'BLE pairing PIN prompt shown only during pairing',
    'connectionPanel.pairWithDevice': 'BLE pairing PIN prompt heading',
    'connectionPanel.submit': 'BLE pairing PIN submit button',
    'connectionPanel.rePairDevice': 'pairing recovery button shown only after a BLE error',
    'connectionPanel.bluetoothDevice': 'device name fallback in the indexed last-connection card',
    'connectionPanel.serialDevice': 'device name fallback in the indexed last-connection card',
    'connectionPanel.wifiDevice': 'device name fallback in the indexed last-connection card',
    'connectionPanel.battery': 'read-only connected-radio value',
    'connectionPanel.firmware': 'read-only connected-radio value',
    'connectionPanel.lastData': 'read-only connected-radio value',
    'connectionPanel.myNode': 'read-only connected-radio value',
    'connectionPanel.from': 'read-only connected-MQTT value',
    'connectionPanel.topic': 'read-only connected-MQTT value; the topic prefix field is indexed',
    'connectionPanel.disconnect*':
      'connected-view radio disconnect split button (an action shown only while connected); the MQTT disconnect is indexed',
    'connectionPanel.moreDisconnectOptions': 'menu trigger of the radio disconnect split button',
    'connectionPanel.manualContactApproval*':
      'only rendered when onToggleManualContacts is passed, which App does not do',
    'connectionPanel.maxReconnectAttempts':
      'connected-view variant of the indexed MQTT max retries stepper',
    'connectionPanel.maxRetriesHelp*': 'help text for the indexed MQTT max retries',
    'connectionPanel.cancelMqttConnect': 'cancel button shown only while MQTT is connecting',
    'connectionPanel.channelPsks*':
      'help, placeholder and validation text of the indexed channel PSKs field',
    'connectionPanel.topicPrefix*': 'help and validation text of the indexed topic prefix field',
    'connectionPanel.coloradoRegionGate*': 'one-time Colorado region confirmation dialog',
    'connectionPanel.broker': 'visible caption of the indexed MeshCore.CA broker group',
    'connectionPanel.region': 'visible caption of the indexed LetsMesh region group',
    'connectionPanel.meshcoreCa*': 'option buttons of the indexed MeshCore.CA broker group',
    'connectionPanel.letsMeshRegion*': 'option buttons of the indexed LetsMesh region group',
    'connectionPanel.meshcorePreset.*': 'option values of the indexed MeshCore network preset',
    'connectionPanel.meshcorePresetDeviation.*': 'warning when settings drift from the preset',
    'connectionPanel.meshtasticPreset.*': 'option values of the indexed Meshtastic network preset',
    'connectionPanel.meshcoreMqttIdentity.*': 'MQTT signing identity status and errors',
    'connectionPanel.wsRequired': 'suffix note on the indexed WebSocket toggle',
    'connectionPanel.windowsMdnsNote': 'Windows note under the indexed device address',
    'mqttProfiles.noneSelected': 'option label of the indexed saved-profile select',
    'mqttProfiles.optionLabel': 'option label of the indexed network preset select',
    'mqttProfiles.reconnectNeeded': 'status text after switching profiles',
    'diagnosticsPanel.docsLink': 'external troubleshooting docs link',
  },
};
