import type {
  SettingSearchEntry,
  SettingsSearchContext,
  SettingsSearchSurface,
} from '../settingsSearch';

// DiagnosticsPanel renders its LoRa settings card only for hop-count protocols, MQTT rows only
// with MQTT hybrid, and the ping card only with Reticulum-native diagnostics.
const hasLoRaDiagnostics = (ctx: SettingsSearchContext) => ctx.capabilities.hasHopCount;
const hasLoRaMqttControls = (ctx: SettingsSearchContext) =>
  ctx.capabilities.hasHopCount && ctx.capabilities.hasMqttHybrid;
const hasPing = (ctx: SettingsSearchContext) => ctx.capabilities.hasReticulumNativeDiagnostics;

const DISPLAY = 'diagnosticsPanel.displaySettings';
const PING = 'diagnosticsPing.title';

const diagnosticsEntries: readonly SettingSearchEntry[] = [
  {
    id: 'diagnostics.export.json',
    slot: 'Diagnostics',
    labelKey: 'diagnosticsPanel.exportJson',
    sectionKey: 'diagnosticsPanel.networkDiagnosticsTitle',
    keywords: ['export', 'download', 'json', 'report'],
  },
  {
    id: 'diagnostics.ping.destination',
    slot: 'Diagnostics',
    labelKey: 'diagnosticsPing.hashLabel',
    sectionKey: PING,
    keywords: ['ping', 'rtt', 'latency', 'destination hash', 'probe'],
    visible: hasPing,
  },
  {
    id: 'diagnostics.ping.interval',
    slot: 'Diagnostics',
    labelKey: 'diagnosticsPing.intervalLabel',
    sectionKey: PING,
    keywords: ['ping', 'interval', 'seconds'],
    visible: hasPing,
  },
  {
    id: 'diagnostics.ping.runOnce',
    slot: 'Diagnostics',
    labelKey: 'diagnosticsPing.runOnce',
    sectionKey: PING,
    keywords: ['ping', 'single', 'probe'],
    visible: hasPing,
  },
  {
    id: 'diagnostics.display.congestionHalos',
    slot: 'Diagnostics',
    labelKey: 'diagnosticsPanel.showChannelUtilHalos',
    sectionKey: DISPLAY,
    keywords: ['halo', 'map', 'channel utilization', 'congestion'],
    visible: hasLoRaDiagnostics,
  },
  {
    id: 'diagnostics.display.anomalyHalos',
    slot: 'Diagnostics',
    labelKey: 'diagnosticsPanel.showRoutingAnomalyHalos',
    sectionKey: DISPLAY,
    keywords: ['halo', 'map', 'anomaly', 'hop goblin'],
    visible: hasLoRaDiagnostics,
  },
  {
    id: 'diagnostics.display.ignoreMqtt',
    slot: 'Diagnostics',
    labelKey: 'diagnosticsPanel.ignoreMqttToggle',
    sectionKey: DISPLAY,
    keywords: ['mqtt', 'filter', 'exclude'],
    visible: hasLoRaMqttControls,
  },
  {
    id: 'diagnostics.display.autoTraceroute',
    slot: 'Diagnostics',
    labelKey: 'diagnosticsPanel.autoTraceroute',
    sectionKey: DISPLAY,
    keywords: ['traceroute', 'discovery', 'automatic', 'route'],
    visible: hasLoRaDiagnostics,
  },
  {
    id: 'diagnostics.display.environmentProfile',
    slot: 'Diagnostics',
    labelKey: 'diagnosticsPanel.environmentProfile',
    sectionKey: DISPLAY,
    keywords: ['city', 'canyon', 'terrain', 'urban'],
    visible: hasLoRaDiagnostics,
  },
  {
    id: 'diagnostics.display.distanceOffset',
    slot: 'Diagnostics',
    labelKey: 'diagnosticsPanel.distanceOffsetKm',
    sectionKey: DISPLAY,
    keywords: ['distance', 'km', 'tolerance', 'range'],
    visible: hasLoRaDiagnostics,
  },
  {
    id: 'diagnostics.display.staleRowsMaxAge',
    slot: 'Diagnostics',
    labelKey: 'diagnosticsPanel.staleRoutingDiagnostics',
    sectionKey: DISPLAY,
    keywords: ['stale', 'age', 'hours', 'expire', 'prune'],
    visible: hasLoRaDiagnostics,
  },
  {
    id: 'diagnostics.mqttFilters.perNode',
    slot: 'Diagnostics',
    labelKey: 'diagnosticsPanel.perNodeMqttFilters',
    keywords: ['mqtt', 'ignored nodes', 'filter'],
    visible: hasLoRaMqttControls,
  },
  {
    id: 'diagnostics.anomalies.search',
    slot: 'Diagnostics',
    labelKey: 'diagnosticsPanel.searchAnomalies',
    keywords: ['filter', 'search', 'anomalies', 'find node'],
    visible: hasLoRaDiagnostics,
  },
];

export const diagnosticsSurface: SettingsSearchSurface = {
  entries: diagnosticsEntries,
  files: [
    { path: 'src/renderer/components/DiagnosticsPanel.tsx', sweepAllKeys: true },
    { path: 'src/renderer/components/DiagnosticsPingPanel.tsx', sweepAllKeys: true },
  ],
  exempt: {
    'diagnosticsPanel.*Help': 'help text beside an indexed control',
    'diagnosticsPanel.*Hint': 'help text or tooltip beside an indexed control or action',
    'diagnosticsPanel.environmentStandard': 'option of the indexed environment profile',
    'diagnosticsPanel.environmentCity': 'option of the indexed environment profile',
    'diagnosticsPanel.environmentCanyon': 'option of the indexed environment profile',
    'diagnosticsPanel.km': 'unit beside the indexed distance offset',
    'diagnosticsPanel.hoursRange': 'unit beside the indexed stale-row age',
    'diagnosticsPanel.dropRoutingRows*':
      'field label and accessible name of the indexed stale-row age',
    'diagnosticsPanel.exportJsonAria': 'accessible name of the indexed export button',
    'diagnosticsPanel.docsLink': 'external documentation link',
    'diagnosticsPanel.reticulum.sectionTitle': 'heading of the Reticulum findings list, no control',
    'diagnosticsPanel.restoredSessionBanner': 'transient restored-session banner text',
    'diagnosticsPanel.stopRestoringOnLaunch':
      'one-shot action in the transient restored-session banner',
    'diagnosticsPanel.meshHealth*': 'mesh health status text',
    'diagnosticsPanel.networkHealthLabel': 'mesh health status label',
    'diagnosticsPanel.nodesWithTelemetry': 'mesh health count text',
    'diagnosticsPanel.errorCount': 'mesh health count text',
    'diagnosticsPanel.warningCount': 'mesh health count text',
    'diagnosticsPanel.noIssues': 'mesh health status text',
    'diagnosticsPanel.thisNodePrefix': 'mesh health status text',
    'diagnosticsPanel.heuristicNotesTooltip': 'mesh health tooltip',
    'diagnosticsPanel.cuHistory*': 'channel utilization chart heading and tooltip',
    'diagnosticsPanel.severity*': 'finding-table severity group headers',
    'diagnosticsPanel.table*': 'finding-table column headers',
    'diagnosticsPanel.*Heading': 'heading over a list of diagnostic findings',
    'diagnosticsPanel.*Column': 'finding or foreign-LoRa table column header',
    'diagnosticsPanel.*Description': 'prose over a list of diagnostic findings',
    'diagnosticsPanel.meshcoreRepeaterConflictBanner': 'diagnostic finding banner, not a control',
    'diagnosticsPanel.meshcoreUnknown*': 'fallback node name in a finding row',
    'diagnosticsPanel.meshcoreHeard*': 'fallback node name in a foreign-LoRa row',
    'diagnosticsPanel.selfNodeFallback': 'fallback node name in a trace route',
    'diagnosticsPanel.proximity*': 'proximity value in a foreign-LoRa row',
    'diagnosticsPanel.foreignClass*': 'packet class value in a foreign-LoRa row',
    'diagnosticsPanel.senderLabel': 'field label in a foreign-LoRa row',
    'diagnosticsPanel.rssi*': 'signal value in a foreign-LoRa row',
    'diagnosticsPanel.snrDb': 'signal value in a foreign-LoRa row',
    'diagnosticsPanel.lastHopBadge': 'badge on a finding row',
    'diagnosticsPanel.hybridNodeMqttWarning': 'warning text on a finding row',
    'diagnosticsPanel.rfTraceNotAvailable': 'status text on an RF finding row',
    'diagnosticsPanel.tracing': 'per-row trace route busy status',
    'diagnosticsPanel.traceRoute': 'per-row trace route action on a finding, not a setting',
    'diagnosticsPanel.retryTrace': 'per-row trace route action on a finding, not a setting',
    'diagnosticsPanel.reTrace': 'per-row trace route action on a finding, not a setting',
    'diagnosticsPanel.ignoreMqttButton': 'per-row MQTT ignore action on a finding',
    'diagnosticsPanel.mqttIgnoredToggle': 'per-row MQTT ignore action on a finding',
    'diagnosticsPanel.excludeMqttData': 'tooltip of a per-row MQTT ignore action',
    'diagnosticsPanel.stopIgnoringMqtt': 'tooltip of a per-row MQTT ignore action',
    'diagnosticsPanel.dismissRow': 'remove chip inside the indexed per-node MQTT filters',
    'diagnosticsPanel.removeMqttFilter': 'remove chip inside the indexed per-node MQTT filters',
    'diagnosticsPanel.noAnomaliesMatchSearch': 'empty state of the indexed anomaly search',
    'diagnosticsPanel.noDiagnosticsHealthy': 'empty state of the findings list',
    'diagnosticsPanel.scopeSubtitle': 'subtitle of the congestion attribution block',
    'meshCongestion.routingAnomalies': 'routing stress banner, not a control',
    'diagnosticsPing.reticulumHint': 'help text under the indexed ping card',
    'diagnosticsPing.hashPlaceholder': 'placeholder of the indexed destination hash',
    'diagnosticsPing.hashAria': 'accessible name of the indexed destination hash',
    'diagnosticsPing.intervalAria': 'accessible name of the indexed ping interval',
    'diagnosticsPing.start': 'start button of the indexed ping card',
    'diagnosticsPing.stop': 'stop button of the indexed ping card',
    'diagnosticsPing.col*': 'ping result table column headers',
    'diagnosticsPing.rttMs': 'ping result value',
    'diagnosticsPing.status*': 'ping result status text',
  },
};
