import type {
  SettingSearchEntry,
  SettingsSearchContext,
  SettingsSearchSurface,
} from '../settingsSearch';

// App.tsx renders ModulePanel in the Modules slot only when the slot is not the Repeaters list.
const hasModulePanel = (ctx: SettingsSearchContext) =>
  !ctx.capabilities.modulesTabUsesRepeatersLabel;

const MODULES = 'modulePanel.title';

const modulesEntries: readonly SettingSearchEntry[] = [
  {
    id: 'modules.mqttRelay',
    slot: 'Modules',
    labelKey: 'modulePanel.sectionMqttRelay',
    sectionKey: MODULES,
    keywords: ['mqtt', 'broker', 'uplink', 'downlink', 'username', 'password', 'json'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.mqttRelay.proxyToClient',
    slot: 'Modules',
    labelKey: 'modulePanel.fields.mqttProxyToClientEnabled',
    sectionKey: 'modulePanel.sectionMqttRelay',
    keywords: ['mqtt', 'proxy', 'client', 'gateway'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.mqttRelay.serverAddress',
    slot: 'Modules',
    labelKey: 'modulePanel.fields.serverAddress',
    sectionKey: 'modulePanel.sectionMqttRelay',
    keywords: ['mqtt', 'broker', 'host', 'server'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.mqttRelay.rootTopic',
    slot: 'Modules',
    labelKey: 'modulePanel.fields.rootTopic',
    sectionKey: 'modulePanel.sectionMqttRelay',
    keywords: ['mqtt', 'topic', 'msh'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.mqttRelay.encryption',
    slot: 'Modules',
    labelKey: 'modulePanel.fields.encryptionEnabled',
    sectionKey: 'modulePanel.sectionMqttRelay',
    keywords: ['mqtt', 'encrypt', 'psk'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.mqttRelay.tls',
    slot: 'Modules',
    labelKey: 'modulePanel.fields.tlsEnabled',
    sectionKey: 'modulePanel.sectionMqttRelay',
    keywords: ['mqtt', 'ssl', 'tls', 'secure'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.mapReport',
    slot: 'Modules',
    labelKey: 'modulePanel.sectionMapReport',
    sectionKey: MODULES,
    keywords: ['map', 'mqtt', 'position', 'publish', 'precision'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.serial',
    slot: 'Modules',
    labelKey: 'modulePanel.sectionSerialModule',
    sectionKey: MODULES,
    keywords: ['serial', 'uart', 'rxd', 'txd', 'nmea', 'echo', 'console'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.serial.baudRate',
    slot: 'Modules',
    labelKey: 'modulePanel.fields.baudRate',
    sectionKey: 'modulePanel.sectionSerialModule',
    keywords: ['baud', 'serial', 'speed'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.serial.mode',
    slot: 'Modules',
    labelKey: 'modulePanel.fields.serialMode',
    sectionKey: 'modulePanel.sectionSerialModule',
    keywords: ['serial', 'textmsg', 'protobuf', 'nmea'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.externalNotification',
    slot: 'Modules',
    labelKey: 'modulePanel.sectionExternalNotification',
    sectionKey: MODULES,
    keywords: ['buzzer', 'vibration', 'led', 'gpio', 'bell', 'alert', 'pwm'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.storeForward',
    slot: 'Modules',
    labelKey: 'modulePanel.sectionStoreForward',
    sectionKey: MODULES,
    keywords: ['store and forward', 's&f', 'history', 'heartbeat', 'records'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.rangeTest',
    slot: 'Modules',
    labelKey: 'modulePanel.sectionRangeTest',
    sectionKey: MODULES,
    keywords: ['range', 'sender', 'csv', 'coverage'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.telemetry',
    slot: 'Modules',
    labelKey: 'modulePanel.sectionTelemetryModule',
    sectionKey: MODULES,
    keywords: ['telemetry', 'device metrics', 'air quality', 'power', 'sensor', 'interval'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.telemetry.deviceInterval',
    slot: 'Modules',
    labelKey: 'modulePanel.fields.telDeviceInterval',
    sectionKey: 'modulePanel.sectionTelemetryModule',
    keywords: ['battery', 'device metrics', 'interval', 'telemetry'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.telemetry.environment',
    slot: 'Modules',
    labelKey: 'modulePanel.fields.telEnvEnabled',
    sectionKey: 'modulePanel.sectionTelemetryModule',
    keywords: ['temperature', 'humidity', 'pressure', 'bme280', 'environment'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.cannedMessages',
    slot: 'Modules',
    labelKey: 'modulePanel.sectionCannedMessages',
    sectionKey: MODULES,
    keywords: ['canned', 'quick reply', 'rotary', 'encoder', 'up down'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.cannedMessages.messages',
    slot: 'Modules',
    labelKey: 'modulePanel.fields.messagesOnePerLine',
    sectionKey: 'modulePanel.sectionCannedMessages',
    keywords: ['canned', 'presets', 'quick reply', 'templates'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.neighborInfo',
    slot: 'Modules',
    labelKey: 'modulePanel.sectionNeighborInfo',
    sectionKey: MODULES,
    keywords: ['neighbors', 'topology', 'interval'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.ambientLighting',
    slot: 'Modules',
    labelKey: 'modulePanel.sectionAmbientLighting',
    sectionKey: MODULES,
    keywords: ['led', 'rgb', 'color', 'brightness'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.detectionSensor',
    slot: 'Modules',
    labelKey: 'modulePanel.sectionDetectionSensor',
    sectionKey: MODULES,
    keywords: ['gpio', 'motion', 'pir', 'door', 'sensor'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.paxCounter',
    slot: 'Modules',
    labelKey: 'modulePanel.sectionPaxCounter',
    sectionKey: MODULES,
    keywords: ['pax', 'people', 'wifi', 'ble', 'count'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.remoteHardware',
    slot: 'Modules',
    labelKey: 'modulePanel.sectionRemoteHardware',
    sectionKey: MODULES,
    keywords: ['gpio', 'pins', 'remote'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.trafficManagement',
    slot: 'Modules',
    labelKey: 'modulePanel.sectionTrafficManagement',
    sectionKey: MODULES,
    keywords: ['traffic', 'dedup', 'hops', 'nodeinfo', 'drop unknown'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.trafficManagement.rateLimit',
    slot: 'Modules',
    labelKey: 'modulePanel.fields.tmRateLimitEnabled',
    sectionKey: 'modulePanel.sectionTrafficManagement',
    keywords: ['rate limit', 'throttle', 'flood', 'packets'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.tak',
    slot: 'Modules',
    labelKey: 'modulePanel.sectionTak',
    sectionKey: MODULES,
    keywords: ['tak', 'atak', 'team', 'role', 'cot'],
    visible: hasModulePanel,
  },
  {
    id: 'modules.rtttlRingtone',
    slot: 'Modules',
    labelKey: 'modulePanel.sectionRtttlRingtone',
    sectionKey: MODULES,
    keywords: ['ringtone', 'rtttl', 'melody', 'sound', 'buzzer'],
    visible: hasModulePanel,
  },
];

export const modulesSurface: SettingsSearchSurface = {
  entries: modulesEntries,
  files: [{ path: 'src/renderer/components/ModulePanel.tsx', sweepAllKeys: true }],
  exempt: {
    'modulePanel.fields.*':
      'row inside an indexed module section (the jump opens the section); key rows are indexed',
    'modulePanel.apply*': 'Apply button of an indexed module section',
    'modulePanel.status*': 'read-only module packet status',
    'modulePanel.debug*': 'read-only packet counters in the status-only Debug Modules section',
    'modulePanel.remoteHardwareConfirm*':
      'confirmation dialog copy for the remote hardware toggles',
    'modulePanel.telemetryDeviceMetrics*': 'help text for the indexed device metrics interval',
    'modulePanel.*Hint': 'help text under a section; the section is indexed',
    'modulePanel.*Failed': 'error toast, not a control',
    'modulePanel.failed': 'error toast, not a control',
    'modulePanel.sectionSent': 'success toast, not a control',
    'modulePanel.cannedMessagesApplied': 'success toast, not a control',
    'modulePanel.rtttlSaved': 'success toast, not a control',
    'modulePanel.connectToDevice': 'disconnected banner, not a control',
    'modulePanel.waitingForModuleConfig': 'loading banner, not a control',
    'modulePanel.ambientColors.rgbComponents': 'read-only RGB readout of the ambient color',
    'modulePanel.selectPreset': 'placeholder option of the ringtone preset picker',
    'modulePanel.sectionAudio': 'status-only section with no settings',
    'modulePanel.sectionDebugModules': 'status-only section with no settings',
    'modulePanel.sectionIpTunnel': 'status-only section with no settings',
    'configureNode.loading': 'remote config loading text, not a control',
    'radioPanel.secondsUnit': 'unit label beside a number field',
    'radioPanel.waitingForConfigSection': 'loading hint inside a module section',
  },
};
