import type {
  SettingSearchEntry,
  SettingsSearchContext,
  SettingsSearchSurface,
} from '../settingsSearch';

// The Radio slot renders ReticulumNetworkPanel instead of RadioPanel when this flag is set.
const showsRadioPanel = (ctx: SettingsSearchContext) => !ctx.capabilities.hasReticulumNetworkPanel;
// RadioPanel picks its MeshCore vs Meshtastic blocks by the companion contact-management props.
const isCompanion = (ctx: SettingsSearchContext) =>
  ctx.capabilities.hasCompanionContactManagementConfig;
const hasMeshtasticLora = (ctx: SettingsSearchContext) => showsRadioPanel(ctx) && !isCompanion(ctx);
const hasChannelConfig = (ctx: SettingsSearchContext) => ctx.capabilities.hasChannelConfig;
const hasDeviceRole = (ctx: SettingsSearchContext) => ctx.capabilities.hasDeviceRoleConfig;
const hasFullPosition = (ctx: SettingsSearchContext) => ctx.capabilities.hasFullPositionConfig;
const hasPower = (ctx: SettingsSearchContext) => ctx.capabilities.hasPowerConfig;
const hasWifi = (ctx: SettingsSearchContext) => ctx.capabilities.hasWifiConfig;
const hasDisplay = (ctx: SettingsSearchContext) => ctx.capabilities.hasDisplayConfig;
const hasBluetooth = (ctx: SettingsSearchContext) => ctx.capabilities.hasBluetoothConfig;
const hasTelemetryPrivacy = (ctx: SettingsSearchContext) =>
  ctx.capabilities.hasCompanionTelemetryPrivacyConfig;

const USER = 'radioPanel.sectionDeviceUser';
const LORA = 'radioPanel.sectionLora';
const CHANNEL_URL = 'radioPanel.channelUrl.sectionTitle';
const DEVICE = 'radioPanel.sectionDeviceRole';
const POSITION = 'radioPanel.sectionPositionGps';
const POWER = 'radioPanel.sectionPower';
const WIFI = 'radioPanel.sectionWifi';
const DISPLAY = 'radioPanel.sectionDisplay';
const BLUETOOTH = 'radioPanel.sectionBluetooth';
const ACTIONS = 'radioPanel.deviceActions';
const CONTACTS = 'meshcoreContactSettings.contactManagement';
const CONTACTS_APP = 'meshcoreContactSettings.contactsListAppHeading';
const TELEMETRY_PRIVACY = 'meshcoreTelemetryPrivacy.summary';

const radioEntries: readonly SettingSearchEntry[] = [
  {
    id: 'radio.config.importJson',
    slot: 'Radio',
    labelKey: 'radioPanel.importConfigJson',
    keywords: ['import', 'json', 'config', 'backup', 'restore'],
    visible: (ctx) => showsRadioPanel(ctx) && ctx.capabilities.hasJsonRadioConfigImport,
  },
  {
    id: 'radio.lockdown.passphrase',
    slot: 'Radio',
    labelKey: 'radioPanel.lockdown.title',
    keywords: ['lockdown', 'passphrase', 'unlock', 'lock', 'security'],
    visible: (ctx) => ctx.capabilities.hasLockdown,
  },

  // Device user / identity
  {
    id: 'radio.user.section',
    slot: 'Radio',
    labelKey: USER,
    keywords: ['owner', 'identity', 'name'],
    visible: showsRadioPanel,
  },
  {
    id: 'radio.user.longName',
    slot: 'Radio',
    labelKey: 'radioPanel.longNameFieldLabel',
    sectionKey: USER,
    keywords: ['name', 'owner', 'node name'],
    visible: hasMeshtasticLora,
  },
  {
    id: 'radio.user.meshcoreName',
    slot: 'Radio',
    labelKey: 'radioPanel.meshcoreNameFieldLabel',
    sectionKey: USER,
    keywords: ['name', 'owner', 'node name', 'advert name'],
    visible: isCompanion,
  },
  {
    id: 'radio.user.shortName',
    slot: 'Radio',
    labelKey: 'radioPanel.shortNameFieldLabel',
    sectionKey: USER,
    keywords: ['name', 'initials', 'short'],
    visible: hasChannelConfig,
  },
  {
    id: 'radio.user.licensedHam',
    slot: 'Radio',
    labelKey: 'radioPanel.licensedHamLabel',
    sectionKey: USER,
    keywords: ['ham', 'amateur', 'licensed', 'callsign', 'unencrypted'],
    visible: hasChannelConfig,
  },

  // LoRa (MeshCore)
  {
    id: 'radio.lora.meshcoreSection',
    slot: 'Radio',
    labelKey: LORA,
    keywords: ['lora', 'radio', 'frequency', 'modem'],
    visible: isCompanion,
  },
  {
    id: 'radio.lora.frequency',
    slot: 'Radio',
    labelKey: 'radioPanel.frequencyMhzLabel',
    sectionKey: LORA,
    keywords: ['frequency', 'mhz', 'band'],
    visible: isCompanion,
  },
  {
    id: 'radio.lora.meshcoreBandwidth',
    slot: 'Radio',
    labelKey: 'radioPanel.bandwidthLabel',
    sectionKey: LORA,
    keywords: ['bw', 'khz', 'lora'],
    visible: isCompanion,
  },
  {
    id: 'radio.lora.meshcoreSpreadFactor',
    slot: 'Radio',
    labelKey: 'radioPanel.spreadFactorLabel',
    sectionKey: LORA,
    keywords: ['sf', 'spreading factor', 'lora'],
    visible: isCompanion,
  },
  {
    id: 'radio.lora.meshcoreCodingRate',
    slot: 'Radio',
    labelKey: 'radioPanel.codingRateLabel',
    sectionKey: LORA,
    keywords: ['cr', 'coding rate', 'lora'],
    visible: isCompanion,
  },
  {
    id: 'radio.txPower.meshcoreTxPower',
    slot: 'Radio',
    labelKey: 'radioPanel.txPowerLabel',
    sectionKey: 'radioPanel.sectionTxPower',
    keywords: ['tx power', 'dbm', 'transmit', 'power'],
    visible: isCompanion,
  },
  {
    id: 'radio.floodScope.section',
    slot: 'Radio',
    labelKey: 'radioPanel.floodScopeTitle',
    keywords: ['flood', 'scope', 'region', 'hashtag'],
    visible: (ctx) => isCompanion(ctx) && ctx.capabilities.hasContactImportExport,
  },

  // LoRa (Meshtastic)
  {
    id: 'radio.lora.section',
    slot: 'Radio',
    labelKey: LORA,
    keywords: ['lora', 'radio', 'modem'],
    visible: hasMeshtasticLora,
  },
  {
    id: 'radio.lora.region',
    slot: 'Radio',
    labelKey: 'radioPanel.regionLabel',
    sectionKey: LORA,
    keywords: ['region', 'country', 'us', 'eu', 'band', 'frequency'],
    visible: hasMeshtasticLora,
  },
  {
    id: 'radio.lora.usePreset',
    slot: 'Radio',
    labelKey: 'radioPanel.useModemPresetLabel',
    sectionKey: LORA,
    keywords: ['preset', 'modem', 'custom'],
    visible: (ctx) => hasMeshtasticLora(ctx) && ctx.capabilities.hasModemPresets,
  },
  {
    id: 'radio.lora.modemPreset',
    slot: 'Radio',
    labelKey: 'radioPanel.modemPresetLabel',
    sectionKey: LORA,
    keywords: ['preset', 'long fast', 'medium', 'short', 'modem'],
    visible: (ctx) => hasMeshtasticLora(ctx) && ctx.capabilities.hasModemPresets,
  },
  {
    id: 'radio.lora.bandwidth',
    slot: 'Radio',
    labelKey: 'radioPanel.bandwidthLabel',
    sectionKey: LORA,
    keywords: ['bw', 'khz', 'custom'],
    visible: hasMeshtasticLora,
  },
  {
    id: 'radio.lora.spreadFactor',
    slot: 'Radio',
    labelKey: 'radioPanel.spreadFactorLabel',
    sectionKey: LORA,
    keywords: ['sf', 'spreading factor', 'custom'],
    visible: hasMeshtasticLora,
  },
  {
    id: 'radio.lora.codingRate',
    slot: 'Radio',
    labelKey: 'radioPanel.codingRateLabel',
    sectionKey: LORA,
    keywords: ['cr', 'coding rate', 'custom'],
    visible: hasMeshtasticLora,
  },
  {
    id: 'radio.lora.txPower',
    slot: 'Radio',
    labelKey: 'radioPanel.txPowerLabel',
    sectionKey: LORA,
    keywords: ['tx power', 'dbm', 'transmit', 'power'],
    visible: hasMeshtasticLora,
  },
  {
    id: 'radio.lora.rxBoostedGain',
    slot: 'Radio',
    labelKey: 'radioPanel.sx126xRxBoostedLabel',
    sectionKey: LORA,
    keywords: ['rx', 'gain', 'boost', 'sx126x', 'receive'],
    visible: hasMeshtasticLora,
  },
  {
    id: 'radio.lora.hopLimit',
    slot: 'Radio',
    labelKey: 'radioPanel.hopLimitLabel',
    sectionKey: LORA,
    keywords: ['hops', 'ttl', 'max hops', 'rebroadcast'],
    visible: hasMeshtasticLora,
  },
  {
    id: 'radio.lora.txEnabled',
    slot: 'Radio',
    labelKey: 'radioPanel.txEnabledLabel',
    sectionKey: LORA,
    keywords: ['transmit', 'tx', 'receive only'],
    visible: hasMeshtasticLora,
  },
  {
    id: 'radio.lora.channelNum',
    slot: 'Radio',
    labelKey: 'radioPanel.channelNumLabel',
    sectionKey: LORA,
    keywords: ['frequency slot', 'channel number'],
    visible: hasMeshtasticLora,
  },
  {
    id: 'radio.lora.overrideFrequency',
    slot: 'Radio',
    labelKey: 'radioPanel.overrideFrequencyLabel',
    sectionKey: LORA,
    keywords: ['frequency', 'mhz', 'override'],
    visible: hasMeshtasticLora,
  },
  {
    id: 'radio.lora.ignoreMqtt',
    slot: 'Radio',
    labelKey: 'radioPanel.ignoreMqttLabel',
    sectionKey: LORA,
    keywords: ['mqtt', 'ignore', 'internet'],
    visible: hasMeshtasticLora,
  },
  {
    id: 'radio.lora.okToMqtt',
    slot: 'Radio',
    labelKey: 'radioPanel.configOkToMqttLabel',
    sectionKey: LORA,
    keywords: ['mqtt', 'uplink', 'internet'],
    visible: hasMeshtasticLora,
  },
  {
    id: 'radio.lora.overrideDutyCycle',
    slot: 'Radio',
    labelKey: 'radioPanel.overrideDutyCycleLabel',
    sectionKey: LORA,
    keywords: ['duty cycle', 'eu', 'airtime'],
    visible: hasMeshtasticLora,
  },
  {
    id: 'radio.lora.paFanDisabled',
    slot: 'Radio',
    labelKey: 'radioPanel.paFanDisabledLabel',
    sectionKey: LORA,
    keywords: ['fan', 'amplifier', 'pa'],
    visible: hasMeshtasticLora,
  },

  // Channels
  {
    id: 'radio.channels.list',
    slot: 'Radio',
    labelKey: 'radioPanel.channels',
    keywords: ['channel', 'psk', 'encryption', 'key', 'primary', 'secondary'],
    visible: hasChannelConfig,
  },
  {
    id: 'radio.channels.shareUrl',
    slot: 'Radio',
    labelKey: 'radioPanel.channelUrl.generateLink',
    sectionKey: CHANNEL_URL,
    keywords: ['share', 'qr', 'url', 'link', 'export'],
    visible: hasChannelConfig,
  },
  {
    id: 'radio.channels.importUrl',
    slot: 'Radio',
    labelKey: 'radioPanel.channelUrl.pasteUrlLabel',
    sectionKey: CHANNEL_URL,
    keywords: ['import', 'qr', 'url', 'link', 'paste'],
    visible: hasChannelConfig,
  },
  {
    id: 'radio.channels.meshcoreList',
    slot: 'Radio',
    labelKey: 'radioPanel.channelsMeshcore',
    keywords: ['channel', 'secret', 'key', 'hashtag'],
    visible: isCompanion,
  },
  {
    id: 'radio.channels.meshcoreAdd',
    slot: 'Radio',
    labelKey: 'radioPanel.meshcoreChannel.addButton',
    sectionKey: 'radioPanel.channelsMeshcore',
    keywords: ['channel', 'new', 'create', 'join'],
    visible: isCompanion,
  },
  {
    id: 'radio.xmodem.transfer',
    slot: 'Radio',
    labelKey: 'radioPanel.xmodemSection',
    keywords: ['xmodem', 'file', 'upload', 'download', 'transfer'],
    visible: (ctx) => ctx.capabilities.hasXmodem,
  },

  // MeshCore contact management
  {
    id: 'radio.contacts.management',
    slot: 'Radio',
    labelKey: CONTACTS,
    keywords: ['contacts', 'auto add', 'manual add'],
    visible: isCompanion,
  },
  {
    id: 'radio.contacts.autoAddMode',
    slot: 'Radio',
    labelKey: 'meshcoreContactSettings.autoAddModeLegend',
    sectionKey: CONTACTS,
    keywords: ['auto add', 'manual', 'adverts', 'contacts'],
    visible: isCompanion,
  },
  {
    id: 'radio.contacts.autoAddTypes',
    slot: 'Radio',
    labelKey: 'meshcoreContactSettings.autoAddTypesHeading',
    sectionKey: CONTACTS,
    keywords: ['auto add', 'repeaters', 'room servers', 'sensors', 'chat'],
    visible: isCompanion,
  },
  {
    id: 'radio.contacts.overwriteOldest',
    slot: 'Radio',
    labelKey: 'meshcoreContactSettings.overwriteOldestTitle',
    sectionKey: CONTACTS,
    keywords: ['full', 'evict', 'oldest', 'contacts'],
    visible: isCompanion,
  },
  {
    id: 'radio.contacts.maxHops',
    slot: 'Radio',
    labelKey: 'meshcoreContactSettings.maxHopsLabel',
    sectionKey: CONTACTS,
    keywords: ['hops', 'auto add', 'distance'],
    visible: isCompanion,
  },
  {
    id: 'radio.contacts.autoOffload',
    slot: 'Radio',
    labelKey: 'meshcoreContactSettings.autoOffloadWhenFullLabel',
    sectionKey: CONTACTS_APP,
    keywords: ['offload', 'full', 'capacity', 'contacts'],
    visible: isCompanion,
  },
  {
    id: 'radio.contacts.showRefresh',
    slot: 'Radio',
    labelKey: 'meshcoreContactSettings.showRefreshLabel',
    sectionKey: CONTACTS_APP,
    keywords: ['refresh', 'contacts', 'button'],
    visible: isCompanion,
  },
  {
    id: 'radio.contacts.showPublicKeys',
    slot: 'Radio',
    labelKey: 'meshcoreContactSettings.showPublicKeysLabel',
    sectionKey: CONTACTS_APP,
    keywords: ['public key', 'pubkey', 'contacts'],
    visible: isCompanion,
  },
  {
    id: 'radio.contacts.clearAll',
    slot: 'Radio',
    labelKey: 'meshcoreContactSettings.clearAllContactsButton',
    sectionKey: CONTACTS,
    keywords: ['delete', 'wipe', 'contacts', 'remove'],
    visible: isCompanion,
  },
  {
    id: 'radio.contacts.offloadContacts',
    slot: 'Radio',
    labelKey: 'radioPanel.offloadContacts',
    sectionKey: ACTIONS,
    keywords: ['offload', 'contacts', 'full', 'capacity', 'free space'],
    visible: isCompanion,
  },

  // Device role (Meshtastic)
  {
    id: 'radio.device.section',
    slot: 'Radio',
    labelKey: DEVICE,
    keywords: ['device', 'role', 'router', 'client'],
    visible: hasDeviceRole,
  },
  {
    id: 'radio.device.role',
    slot: 'Radio',
    labelKey: 'radioPanel.roleFieldLabel',
    sectionKey: DEVICE,
    keywords: ['role', 'router', 'client', 'repeater', 'client mute', 'tracker'],
    visible: hasDeviceRole,
  },
  {
    id: 'radio.device.rebroadcastMode',
    slot: 'Radio',
    labelKey: 'radioPanel.rebroadcastModeLabel',
    sectionKey: DEVICE,
    keywords: ['rebroadcast', 'relay', 'forward'],
    visible: hasDeviceRole,
  },
  {
    id: 'radio.device.nodeInfoInterval',
    slot: 'Radio',
    labelKey: 'radioPanel.nodeInfoBroadcastSecsLabel',
    sectionKey: DEVICE,
    keywords: ['node info', 'broadcast', 'interval', 'announce'],
    visible: hasDeviceRole,
  },
  {
    id: 'radio.device.doubleTap',
    slot: 'Radio',
    labelKey: 'radioPanel.doubleTapAsButtonPressLabel',
    sectionKey: DEVICE,
    keywords: ['double tap', 'button', 'accelerometer'],
    visible: hasDeviceRole,
  },
  {
    id: 'radio.device.disableTripleClick',
    slot: 'Radio',
    labelKey: 'radioPanel.disableTripleClickLabel',
    sectionKey: DEVICE,
    keywords: ['triple click', 'button', 'gps toggle'],
    visible: hasDeviceRole,
  },
  {
    id: 'radio.device.ledHeartbeat',
    slot: 'Radio',
    labelKey: 'radioPanel.ledHeartbeatDisabledLabel',
    sectionKey: DEVICE,
    keywords: ['led', 'heartbeat', 'blink', 'light'],
    visible: hasDeviceRole,
  },
  {
    id: 'radio.device.buttonGpio',
    slot: 'Radio',
    labelKey: 'radioPanel.buttonGpioLabel',
    sectionKey: DEVICE,
    keywords: ['gpio', 'pin', 'button'],
    visible: hasDeviceRole,
  },
  {
    id: 'radio.device.buzzerGpio',
    slot: 'Radio',
    labelKey: 'radioPanel.buzzerGpioLabel',
    sectionKey: DEVICE,
    keywords: ['gpio', 'pin', 'buzzer'],
    visible: hasDeviceRole,
  },
  {
    id: 'radio.device.timezone',
    slot: 'Radio',
    labelKey: 'radioPanel.tzdefLabel',
    sectionKey: DEVICE,
    keywords: ['timezone', 'tz', 'posix', 'clock'],
    visible: hasDeviceRole,
  },

  // Position / GPS
  {
    id: 'radio.position.section',
    slot: 'Radio',
    labelKey: POSITION,
    keywords: ['gps', 'position', 'location'],
    visible: showsRadioPanel,
  },
  {
    id: 'radio.position.broadcastInterval',
    slot: 'Radio',
    labelKey: 'radioPanel.positionBroadcastIntervalLabel',
    sectionKey: POSITION,
    keywords: ['position', 'broadcast', 'interval'],
    visible: hasFullPosition,
  },
  {
    id: 'radio.position.gpsUpdateInterval',
    slot: 'Radio',
    labelKey: 'radioPanel.gpsUpdateIntervalLabel',
    sectionKey: POSITION,
    keywords: ['gps', 'interval', 'fix'],
    visible: hasFullPosition,
  },
  {
    id: 'radio.position.gpsMode',
    slot: 'Radio',
    labelKey: 'radioPanel.gpsModeLabel',
    sectionKey: POSITION,
    keywords: ['gps', 'enable', 'disable', 'not present'],
    visible: hasFullPosition,
  },
  {
    id: 'radio.position.precision',
    slot: 'Radio',
    labelKey: 'radioPanel.positionPrecisionLabel',
    sectionKey: POSITION,
    keywords: ['precision', 'privacy', 'accuracy', 'bits'],
    visible: hasFullPosition,
  },
  {
    id: 'radio.position.smartBroadcast',
    slot: 'Radio',
    labelKey: 'radioPanel.smartPositionBroadcastLabel',
    sectionKey: POSITION,
    keywords: ['smart', 'position', 'movement'],
    visible: hasFullPosition,
  },
  {
    id: 'radio.position.smartMinDistance',
    slot: 'Radio',
    labelKey: 'radioPanel.minDistanceTriggerLabel',
    sectionKey: POSITION,
    keywords: ['smart', 'distance', 'meters'],
    visible: hasFullPosition,
  },
  {
    id: 'radio.position.smartMinInterval',
    slot: 'Radio',
    labelKey: 'radioPanel.minIntervalLabel',
    sectionKey: POSITION,
    keywords: ['smart', 'interval', 'seconds'],
    visible: hasFullPosition,
  },
  {
    id: 'radio.position.fixedPosition',
    slot: 'Radio',
    labelKey: 'radioPanel.fixedPositionLabel',
    sectionKey: POSITION,
    keywords: ['fixed', 'static', 'manual', 'location'],
    visible: hasFullPosition,
  },
  {
    id: 'radio.position.sendToDevice',
    slot: 'Radio',
    labelKey: 'radioPanel.sendPositionToDevice',
    sectionKey: POSITION,
    keywords: ['latitude', 'longitude', 'altitude', 'coordinates', 'fixed'],
    visible: showsRadioPanel,
  },

  // Power
  {
    id: 'radio.power.section',
    slot: 'Radio',
    labelKey: POWER,
    keywords: ['power', 'battery', 'sleep'],
    visible: hasPower,
  },
  {
    id: 'radio.power.powerSaving',
    slot: 'Radio',
    labelKey: 'radioPanel.powerSavingModeLabel',
    sectionKey: POWER,
    keywords: ['power saving', 'battery', 'sleep'],
    visible: hasPower,
  },
  {
    id: 'radio.power.minWake',
    slot: 'Radio',
    labelKey: 'radioPanel.minWakeDurationLabel',
    sectionKey: POWER,
    keywords: ['wake', 'sleep'],
    visible: hasPower,
  },
  {
    id: 'radio.power.bluetoothIdle',
    slot: 'Radio',
    labelKey: 'radioPanel.bluetoothIdleTimeoutLabel',
    sectionKey: POWER,
    keywords: ['bluetooth', 'idle', 'timeout'],
    visible: hasPower,
  },
  {
    id: 'radio.power.superDeepSleep',
    slot: 'Radio',
    labelKey: 'radioPanel.superDeepSleepLabel',
    sectionKey: POWER,
    keywords: ['deep sleep', 'sds'],
    visible: hasPower,
  },
  {
    id: 'radio.power.lightSleep',
    slot: 'Radio',
    labelKey: 'radioPanel.lightSleepDurationLabel',
    sectionKey: POWER,
    keywords: ['light sleep', 'ls'],
    visible: hasPower,
  },
  {
    id: 'radio.power.batteryShutdown',
    slot: 'Radio',
    labelKey: 'radioPanel.batteryShutdownLabel',
    sectionKey: POWER,
    keywords: ['battery', 'shutdown', 'off'],
    visible: hasPower,
  },

  // MeshCore telemetry privacy
  {
    id: 'radio.telemetryPrivacy.section',
    slot: 'Radio',
    labelKey: TELEMETRY_PRIVACY,
    keywords: ['telemetry', 'privacy', 'permissions'],
    visible: hasTelemetryPrivacy,
  },
  {
    id: 'radio.telemetryPrivacy.allowTelemetry',
    slot: 'Radio',
    labelKey: 'meshcoreTelemetryPrivacy.allowTelemetryTitle',
    sectionKey: TELEMETRY_PRIVACY,
    keywords: ['telemetry', 'privacy', 'battery'],
    visible: hasTelemetryPrivacy,
  },
  {
    id: 'radio.telemetryPrivacy.location',
    slot: 'Radio',
    labelKey: 'meshcoreTelemetryPrivacy.includeLocationTitle',
    sectionKey: TELEMETRY_PRIVACY,
    keywords: ['location', 'gps', 'privacy'],
    visible: hasTelemetryPrivacy,
  },
  {
    id: 'radio.telemetryPrivacy.environment',
    slot: 'Radio',
    labelKey: 'meshcoreTelemetryPrivacy.includeEnvironmentTitle',
    sectionKey: TELEMETRY_PRIVACY,
    keywords: ['environment', 'sensors', 'temperature', 'privacy'],
    visible: hasTelemetryPrivacy,
  },

  // WiFi / network
  {
    id: 'radio.wifi.section',
    slot: 'Radio',
    labelKey: WIFI,
    keywords: ['wifi', 'network', 'ethernet'],
    visible: hasWifi,
  },
  {
    id: 'radio.wifi.enabled',
    slot: 'Radio',
    labelKey: 'radioPanel.wifiEnabledLabel',
    sectionKey: WIFI,
    keywords: ['wifi', 'wireless'],
    visible: hasWifi,
  },
  {
    id: 'radio.wifi.ssid',
    slot: 'Radio',
    labelKey: 'radioPanel.wifiSsidLabel',
    sectionKey: WIFI,
    keywords: ['ssid', 'network name', 'wifi'],
    visible: hasWifi,
  },
  {
    id: 'radio.wifi.password',
    slot: 'Radio',
    labelKey: 'radioPanel.wifiPasswordLabel',
    sectionKey: WIFI,
    keywords: ['password', 'psk', 'wifi'],
    visible: hasWifi,
  },
  {
    id: 'radio.wifi.ntpServer',
    slot: 'Radio',
    labelKey: 'radioPanel.ntpServerLabel',
    sectionKey: WIFI,
    keywords: ['ntp', 'time', 'clock'],
    visible: hasWifi,
  },
  {
    id: 'radio.wifi.ethernet',
    slot: 'Radio',
    labelKey: 'radioPanel.ethernetEnabledLabel',
    sectionKey: WIFI,
    keywords: ['ethernet', 'wired', 'lan'],
    visible: hasWifi,
  },

  // Display
  {
    id: 'radio.display.section',
    slot: 'Radio',
    labelKey: DISPLAY,
    keywords: ['screen', 'oled', 'display'],
    visible: hasDisplay,
  },
  {
    id: 'radio.display.screenOn',
    slot: 'Radio',
    labelKey: 'radioPanel.screenOnDurationLabel',
    sectionKey: DISPLAY,
    keywords: ['screen', 'timeout'],
    visible: hasDisplay,
  },
  {
    id: 'radio.display.units',
    slot: 'Radio',
    labelKey: 'radioPanel.displayUnitsFieldLabel',
    sectionKey: DISPLAY,
    keywords: ['metric', 'imperial', 'units'],
    visible: hasDisplay,
  },
  {
    id: 'radio.display.carousel',
    slot: 'Radio',
    labelKey: 'radioPanel.autoScreenCarouselSecsLabel',
    sectionKey: DISPLAY,
    keywords: ['carousel', 'rotate', 'screens'],
    visible: hasDisplay,
  },
  {
    id: 'radio.display.oledType',
    slot: 'Radio',
    labelKey: 'radioPanel.oledTypeLabel',
    sectionKey: DISPLAY,
    keywords: ['oled', 'ssd1306', 'sh1106'],
    visible: hasDisplay,
  },
  {
    id: 'radio.display.mode',
    slot: 'Radio',
    labelKey: 'radioPanel.displayModeLabel',
    sectionKey: DISPLAY,
    keywords: ['display mode', 'color', 'inverted'],
    visible: hasDisplay,
  },
  {
    id: 'radio.display.flipScreen',
    slot: 'Radio',
    labelKey: 'radioPanel.flipScreenLabel',
    sectionKey: DISPLAY,
    keywords: ['flip', 'rotate', 'upside down'],
    visible: hasDisplay,
  },
  {
    id: 'radio.display.headingBold',
    slot: 'Radio',
    labelKey: 'radioPanel.headingBoldLabel',
    sectionKey: DISPLAY,
    keywords: ['bold', 'heading', 'font'],
    visible: hasDisplay,
  },
  {
    id: 'radio.display.wakeOnTap',
    slot: 'Radio',
    labelKey: 'radioPanel.wakeOnTapOrMotionLabel',
    sectionKey: DISPLAY,
    keywords: ['wake', 'tap', 'motion', 'accelerometer'],
    visible: hasDisplay,
  },
  {
    id: 'radio.display.use12hClock',
    slot: 'Radio',
    labelKey: 'radioPanel.use12hClockLabel',
    sectionKey: DISPLAY,
    keywords: ['clock', '12 hour', 'am pm', 'time format'],
    visible: hasDisplay,
  },
  {
    id: 'radio.display.longNodeName',
    slot: 'Radio',
    labelKey: 'radioPanel.useLongNodeNameLabel',
    sectionKey: DISPLAY,
    keywords: ['long name', 'node name'],
    visible: hasDisplay,
  },
  {
    id: 'radio.display.messageBubbles',
    slot: 'Radio',
    labelKey: 'radioPanel.enableMessageBubblesLabel',
    sectionKey: DISPLAY,
    keywords: ['bubbles', 'messages', 'chat'],
    visible: hasDisplay,
  },

  // Bluetooth
  {
    id: 'radio.bluetooth.section',
    slot: 'Radio',
    labelKey: BLUETOOTH,
    keywords: ['bluetooth', 'ble', 'pairing'],
    visible: hasBluetooth,
  },
  {
    id: 'radio.bluetooth.enabled',
    slot: 'Radio',
    labelKey: 'radioPanel.bluetoothEnabled',
    sectionKey: BLUETOOTH,
    keywords: ['bluetooth', 'ble'],
    visible: hasBluetooth,
  },
  {
    id: 'radio.bluetooth.pairingMode',
    slot: 'Radio',
    labelKey: 'radioPanel.btPairingModeLabel',
    sectionKey: BLUETOOTH,
    keywords: ['pairing', 'random pin', 'fixed pin', 'no pin'],
    visible: hasBluetooth,
  },
  {
    id: 'radio.bluetooth.pin',
    slot: 'Radio',
    labelKey: 'radioPanel.pairingPin',
    sectionKey: BLUETOOTH,
    keywords: ['pin', 'pairing', 'passkey'],
    visible: hasBluetooth,
  },

  // Device actions (MeshCore)
  {
    id: 'radio.actions.floodAdvert',
    slot: 'Radio',
    labelKey: 'radioPanel.floodAdvertButton',
    sectionKey: ACTIONS,
    keywords: ['advert', 'advertise', 'announce', 'flood'],
    visible: (ctx) => ctx.capabilities.hasContactImportExport,
  },
  {
    id: 'radio.actions.zeroHopAdvert',
    slot: 'Radio',
    labelKey: 'radioPanel.zeroHopAdvertButton',
    sectionKey: ACTIONS,
    keywords: ['advert', 'advertise', 'zero hop', 'local'],
    visible: (ctx) => ctx.capabilities.hasContactImportExport,
  },
  {
    id: 'radio.actions.syncClock',
    slot: 'Radio',
    labelKey: 'radioPanel.syncClockButton',
    sectionKey: ACTIONS,
    keywords: ['clock', 'time', 'sync'],
    visible: isCompanion,
  },

  // MeshCore experimental
  {
    id: 'radio.experimental.openWireCompat',
    slot: 'Radio',
    labelKey: 'appPanel.meshcoreOpenWireCompatLabel',
    sectionKey: 'appPanel.meshcoreOpenWireExperimentalTitle',
    keywords: ['experimental', 'compatibility', 'wire'],
    visible: isCompanion,
  },
  {
    id: 'radio.experimental.pathHashMode',
    slot: 'Radio',
    labelKey: 'appPanel.meshcorePathHashModeLabel',
    sectionKey: 'appPanel.meshcorePathHashExperimentalTitle',
    keywords: ['path hash', 'experimental', 'bytes', 'routing'],
    visible: isCompanion,
  },
];

export const radioSurface: SettingsSearchSurface = {
  entries: radioEntries,
  files: [
    { path: 'src/renderer/components/RadioPanel.tsx', sweepAllKeys: true },
    { path: 'src/renderer/components/MeshcoreContactSettingsSection.tsx', sweepAllKeys: true },
    { path: 'src/renderer/components/MeshcoreTelemetryPrivacySection.tsx', sweepAllKeys: true },
    { path: 'src/renderer/components/LockdownSection.tsx', sweepAllKeys: true },
  ],
  exempt: {
    'radioPanel.*Desc': 'help text under a control; the control is indexed',
    'radioPanel.*Description': 'help text under a control; the control is indexed',
    'radioPanel.*Hint*': 'help text under a control; the control is indexed',
    'radioPanel.*Tooltip': 'tooltip on a control or status icon, not a control',
    'radioPanel.*Placeholder': 'input placeholder; its field is indexed or exempted',
    'radioPanel.*Failed': 'error toast or status text, not a control',
    'radioPanel.apply*': 'Apply progress and result status text',
    'radioPanel.configImported*': 'JSON import result toast, not a control',
    'radioPanel.offload*': 'offload progress and result toasts of the indexed offload button',
    'radioPanel.gpsMode*': 'option values of the indexed GPS mode',
    'radioPanel.txPowerMax*': 'limit text under the indexed TX power field',
    'radioPanel.channelName*': 'per-channel edit form, shown only after selecting a channel',
    'radioPanel.channelRole*': 'per-channel role values in the indexed Channels list',
    'radioPanel.encryption*': 'per-channel edit form, shown only after selecting a channel',
    'radioPanel.keySize*': 'per-channel edit form, shown only after selecting a channel',
    'radioPanel.mqtt*': 'per-channel MQTT toggles, shown only after selecting a channel',
    'radioPanel.validation*': 'per-channel PSK validation errors, not a control',
    'radioPanel.channelUrl.apply*': 'import confirm button and result, shown after a link parses',
    'radioPanel.channelUrl.confirm*': 'confirmation dialog copy for the indexed link import',
    'radioPanel.channelUrl.cop*': 'copy buttons and toasts inside the indexed share row',
    'radioPanel.channelUrl.*Warning': 'warning text inside the indexed share/import rows',
    'radioPanel.channelUrl.preview*': 'parsed-link preview text, not a control',
    'radioPanel.channelUrl.role*': 'channel role words inside the parsed-link preview',
    'radioPanel.channelUrl.mode*': 'add/replace badge inside the parsed-link preview',
    'radioPanel.channelUrl.*UrlLabel':
      'read-only generated link fields inside the indexed share row',
    'radioPanel.channelUrl.exportTitle': 'sub-heading of the indexed share row',
    'radioPanel.channelUrl.importTitle': 'sub-heading of the indexed import row',
    'radioPanel.channelUrl.includeSecondary': 'export option inside the indexed share row',
    'radioPanel.channelUrl.channelRow': 'parsed-link preview text, not a control',
    'radioPanel.channelUrl.unnamedChannel': 'parsed-link preview text, not a control',
    'radioPanel.channelUrl.connectToImport': 'status text in the indexed import row',
    'radioPanel.channelUrl.noChannelsToExport': 'error toast, not a control',
    'radioPanel.channelUrl.qrAria': 'accessible name of the generated QR image',
    'radioPanel.channelUrl.qrHeading': 'caption of the generated QR image',
    'radioPanel.meshcoreChannel.*':
      'MeshCore channel row actions and add/edit form; the channel card and add button are indexed',
    'radioPanel.meshcoreChannelName*': 'MeshCore channel add/edit form field',
    'radioPanel.meshcoreChannelKeyLabel': 'MeshCore channel add/edit form field',
    'radioPanel.meshcoreDeriveFromName': 'MeshCore channel add/edit form button',
    'radioPanel.meshcoreDeriving': 'busy label of a channel form button',
    'radioPanel.meshcoreGenerateRandomKey': 'MeshCore channel add/edit form button',
    'radioPanel.meshcoreSha256KeyTitle': 'tooltip on a channel form button',
    'radioPanel.channelN': 'channel slot name in the indexed Channels list',
    'radioPanel.channelLoading': 'channel slot status text',
    'radioPanel.channelResetStatus': 'channel edit status text',
    'radioPanel.channelSavedStatus': 'channel edit status text',
    'radioPanel.editChannelTitle': 'per-channel edit form heading',
    'radioPanel.disableChannel': 'per-channel edit form button',
    'radioPanel.resetChannelDefaults': 'per-channel edit form button',
    'radioPanel.saveChannel': 'per-channel edit form button',
    'radioPanel.savingChannel': 'busy label of the channel save button',
    'radioPanel.generateRandomKey': 'per-channel edit form button',
    'radioPanel.regeneratePsk': 'per-channel edit form button',
    'radioPanel.positionPrecisionChannelLabel': 'per-channel edit form field',
    'radioPanel.hideKey': 'reveal toggle tooltip on a channel row',
    'radioPanel.revealKey': 'reveal toggle tooltip on a channel row',
    'radioPanel.retryRemoteChannels': 'retry link for remote channel loading, not a setting',
    'radioPanel.noChannels': 'empty-state text',
    'radioPanel.title': 'panel heading; the launcher already lists the Radio panel',
    'radioPanel.connectToConfigure': 'connection banner, not a control',
    'radioPanel.waitingForConfigSection': 'loading status text inside a section',
    'radioPanel.sectionGroupDevice': 'group heading above the device sections; each is indexed',
    'radioPanel.secondsUnit': 'unit label beside a number field',
    'radioPanel.metersUnit': 'unit label beside a number field',
    'radioPanel.txPowerDeviceCurrent': 'status text under the indexed TX power field',
    'radioPanel.advertisedPositionLabel': 'status text in the indexed position row',
    'radioPanel.latitudeLabel': 'coordinate field of the indexed send-position row',
    'radioPanel.longitudeLabel': 'coordinate field of the indexed send-position row',
    'radioPanel.altitudeMetersLabel': 'coordinate field of the indexed send-position row',
    'radioPanel.useCurrentGps': 'fill-from-GPS link of the indexed send-position row',
    'radioPanel.invalidCoordinates': 'error toast, not a control',
    'radioPanel.positionSent': 'success toast, not a control',
    'radioPanel.sendPositionDisabledShareOff': 'disabled-state tooltip of the send-position button',
    'radioPanel.enumDeprecatedSuffix': 'suffix on deprecated option values',
    'radioPanel.clientMuteGpsSuppressed': 'status text after applying the device role',
    'radioPanel.clockSynced': 'success toast, not a control',
    'radioPanel.floodAdvertSent': 'success toast, not a control',
    'radioPanel.zeroHopAdvertSent': 'success toast, not a control',
    'radioPanel.floodScopeApplySuccess': 'success status, not a control',
    'radioPanel.contactManagementUpdated': 'success toast, not a control',
    'radioPanel.telemetryPrivacyUpdated': 'success toast, not a control',
    'radioPanel.contactsOnRadioBadgeTitle': 'tooltip on the contact count badge',
    'radioPanel.removeAllContactsTitle': 'tooltip on the indexed offload button',
    'radioPanel.failedOffloadContacts': 'error toast, not a control',
    'radioPanel.lockdown.*Label':
      'status rows and passphrase field inside the indexed Lockdown card',
    'radioPanel.lockdown.*Aria': 'accessible-name variant of a Lockdown card button',
    'radioPanel.lockdown.description': 'card prose; the Lockdown card is indexed',
    'radioPanel.lockdown.backoffValue': 'status value inside the Lockdown card',
    'radioPanel.lockdown.stateNotReported': 'status value inside the Lockdown card',
    'radioPanel.lockdown.provision': 'action button inside the indexed Lockdown card',
    'radioPanel.lockdown.unlock': 'action button inside the indexed Lockdown card',
    'radioPanel.lockdown.lockNow': 'action button inside the indexed Lockdown card',
    'radioPanel.lockdown.disable': 'action button inside the indexed Lockdown card',
    'appPanel.meshcoreOpenWireCompatHint': 'help text for the indexed open-wire toggle',
    'appPanel.meshcorePathHashModeHint': 'help text for the indexed path hash mode',
    'appPanel.meshcorePathHashApplyFailed': 'error toast, not a control',
    'appPanel.meshcorePathHashMode*Byte': 'option values of the indexed path hash mode',
    'appPanel.meshcorePathHashModeShort*': 'device-reported value text for the path hash mode',
    'appPanel.meshcorePathHashDeviceReported': 'status text under the indexed path hash mode',
    'modulePanel.applySection': 'section Apply button; the section is indexed',
    'modulePanel.applyingButton': 'busy label of a section Apply button',
    'configureNode.loading': 'remote config loading status text',
    'qrIngest.*': 'QR paste hint and import toasts, not a setting',
    'meshcoreContactSettings.*Desc': 'help text under a control; the control is indexed',
    'meshcoreContactSettings.*Help': 'help text under a control; the control is indexed',
    'meshcoreContactSettings.autoAdd*Title': 'option values of the indexed auto-add mode',
    'meshcoreContactSettings.type*': 'contact-type checkboxes inside the indexed auto-add types',
    'meshcoreContactSettings.autoOffloadWhenFull':
      'accessible name of the indexed auto-offload toggle',
    'meshcoreContactSettings.overwriteOldest':
      'accessible name of the indexed overwrite-oldest toggle',
    'meshcoreContactSettings.showPublicKeys':
      'accessible name of the indexed show-public-keys toggle',
    'meshcoreContactSettings.showRefreshControl': 'accessible name of the indexed refresh toggle',
    'meshcoreContactSettings.clearAllContacts': 'accessible name of the indexed clear-all button',
    'meshcoreContactSettings.clearAllContactsConfirm':
      'confirmation prompt for the indexed clear-all',
    'meshcoreContactSettings.clearAllIntro': 'prose above the indexed clear-all button',
    'meshcoreContactSettings.clearingContacts': 'busy label of the indexed clear-all button',
    'meshcoreContactSettings.allContactsCleared': 'success toast, not a control',
    'meshcoreContactSettings.failedClearContacts': 'error toast, not a control',
    'meshcoreContactSettings.maxHopsInvalid': 'validation error of the indexed max hops field',
    'meshcoreContactSettings.noLimitPlaceholder': 'placeholder of the indexed max hops field',
    'meshcoreContactSettings.intro': 'card prose; its rows are indexed',
    'meshcoreContactSettings.overwriteOldestEvictsNote':
      'note shown when two indexed toggles are on',
    'meshcoreTelemetryPrivacy.allowAll*': 'option description inside an indexed telemetry row',
    'meshcoreTelemetryPrivacy.deny*': 'option description inside an indexed telemetry row',
    'meshcoreTelemetryPrivacy.*SpecificContacts': 'option label inside an indexed telemetry row',
    'meshcoreTelemetryPrivacy.contactCount': 'option description inside an indexed telemetry row',
    'meshcoreTelemetryPrivacy.description': 'card prose; its rows are indexed',
    'meshcoreTelemetryPrivacy.applyButton': 'card Apply button; the card is indexed',
    'meshcoreTelemetryPrivacy.applying': 'busy label of the card Apply button',
  },
};
