import type {
  SettingSearchEntry,
  SettingsSearchContext,
  SettingsSearchSurface,
} from '../settingsSearch';

// The Radio slot hosts ReticulumNetworkPanel only when this flag is set (RadioPanel otherwise).
const hasNetworkPanel = (ctx: SettingsSearchContext) => ctx.capabilities.hasReticulumNetworkPanel;

const STACK = 'networkPanel.reticulumStackSettings.title';
const IDENTITY = 'connectionPanel.reticulumIdentity.title';
const PROPAGATION = 'connectionPanel.reticulumPropagation.title';
const PN_HOSTING = 'networkPanel.reticulumPnHosting.title';

const reticulumRadioEntries: readonly SettingSearchEntry[] = [
  {
    id: 'radio.reticulumStack.enableTransport',
    slot: 'Radio',
    labelKey: 'networkPanel.reticulumStackSettings.enableTransport',
    sectionKey: STACK,
    keywords: ['transport node', 'routing', 'relay', 'rns'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumStack.shareInstance',
    slot: 'Radio',
    labelKey: 'networkPanel.reticulumStackSettings.shareInstance',
    sectionKey: STACK,
    keywords: ['shared instance', 'rnsd', 'local clients'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumStack.logLevel',
    slot: 'Radio',
    labelKey: 'networkPanel.reticulumStackSettings.logLevel',
    sectionKey: STACK,
    keywords: ['loglevel', 'debug', 'verbose', 'logging'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumStack.pathMediumPreference',
    slot: 'Radio',
    labelKey: 'networkPanel.reticulumStackSettings.pathMediumPreference',
    sectionKey: STACK,
    keywords: ['path', 'route', 'rf', 'internet', 'lowest hops'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumStack.autoconnectDiscovered',
    slot: 'Radio',
    labelKey: 'networkPanel.reticulumStackSettings.autoconnectDiscovered',
    sectionKey: STACK,
    keywords: ['interface discovery', 'auto connect', 'discovered interfaces'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumStack.requiredDiscoveryValue',
    slot: 'Radio',
    labelKey: 'networkPanel.reticulumStackSettings.requiredDiscoveryValue',
    sectionKey: STACK,
    keywords: ['interface discovery', 'stamp', 'proof of work'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumStack.discoverySources',
    slot: 'Radio',
    labelKey: 'networkPanel.reticulumStackSettings.discoverySources',
    sectionKey: STACK,
    keywords: ['interface discovery', 'sources', 'trusted'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumStack.networkIdentity',
    slot: 'Radio',
    labelKey: 'networkPanel.reticulumStackSettings.networkIdentity',
    sectionKey: STACK,
    keywords: ['network identity', 'discovery', 'publish'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumScanImport.qrCode',
    slot: 'Radio',
    labelKey: 'networkPanel.reticulumScanImport.title',
    keywords: ['qr', 'scan', 'paste', 'lxm link', 'contact'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumIdentity.slots',
    slot: 'Radio',
    labelKey: 'connectionPanel.reticulumIdentity.slotsTitle',
    sectionKey: IDENTITY,
    keywords: ['switch identity', 'multiple identities', 'profiles'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumIdentity.displayName',
    slot: 'Radio',
    labelKey: 'connectionPanel.reticulumIdentity.displayName',
    sectionKey: IDENTITY,
    keywords: ['name', 'nickname', 'announce name', 'lxmf'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumIdentity.export',
    slot: 'Radio',
    labelKey: 'connectionPanel.reticulumIdentity.export',
    sectionKey: IDENTITY,
    keywords: ['backup', 'rsi', 'export identity', 'private key'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumIdentity.generate',
    slot: 'Radio',
    labelKey: 'connectionPanel.reticulumIdentity.generate',
    sectionKey: IDENTITY,
    keywords: ['new identity', 'create', 'mnemonic'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumIdentity.importMnemonic',
    slot: 'Radio',
    labelKey: 'connectionPanel.reticulumIdentity.importLabel',
    sectionKey: IDENTITY,
    keywords: ['restore', 'bip-39', 'recovery phrase', 'seed'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumIdentity.importBackup',
    slot: 'Radio',
    labelKey: 'connectionPanel.reticulumIdentity.importBackupLabel',
    sectionKey: IDENTITY,
    keywords: ['restore', 'rsi', 'backup'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumIdentity.importPrivateKey',
    slot: 'Radio',
    labelKey: 'connectionPanel.reticulumIdentity.importPrivateKeyLabel',
    sectionKey: IDENTITY,
    keywords: ['restore', 'private key', 'raw identity'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumIdentity.vaultPasscode',
    slot: 'Radio',
    labelKey: 'identityVault.title',
    sectionKey: IDENTITY,
    keywords: ['passcode', 'lock', 'unlock', 'encrypt identity'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumAnnounce.interval',
    slot: 'Radio',
    labelKey: 'reticulumIdentity.announceIntervalSec',
    sectionKey: IDENTITY,
    keywords: ['announce', 'interval', 'seconds', 'beacon'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumAnnounce.announceNow',
    slot: 'Radio',
    labelKey: 'reticulumIdentity.announceNow',
    sectionKey: IDENTITY,
    keywords: ['announce', 'advertise'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumAnnounce.clearAnnounces',
    slot: 'Radio',
    labelKey: 'reticulumIdentity.clearAnnounces',
    sectionKey: IDENTITY,
    keywords: ['announce', 'clear', 'cache'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumRmap.discovery',
    slot: 'Radio',
    labelKey: 'reticulumRmapDiscovery.sectionTitle',
    keywords: ['rmap', 'map', 'publish', 'discoverable', 'interface discovery'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumBlocklist.blockedContacts',
    slot: 'Radio',
    labelKey: 'appPanel.reticulumBlocklist.title',
    keywords: ['block', 'unblock', 'ignore', 'blocklist'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumConfigImport.importConfig',
    slot: 'Radio',
    labelKey: 'networkPanel.reticulumConfigImport.title',
    keywords: ['config', 'rnsd', 'import', 'merge', 'replace'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumConfigImport.validate',
    slot: 'Radio',
    labelKey: 'networkPanel.reticulumConfigValidate.button',
    sectionKey: 'networkPanel.reticulumConfigImport.title',
    keywords: ['config', 'check', 'lint'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumPropagation.mode',
    slot: 'Radio',
    labelKey: 'reticulumPropagation.modeLabel',
    sectionKey: PROPAGATION,
    keywords: ['propagation node', 'pn', 'auto', 'manual', 'lxmf'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumPropagation.autoSyncInterval',
    slot: 'Radio',
    labelKey: 'reticulumPropagation.autoSyncIntervalLabel',
    sectionKey: PROPAGATION,
    keywords: ['propagation node', 'sync', 'interval'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumPropagation.syncNow',
    slot: 'Radio',
    labelKey: 'reticulumPropagation.syncNow',
    sectionKey: PROPAGATION,
    keywords: ['propagation node', 'fetch', 'download messages'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumPropagation.addNode',
    slot: 'Radio',
    labelKey: 'reticulumPropagation.addNodeLabel',
    sectionKey: PROPAGATION,
    keywords: ['propagation node', 'pn', 'add', 'hash'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumPropagation.discoveredNodes',
    slot: 'Radio',
    labelKey: 'reticulumPropagation.discoveredTitle',
    sectionKey: PROPAGATION,
    keywords: ['propagation node', 'select', 'preferred', 'ignore'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumPropagation.showChatNotice',
    slot: 'Radio',
    labelKey: 'reticulumPropagation.showChatNotice',
    sectionKey: PROPAGATION,
    keywords: ['propagation node', 'chat', 'banner', 'notice'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumPnHosting.settings',
    slot: 'Radio',
    labelKey: PN_HOSTING,
    keywords: ['propagation node', 'host', 'lxmd', 'peering', 'stamp cost', 'storage'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumPnHosting.autopeer',
    slot: 'Radio',
    labelKey: 'networkPanel.reticulumPnHosting.autopeer',
    sectionKey: PN_HOSTING,
    keywords: ['propagation node', 'peering', 'lxmd'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumPnHosting.authRequired',
    slot: 'Radio',
    labelKey: 'networkPanel.reticulumPnHosting.authRequired',
    sectionKey: PN_HOSTING,
    keywords: ['propagation node', 'auth', 'access control'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumPnHosting.nodeName',
    slot: 'Radio',
    labelKey: 'networkPanel.reticulumPnHosting.nodeName',
    sectionKey: PN_HOSTING,
    keywords: ['propagation node', 'name'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumPnHosting.staticPeers',
    slot: 'Radio',
    labelKey: 'networkPanel.reticulumPnHosting.staticPeers',
    sectionKey: PN_HOSTING,
    keywords: ['propagation node', 'peers', 'static'],
    visible: hasNetworkPanel,
  },
  {
    id: 'radio.reticulumPathTable.clear',
    slot: 'Radio',
    labelKey: 'networkPanel.reticulumPathTable.clear',
    sectionKey: 'networkPanel.reticulumPathTable.title',
    keywords: ['path table', 'routes', 'reset', 'flush'],
    visible: hasNetworkPanel,
  },
];

export const reticulumRadioSurface: SettingsSearchSurface = {
  entries: reticulumRadioEntries,
  files: [
    { path: 'src/renderer/components/ReticulumNetworkPanel.tsx', sweepAllKeys: true },
    { path: 'src/renderer/components/ReticulumPropagationSection.tsx', sweepAllKeys: true },
    { path: 'src/renderer/components/ReticulumAnnounceControls.tsx', sweepAllKeys: true },
    { path: 'src/renderer/components/IdentityVaultPanel.tsx', sweepAllKeys: true },
    { path: 'src/renderer/components/ReticulumPnHostingDangerZone.tsx', sweepAllKeys: true },
    { path: 'src/renderer/components/ReticulumPathTableMaintenance.tsx', sweepAllKeys: true },
  ],
  exempt: {
    'connectionPanel.reticulumIdentity.*Aria': 'accessible-name variant of an identity control',
    'connectionPanel.reticulumIdentity.*Confirm*': 'identity replace/switch/delete dialog copy',
    'connectionPanel.reticulumIdentity.slot*':
      'per-identity row actions and status inside the indexed Identities list',
    'connectionPanel.reticulumIdentity.copy*': 'copy-to-clipboard button for an identity hash',
    'connectionPanel.reticulumIdentity.*Label': 'read-only identity hash or import row label',
    'connectionPanel.reticulumIdentity.invalid*': 'identity import validation error',
    'connectionPanel.reticulumIdentity.*Require*': 'identity import/export validation error',
    'connectionPanel.reticulumIdentity.import*':
      'source buttons and PIN field of the indexed import rows',
    'connectionPanel.reticulumIdentity.backupHashMismatch': 'identity import validation error',
    'connectionPanel.reticulumIdentity.exportPassphraseMismatch':
      'identity export validation error',
    'connectionPanel.reticulumIdentity.identityAlreadyConfigured': 'identity setup error',
    'connectionPanel.reticulumIdentity.identityFileMissing': 'identity setup error',
    'connectionPanel.reticulumIdentity.failed': 'identity action error toast',
    'connectionPanel.reticulumIdentity.displayNameSaved': 'result toast, not a control',
    'connectionPanel.reticulumIdentity.exportSaved': 'result toast, not a control',
    'connectionPanel.reticulumIdentity.confirmSaved': 'setup step checkbox for a new mnemonic',
    'connectionPanel.reticulumIdentity.exportPassphrase':
      'passphrase field of the indexed export action',
    'connectionPanel.reticulumIdentity.exportRaw': 'variant button of the indexed export action',
    'connectionPanel.reticulumIdentity.saveDisplayName':
      'save button of the indexed display name field',
    'connectionPanel.reticulumIdentity.mnemonic': 'mnemonic field of the indexed import row',
    'connectionPanel.reticulumIdentity.hint': 'identity card description',
    'connectionPanel.reticulumIdentity.replaceIdentitySection': 'sub-heading above import rows',
    'connectionPanel.reticulumIdentity.startStackFirst': 'stack-stopped notice, not a control',
    'networkPanel.reticulumConfigImport.*':
      'source buttons, paste box and confirm dialog of the indexed config import card',
    'networkPanel.reticulumConfigImportFailed': 'result toast, not a control',
    'networkPanel.reticulumConfigNotFound': 'result toast, not a control',
    'networkPanel.reticulumConfigValidate.*':
      'result text and busy label of the indexed validate button',
    'networkPanel.reticulumScanImport.hint': 'description of the indexed QR import card',
    'networkPanel.reticulumStackSettings.*Aria': 'accessible-name variant of a stack setting',
    'networkPanel.reticulumStackSettings.*Hint': 'help text under a stack setting',
    'networkPanel.reticulumStackSettings.*Placeholder': 'input placeholder of a stack setting',
    'networkPanel.reticulumStackSettings.pathMedium*':
      'option values and save results of the indexed path medium preference',
    'networkPanel.reticulumStackSettings.discoveryConsumeTitle':
      'sub-heading above indexed discovery settings',
    'networkPanel.reticulumStackSettings.discoverySourcesInvalid': 'validation error',
    'networkPanel.reticulumStackSettings.save': 'save button for the indexed stack settings',
    'networkPanel.reticulumStackSettings.saveFailed': 'result toast, not a control',
    'reticulumSetup.open': 'navigation link to the setup guide, not a setting',
    'reticulumSetup.tabUnavailable': 'navigation error toast',
    'connectionPanel.reticulumPropagation.enable': 'per-node toggle in the propagation list',
    'connectionPanel.reticulumPropagation.disable': 'per-node toggle in the propagation list',
    'reticulumPropagation.*Aria': 'accessible-name variant of a propagation control',
    'reticulumPropagation.*Failed': 'result toast, not a control',
    'reticulumPropagation.*Confirm*': 'propagation delete/local-host dialog copy',
    'reticulumPropagation.*Hint': 'help text under a propagation control',
    'reticulumPropagation.mode*': 'option values and help of the indexed propagation mode',
    'reticulumPropagation.discovered*': 'per-row text and actions in the indexed discovered list',
    'reticulumPropagation.*ForAuto*': 'per-node ignore/allow for Auto mode',
    'reticulumPropagation.rename*': 'per-node rename editor',
    'reticulumPropagation.sync*':
      'sync status text and per-node sync buttons; the main Sync now is indexed',
    'reticulumPropagation.localHost*': 'local propagation host row text',
    'reticulumPropagation.addNode': 'button of the indexed add-node row',
    'reticulumPropagation.addNodePlaceholder': 'input placeholder of the indexed add-node row',
    'reticulumPropagation.addProbing': 'busy label of the indexed add-node row',
    'reticulumPropagation.cancelSync': 'busy-state variant of the indexed Sync now',
    'reticulumPropagation.delete': 'per-node action in the propagation list',
    'reticulumPropagation.setPreferred': 'per-node action in the propagation list',
    'reticulumPropagation.preferred': 'per-node badge',
    'reticulumPropagation.preferredLocalWarning': 'per-node warning text',
    'reticulumPropagation.lastSynced': 'sync status text, not a control',
    'reticulumIdentity.announceIntervalHint': 'help text under the indexed announce interval',
    'reticulumIdentity.*Done': 'result toast, not a control',
    'reticulumIdentity.*Failed': 'result toast, not a control',
    'reticulumIdentity.announceSaved': 'result toast, not a control',
    'reticulumIdentity.announceSaveSidecarStopped': 'result toast, not a control',
    'identityVault.status*': 'vault status text, not a control',
    'identityVault.*Success': 'result toast, not a control',
    'identityVault.*Failed': 'result toast, not a control',
    'identityVault.passcode*': 'passcode field and validation inside the indexed vault card',
    'identityVault.confirmPasscode': 'field inside the indexed vault card',
    'identityVault.setPasscode': 'button inside the indexed vault card',
    'identityVault.lock': 'button inside the indexed vault card',
    'identityVault.unlock': 'button inside the indexed vault card',
    'identityVault.hint': 'vault card description',
    'networkPanel.reticulumPnHosting.save*':
      'save button, dialog and result of the PN hosting card',
    'networkPanel.reticulumPnHosting.saving': 'busy label of the PN hosting save button',
    'networkPanel.reticulumPnHosting.announceAtStart': 'field inside the indexed PN hosting card',
    'networkPanel.reticulumPnHosting.announceIntervalSec':
      'field inside the indexed PN hosting card',
    'networkPanel.reticulumPnHosting.autopeerMaxdepth': 'field inside the indexed PN hosting card',
    'networkPanel.reticulumPnHosting.deliveryLimitKb': 'field inside the indexed PN hosting card',
    'networkPanel.reticulumPnHosting.fromStaticOnly': 'field inside the indexed PN hosting card',
    'networkPanel.reticulumPnHosting.maxPeeringCost': 'field inside the indexed PN hosting card',
    'networkPanel.reticulumPnHosting.maxPeers': 'field inside the indexed PN hosting card',
    'networkPanel.reticulumPnHosting.peeringCost': 'field inside the indexed PN hosting card',
    'networkPanel.reticulumPnHosting.propagationLimitKb':
      'field inside the indexed PN hosting card',
    'networkPanel.reticulumPnHosting.stampCost': 'field inside the indexed PN hosting card',
    'networkPanel.reticulumPnHosting.stampFlex': 'field inside the indexed PN hosting card',
    'networkPanel.reticulumPnHosting.storageMb': 'field inside the indexed PN hosting card',
    'networkPanel.reticulumPnHosting.syncLimitKb': 'field inside the indexed PN hosting card',
    'networkPanel.reticulumPnHosting.staticPeersPlaceholder':
      'input placeholder of the indexed static peers field',
    'networkPanel.reticulumPnHosting.enforceUnavailableTip': 'tooltip, not a control',
    'networkPanel.reticulumPnHosting.warning': 'danger zone warning prose',
    'networkPanel.reticulumPathTable.clear*': 'aria, busy label and results of the indexed Clear',
    'networkPanel.reticulumPathTable.confirm*': 'path table clear confirmation dialog copy',
    'networkPanel.reticulumPathTable.description': 'path table card description',
    'connectionPanel.reticulumIdentity.exportSaveFailed': 'error toast, not a control',
    'connectionPanel.reticulumIdentity.saveDisplayNameFailed': 'error toast, not a control',
    'qrIngest.pasteImageHint': 'QR import help text',
    'qrIngest.unknownLink': 'QR import error text',
    'connectionPanel.reticulumIdentity.replaceIdentityHint': 'help text for the identity card',
    'qrIngest.showIdentityQrAria': 'accessible name of the identity QR button',
    'qrIngest.showIdentityQr': 'identity QR button inside the indexed identity card',
  },
};
