import type { SettingSearchEntry, SettingsSearchSurface } from '../settingsSearch';

const SYNC = 'roomsPanel.loginAndSyncHeading';

const roomsEntries: readonly SettingSearchEntry[] = [
  {
    id: 'rooms.list.loginAllSaved',
    slot: 'Rooms',
    labelKey: 'roomsPanel.loginAllSaved',
    sectionKey: 'roomsPanel.title',
    keywords: ['bbs', 'room server', 'login', 'saved passwords'],
  },
  {
    id: 'rooms.sync.autoLogin',
    slot: 'Rooms',
    labelKey: 'roomsPanel.autoLoginOnConnect',
    sectionKey: SYNC,
    keywords: ['bbs', 'room server', 'auto login', 'connect'],
  },
  {
    id: 'rooms.sync.autoSync',
    slot: 'Rooms',
    labelKey: 'roomsPanel.autoSync',
    sectionKey: SYNC,
    keywords: ['bbs', 'room server', 'sync', 'poll'],
  },
  {
    id: 'rooms.sync.syncInterval',
    slot: 'Rooms',
    labelKey: 'roomsPanel.syncIntervalLabel',
    sectionKey: SYNC,
    keywords: ['bbs', 'room server', 'sync', 'interval', 'minutes'],
  },
];

export const roomsSurface: SettingsSearchSurface = {
  entries: roomsEntries,
  files: [{ path: 'src/renderer/components/RoomsPanel.tsx', sweepAllKeys: true }],
  exempt: {
    'chatPanel.clearSenderFilter': 'room post view control reused from Chat, not a setting',
    'chatPanel.copyMessage': 'room post view control reused from Chat, not a setting',
    'chatPanel.dayToday': 'room post view control reused from Chat, not a setting',
    'chatPanel.dayYesterday': 'room post view control reused from Chat, not a setting',
    'chatPanel.emptyNoSearchMatches': 'room post view control reused from Chat, not a setting',
    'chatPanel.exportChat': 'room post view control reused from Chat, not a setting',
    'chatPanel.filteringBySender': 'room post view control reused from Chat, not a setting',
    'chatPanel.goToMessage': 'room post view control reused from Chat, not a setting',
    'chatPanel.jumpToDate': 'room post view control reused from Chat, not a setting',
    'chatPanel.muteConversation': 'room post view control reused from Chat, not a setting',
    'chatPanel.unmuteConversation': 'room post view control reused from Chat, not a setting',
    'chatPanel.noStarredMessages': 'room post view control reused from Chat, not a setting',
    'chatPanel.resendMessage': 'room post view control reused from Chat, not a setting',
    'chatPanel.searchMessages': 'room post view control reused from Chat, not a setting',
    'chatPanel.searchMessagesPlaceholder': 'room post view control reused from Chat, not a setting',
    'chatPanel.searchResults': 'room post view control reused from Chat, not a setting',
    'chatPanel.starMessage': 'room post view control reused from Chat, not a setting',
    'chatPanel.unstarMessage': 'room post view control reused from Chat, not a setting',
    'chatPanel.starredMessages': 'room post view control reused from Chat, not a setting',
    'aria.backToTop': 'room post view navigation',
    'nodeDetailModal.messageButton': 'room member action, not a setting',
    'roomsPanel.*Aria': 'accessible-name variant of a room control',
    'roomsPanel.*Tooltip': 'tooltip text, not a control',
    'roomsPanel.*Hint': 'help text, not a control',
    'roomsPanel.*Failed': 'result toast, not a control',
    'roomsPanel.badge*': 'per-room badge',
    'roomsPanel.legend*': 'room list legend',
    'roomsPanel.status*': 'per-room status text',
    'roomsPanel.members*': 'room members and ACL view',
    'roomsPanel.loginAllSavedDisabled*': 'disabled reason of the indexed Log in all saved',
    'roomsPanel.loginAllInProgress': 'busy label of the indexed Log in all saved',
    'roomsPanel.login*': 'per-room login card',
    'roomsPanel.loggingIn*': 'login progress text',
    'roomsPanel.leav*': 'per-room leave action and progress',
    'roomsPanel.syncInterval*': 'option values of the indexed sync interval',
    'roomsPanel.savedPassword*': 'saved-password list',
    'roomsPanel.forgetSavedPassword*': 'per-room saved-password action and dialog',
    'roomsPanel.guestPassword*': 'per-room guest login field',
    'roomsPanel.post*': 'room post composer and counts',
    'roomsPanel.jumpTo*': 'room post view navigation',
    'roomsPanel.stopAutoLogin': 'per-room action to stop a pending auto-login',
    'roomsPanel.autoLoginRequiresSavedPassword': 'disabled reason of the indexed auto-login',
    'roomsPanel.saveSyncConfig': 'save button for the indexed sync settings',
    'roomsPanel.rememberPassword': 'per-room login card checkbox',
    'roomsPanel.cancelLogin': 'per-room login progress action',
    'roomsPanel.continueReadOnly': 'per-room login card action',
    'roomsPanel.upgradeAccess': 'per-room login card action',
    'roomsPanel.readOnlyBadge': 'per-room badge',
    'roomsPanel.backToList': 'room view navigation',
    'roomsPanel.collapseRoomList': 'room list layout toggle',
    'roomsPanel.expandRoomList': 'room list layout toggle',
    'roomsPanel.selectRoom': 'room view navigation',
    'roomsPanel.details': 'per-room details toggle',
    'roomsPanel.hideDetails': 'per-room details toggle',
    'roomsPanel.manageRoom': 'per-room navigation to Repeaters admin',
    'roomsPanel.moreActions': 'per-room overflow menu',
    'roomsPanel.favorite': 'per-room favourite toggle',
    'roomsPanel.unfavorite': 'per-room favourite toggle',
    'roomsPanel.lastPost': 'per-room status text',
    'roomsPanel.lastSync': 'per-room status text',
    'roomsPanel.unreadPosts': 'per-room status text',
    'roomsPanel.newMessagesDivider': 'room post view divider',
    'roomsPanel.noPostsYet': 'empty state of the room post view',
    'roomsPanel.noRoomsYet': 'empty state of the room list',
    'roomsPanel.sidebarLegendTitle': 'room list legend heading',
  },
};
