import type { SettingSearchEntry, SettingsSearchSurface } from '../settingsSearch';

const SERVER = 'takServerPanel.serverSettings';
const REMOTE = 'takServerPanel.remoteTitle';
const STYLES = 'takServerPanel.unitStylesTitle';

const takEntries: readonly SettingSearchEntry[] = [
  {
    id: 'tak.server.port',
    slot: 'TAK',
    labelKey: 'takServerPanel.portLabel',
    sectionKey: SERVER,
    keywords: ['tak', 'atak', 'cot', '8089'],
  },
  {
    id: 'tak.server.serverName',
    slot: 'TAK',
    labelKey: 'takServerPanel.serverNameLabel',
    sectionKey: SERVER,
    keywords: ['tak', 'atak', 'name'],
  },
  {
    id: 'tak.server.requireCert',
    slot: 'TAK',
    labelKey: 'takServerPanel.requireCert',
    sectionKey: SERVER,
    keywords: ['tak', 'tls', 'client certificate', 'mtls'],
  },
  {
    id: 'tak.server.autoStart',
    slot: 'TAK',
    labelKey: 'takServerPanel.autoStart',
    sectionKey: SERVER,
    keywords: ['tak', 'startup', 'launch'],
  },
  {
    id: 'tak.server.startStop',
    slot: 'TAK',
    labelKey: 'takServerPanel.startServer',
    sectionKey: SERVER,
    keywords: ['tak', 'atak', 'stop server', 'run'],
  },
  {
    id: 'tak.dataPackage.generate',
    slot: 'TAK',
    labelKey: 'takServerPanel.generateReveal',
    sectionKey: 'takServerPanel.atakDataPackage',
    keywords: ['atak', 'data package', 'zip', 'itak', 'wintak'],
  },
  {
    id: 'tak.certificates.regenerate',
    slot: 'TAK',
    labelKey: 'takServerPanel.regenerateCerts',
    sectionKey: 'takServerPanel.certificates',
    keywords: ['tak', 'certificate', 'tls', 'reset'],
  },
  {
    id: 'tak.remote.host',
    slot: 'TAK',
    labelKey: 'takServerPanel.remoteHostLabel',
    sectionKey: REMOTE,
    keywords: ['tak server', 'relay', 'address', 'host'],
  },
  {
    id: 'tak.remote.port',
    slot: 'TAK',
    labelKey: 'takServerPanel.remotePortLabel',
    sectionKey: REMOTE,
    keywords: ['tak server', 'relay', '8089', '8087'],
  },
  {
    id: 'tak.remote.useTls',
    slot: 'TAK',
    labelKey: 'takServerPanel.remoteUseTls',
    sectionKey: REMOTE,
    keywords: ['tak server', 'ssl', 'encryption'],
  },
  {
    id: 'tak.remote.verifyServer',
    slot: 'TAK',
    labelKey: 'takServerPanel.remoteVerifyServer',
    sectionKey: REMOTE,
    keywords: ['tak server', 'certificate', 'verify', 'trust'],
  },
  {
    id: 'tak.remote.allowNameMismatch',
    slot: 'TAK',
    labelKey: 'takServerPanel.remoteAllowNameMismatch',
    sectionKey: REMOTE,
    keywords: ['tak server', 'hostname', 'certificate'],
  },
  {
    id: 'tak.remote.autoConnect',
    slot: 'TAK',
    labelKey: 'takServerPanel.remoteAutoConnect',
    sectionKey: REMOTE,
    keywords: ['tak server', 'startup', 'relay'],
  },
  {
    id: 'tak.remote.importCertificates',
    slot: 'TAK',
    labelKey: 'takServerPanel.remoteImport',
    sectionKey: REMOTE,
    keywords: ['tak server', 'p12', 'pkcs12', 'certificate', 'data package'],
  },
  {
    id: 'tak.remote.enroll',
    slot: 'TAK',
    labelKey: 'takServerPanel.remoteEnroll',
    sectionKey: REMOTE,
    keywords: ['tak server', 'enrollment', 'username', 'password', 'certificate'],
  },
  {
    id: 'tak.remote.connect',
    slot: 'TAK',
    labelKey: 'takServerPanel.remoteConnect',
    sectionKey: REMOTE,
    keywords: ['tak server', 'relay', 'disconnect'],
  },
  {
    id: 'tak.styles.sendUnmatched',
    slot: 'TAK',
    labelKey: 'takServerPanel.unitStylesSendUnmatched',
    sectionKey: STYLES,
    keywords: ['tak', 'cot', 'filter', 'relay', 'unmatched'],
  },
  {
    id: 'tak.styles.addFilter',
    slot: 'TAK',
    labelKey: 'takServerPanel.unitStylesAddFilter',
    sectionKey: STYLES,
    keywords: ['tak', 'cot', 'unit filter', 'icon', 'team color', 'role', 'k9', 'ems', 'callsign'],
  },
  {
    id: 'tak.channelRelay.trackers',
    slot: 'TAK',
    labelKey: 'takServerPanel.channelRelayTrackers',
    sectionKey: 'takServerPanel.channelRelayTitle',
    keywords: ['tak', 'meshcore', 'tracker', 'mt1', 'geochat', 'chat', 'channel', 'room'],
  },
];

export const takSurface: SettingsSearchSurface = {
  entries: takEntries,
  files: [
    { path: 'src/renderer/components/TakServerPanel.tsx', sweepAllKeys: true },
    { path: 'src/renderer/components/TakRemoteRelaySection.tsx', sweepAllKeys: true },
    { path: 'src/renderer/components/TakUnitFiltersSection.tsx', sweepAllKeys: true },
    { path: 'src/renderer/components/TakChannelRelaySection.tsx', sweepAllKeys: true },
  ],
  exempt: {
    'takServerPanel.title': 'panel heading; the launcher already lists the TAK panel',
    'takServerPanel.description': 'panel prose, no control',
    'takServerPanel.remoteDescription': 'section prose, no control',
    'takServerPanel.*Desc': 'description text; its control is indexed',
    'takServerPanel.*Hint': 'help text under an indexed row',
    'takServerPanel.*Warning': 'warning text, not a control',
    'takServerPanel.*Error': 'validation or status error text',
    'takServerPanel.*Needs*': 'precondition note under an indexed row',
    'takServerPanel.duration*': 'connected-client duration text',
    'takServerPanel.portClientsInfo*': 'server status text',
    'takServerPanel.running': 'server status text',
    'takServerPanel.stopped': 'server status text',
    'takServerPanel.starting': 'busy label of the indexed start/stop button',
    'takServerPanel.stopping': 'busy label of the indexed start/stop button',
    'takServerPanel.stopServer': 'running-state label of the indexed start/stop button',
    'takServerPanel.generating': 'busy label of the indexed data package button',
    'takServerPanel.packageSaved': 'success status of the indexed data package button',
    'takServerPanel.startServerFirst': 'precondition note under the indexed data package button',
    'takServerPanel.connectedClients': 'read-only connected-client list heading',
    'takServerPanel.no*': 'empty-state text of a read-only list',
    'takServerPanel.atakPlugin*': 'read-only ATAK plugin message list',
    'takServerPanel.atakUndecodable': 'read-only ATAK plugin message list text',
    'takServerPanel.packets': 'read-only ATAK plugin message list text',
    'takServerPanel.lastText': 'read-only ATAK plugin message list text',
    'takServerPanel.remoteConnected': 'remote relay status text',
    'takServerPanel.remoteConnecting': 'remote relay status text',
    'takServerPanel.remoteDisconnected': 'remote relay status text',
    'takServerPanel.remoteDisconnect': 'active-state label of the indexed remote connect button',
    'takServerPanel.remote*Summary': 'imported credential status text',
    'takServerPanel.remoteNo*': 'imported credential status text',
    'takServerPanel.remoteCertificates': 'sub-heading; its import and enroll rows are indexed',
    'takServerPanel.remotePasswordLabel': 'password field of the indexed certificate import row',
    'takServerPanel.remoteClear': 'clear button grouped with the indexed certificate import row',
    'takServerPanel.remoteEnroll*': 'fields and notes of the indexed certificate enrollment row',
    'takServerPanel.unitStylesTitle': 'section heading; its rows are indexed',
    'takServerPanel.unitStylesSave*': 'save button and status for the indexed unit filter rows',
    'takServerPanel.unitStylesPreview*': 'name tester for the indexed unit filters, not a setting',
    'takServerPanel.unitFilter*': 'fields of a filter row added by the indexed Add filter control',
    'takServerPanel.channelRelayTitle': 'section heading; its channel rows are indexed',
    'takServerPanel.channelRelayRoom*': 'GeoChat room field in each indexed channel row',
    'takServerPanel.channelRelayUnnamed': 'fallback channel name in a row',
    'takServerPanel.channelRelayNoChannels': 'empty-state text before a radio lists channels',
  },
};
