import { existsSync, readdirSync, readFileSync } from 'fs';
import { join, relative } from 'path';

export interface BrokenDocLink {
  sourceFile: string;
  line: number;
  urlOrTarget: string;
  resolvedPath: string;
}

interface DocLinkMatch {
  index: number;
  raw: string;
  /** Repo-relative path of the linked file. */
  target: string;
  /** Heading anchor to verify (docs-site links only). */
  anchor?: string;
}

const MESH_CLIENT_BLOB_RE =
  /https:\/\/github\.com\/charlottemeshtastic\/mesh-client\/blob\/main\/([^\s"'#)]+)/g;

const RELATIVE_DOC_LINK_RE = /\]\((docs\/[^)#]+\.md)/g;

const DOCS_SITE_LINK_RE =
  /https:\/\/charlottemeshtastic\.github\.io\/mesh-client\/([a-z0-9-]*)\/?([#A-Za-z0-9_-]*)/g;

/** Docs-site pages generated by `scripts/prepare-mkdocs.mjs` (gitignored, so not on disk in a clean checkout). */
const GENERATED_SITE_PAGES: ReadonlySet<string> = new Set(['contributing', 'install', 'features']);

const ROOT_MARKDOWN = ['README.md', 'AGENTS.md', 'ARCHITECTURE.md', 'CONTRIBUTING.md'] as const;

/** Non-markdown release artifacts that link to the docs (macOS install notice, release notes). */
const EXTRA_SCAN_FILES = [
  'scripts/macos-install-notice.mjs',
  'scripts/release.sh',
  'resources/macos/IMPORTANT-macOS-install.txt',
] as const;

function collectFilesRecursive(dir: string, extensions: string[]): string[] {
  const results: string[] = [];
  if (!existsSync(dir)) return results;
  for (const ent of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, ent.name);
    if (ent.isDirectory()) {
      results.push(...collectFilesRecursive(full, extensions));
    } else if (extensions.some((ext) => ent.name.endsWith(ext))) {
      results.push(full);
    }
  }
  return results;
}

function collectScanFiles(repoRoot: string): string[] {
  const files: string[] = [];

  files.push(...collectFilesRecursive(join(repoRoot, 'src/renderer'), ['.ts', '.tsx']));
  files.push(...collectFilesRecursive(join(repoRoot, 'src/main'), ['.ts']));

  for (const name of [...ROOT_MARKDOWN, ...EXTRA_SCAN_FILES]) {
    const path = join(repoRoot, name);
    if (existsSync(path)) files.push(path);
  }

  files.push(...collectFilesRecursive(join(repoRoot, 'docs'), ['.md']));
  files.push(...collectFilesRecursive(join(repoRoot, '.github'), ['.md']));

  return files;
}

function lineNumberAt(content: string, index: number): number {
  let line = 1;
  for (let i = 0; i < index; i++) {
    if (content[i] === '\n') line++;
  }
  return line;
}

/** Map a docs-site page slug (`troubleshooting`, `` for the home page) to its `docs/*.md` source. */
export function docsSitePageToRepoPath(page: string): string {
  return `docs/${page === '' ? 'index' : page}.md`;
}

/** GitHub / MkDocs (`pymdownx.slugs`) heading slug: lowercase, drop punctuation, spaces to hyphens. */
export function githubHeadingSlug(heading: string): string {
  return heading
    .trim()
    .toLowerCase()
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
    .replace(/[^\p{L}\p{N}\s_-]/gu, '')
    .replace(/\s/g, '-');
}

/** Heading anchors defined by a markdown file (outside fenced code blocks). */
export function markdownHeadingAnchors(markdown: string): Set<string> {
  const anchors = new Set<string>();
  const seen = new Map<string, number>();
  let inFence = false;
  for (const line of markdown.split('\n')) {
    if (/^\s*(```|~~~)/.test(line)) inFence = !inFence;
    if (inFence) continue;
    const match = /^#{1,6} (.*)$/.exec(line);
    const text = match?.at(1);
    if (text === undefined) continue;
    const base = githubHeadingSlug(text);
    const count = seen.get(base) ?? 0;
    seen.set(base, count + 1);
    anchors.add(count === 0 ? base : `${base}-${count}`);
  }
  return anchors;
}

function findDocLinkMatches(content: string): DocLinkMatch[] {
  const matches: DocLinkMatch[] = [];
  let match: RegExpExecArray | null;

  MESH_CLIENT_BLOB_RE.lastIndex = 0;
  while ((match = MESH_CLIENT_BLOB_RE.exec(content)) !== null) {
    const target = match.at(1);
    if (target !== undefined) matches.push({ index: match.index, raw: match[0], target });
  }

  RELATIVE_DOC_LINK_RE.lastIndex = 0;
  while ((match = RELATIVE_DOC_LINK_RE.exec(content)) !== null) {
    const target = match.at(1);
    if (target !== undefined) {
      matches.push({ index: match.index, raw: `](${target})`, target });
    }
  }

  DOCS_SITE_LINK_RE.lastIndex = 0;
  while ((match = DOCS_SITE_LINK_RE.exec(content)) !== null) {
    const page = match.at(1) ?? '';
    const fragment = match.at(2) ?? '';
    const anchor = fragment.startsWith('#') && fragment.length > 1 ? fragment.slice(1) : undefined;
    matches.push({
      index: match.index,
      raw: match[0],
      target: docsSitePageToRepoPath(page),
      ...(anchor !== undefined ? { anchor } : {}),
    });
  }

  return matches;
}

/** Extract repo-relative doc paths from blob URLs, docs-site URLs, and `](docs/...)` markdown links. */
export function extractDocLinkTargets(content: string): string[] {
  return findDocLinkMatches(content)
    .sort((a, b) => a.index - b.index)
    .map((m) => m.target);
}

function isGeneratedSitePage(target: string): boolean {
  const page = /^docs\/([a-z0-9-]+)\.md$/.exec(target)?.at(1);
  return page !== undefined && GENERATED_SITE_PAGES.has(page);
}

/**
 * Returns doc links in scanned sources whose target file is missing from the repo,
 * or (for docs-site URLs) whose `#anchor` is not a heading in the target page.
 */
export function findBrokenDocLinks(repoRoot: string): BrokenDocLink[] {
  const broken: BrokenDocLink[] = [];
  const anchorCache = new Map<string, Set<string>>();

  const anchorsFor = (target: string): Set<string> => {
    let anchors = anchorCache.get(target);
    if (anchors === undefined) {
      anchors = markdownHeadingAnchors(readFileSync(join(repoRoot, target), 'utf8'));
      anchorCache.set(target, anchors);
    }
    return anchors;
  };

  for (const sourceFile of collectScanFiles(repoRoot)) {
    const content = readFileSync(sourceFile, 'utf8');
    const relSource = relative(repoRoot, sourceFile);

    for (const link of findDocLinkMatches(content)) {
      if (isGeneratedSitePage(link.target)) continue;
      const exists = existsSync(join(repoRoot, link.target));
      const anchorMissing =
        exists && link.anchor !== undefined && !anchorsFor(link.target).has(link.anchor);
      if (!exists || anchorMissing) {
        broken.push({
          sourceFile: relSource,
          line: lineNumberAt(content, link.index),
          urlOrTarget: link.raw,
          resolvedPath: link.anchor !== undefined ? `${link.target}#${link.anchor}` : link.target,
        });
      }
    }
  }

  return broken;
}
