#!/usr/bin/env node
/**
 * Generate docs-site pages that are derived from root markdown, so README /
 * CONTRIBUTING stay the single source of truth:
 *   CONTRIBUTING.md                      -> docs/contributing.md
 *   README.md docs-site:install markers  -> docs/install.md
 *   README.md docs-site:features markers -> docs/features.md (+ limitations)
 * Generated files are gitignored. Run before `mkdocs build|serve`
 * (scripts/run-mkdocs.mjs and .github/workflows/docs.yml both do).
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

export const REPO_BLOB_BASE = 'https://github.com/Colorado-Mesh/mesh-client/blob/main/';

const GENERATED_NOTICE = (source) =>
  `<!-- Generated by scripts/prepare-mkdocs.mjs from ${source}; edit the source file, not this one. -->`;

/** Remove HTML tags, repeating until stable so nested input like `<scr<b>ipt>` cannot survive. */
function stripHtmlTags(text) {
  let previous;
  let current = text;
  do {
    previous = current;
    current = current.replace(/<[^<>]*>/g, '');
  } while (current !== previous);
  return current;
}

/** GitHub-compatible heading slug (lowercase, strip punctuation, spaces to hyphens; no collapsing). */
export function githubSlug(heading) {
  return stripHtmlTags(heading.trim().toLowerCase())
    .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')
    .replace(/[^\p{L}\p{N}\s_-]/gu, '')
    .replace(/\s/g, '-');
}

/** Anchors produced by markdown headings outside fenced code blocks. */
export function headingAnchors(markdown) {
  const anchors = new Set();
  const seen = new Map();
  let inFence = false;
  for (const line of markdown.split('\n')) {
    if (/^\s*(```|~~~)/.test(line)) inFence = !inFence;
    if (inFence) continue;
    const match = /^#{1,6} (.*)$/.exec(line);
    if (!match) continue;
    const base = githubSlug(match[1]);
    const count = seen.get(base) ?? 0;
    seen.set(base, count + 1);
    anchors.add(count === 0 ? base : `${base}-${count}`);
  }
  return anchors;
}

/** Text between `<!-- docs-site:<name>:start -->` and `<!-- docs-site:<name>:end -->`. */
export function extractMarkedSection(markdown, name) {
  const start = `<!-- docs-site:${name}:start -->`;
  const end = `<!-- docs-site:${name}:end -->`;
  const startIdx = markdown.indexOf(start);
  const endIdx = markdown.indexOf(end);
  if (startIdx === -1 || endIdx === -1 || endIdx < startIdx) {
    throw new Error(`prepare-mkdocs: missing or misordered docs-site:${name} markers`);
  }
  return markdown.slice(startIdx + start.length, endIdx).trim();
}

/** Raise every heading outside code fences by `levels` (### -> ## for levels=1). */
export function promoteHeadings(markdown, levels = 1) {
  let inFence = false;
  return markdown
    .split('\n')
    .map((line) => {
      if (/^\s*(```|~~~)/.test(line)) inFence = !inFence;
      if (inFence) return line;
      const match = /^(#{2,6}) /.exec(line);
      if (!match) return line;
      const depth = Math.max(1, match[1].length - levels);
      return `${'#'.repeat(depth)}${line.slice(match[1].length)}`;
    })
    .join('\n');
}

function rewriteTarget(target, { sourceFile, pageAnchors }) {
  if (/^[a-z][a-z0-9+.-]*:/i.test(target)) return target;
  if (target.startsWith('#')) {
    return pageAnchors.has(target.slice(1)) ? target : `${REPO_BLOB_BASE}${sourceFile}${target}`;
  }
  const path = target.replace(/^\.\//, '');
  if (path.startsWith('docs/') && !path.startsWith('docs/agents/')) {
    return path.slice('docs/'.length);
  }
  if (path === 'CONTRIBUTING.md' || path.startsWith('CONTRIBUTING.md#')) {
    return path.replace('CONTRIBUTING.md', 'contributing.md');
  }
  return `${REPO_BLOB_BASE}${path}`;
}

/**
 * Rewrite links in root-level markdown so they resolve on the docs site:
 * `docs/x.md` -> `x.md`, CONTRIBUTING -> contributing.md, in-page anchors that
 * are not on the generated page -> GitHub, everything else repo-relative -> GitHub.
 */
export function rewriteRootLinksForSite(markdown, { sourceFile, pageAnchors = new Set() }) {
  const opts = { sourceFile, pageAnchors };
  return markdown
    .replace(/\]\(([^)\s]+)/g, (_whole, target) => `](${rewriteTarget(target, opts)}`)
    .replace(/(src|href)="([^"]+)"/g, (_whole, attr, target) => {
      return `${attr}="${rewriteTarget(target, opts)}"`;
    });
}

function buildPage({ title, intro, body, sourceFile }) {
  const page = [GENERATED_NOTICE(sourceFile), '', `# ${title}`, '', intro, '', body, ''].join('\n');
  return rewriteRootLinksForSite(page, { sourceFile, pageAnchors: headingAnchors(page) });
}

export function buildInstallPage(readme) {
  return buildPage({
    title: 'Install',
    intro:
      'Download a release build for your platform. To build from source instead, see the [Development Guide](docs/development-environment.md).',
    body: promoteHeadings(extractMarkedSection(readme, 'install')),
    sourceFile: 'README.md',
  });
}

export function buildFeaturesPage(readme) {
  const features = promoteHeadings(extractMarkedSection(readme, 'features'));
  const limitations = extractMarkedSection(readme, 'limitations');
  return buildPage({
    title: 'Features',
    intro:
      'What Mesh-Client does on each protocol. New to the terms? See the [Glossary](docs/glossary.md).',
    body: `${features}\n\n## Limitations\n\n${limitations}`,
    sourceFile: 'README.md',
  });
}

export function buildContributingPage(contributing) {
  const page = [GENERATED_NOTICE('CONTRIBUTING.md'), '', contributing.trim(), ''].join('\n');
  return rewriteRootLinksForSite(page, {
    sourceFile: 'CONTRIBUTING.md',
    pageAnchors: headingAnchors(page),
  });
}

export function prepareMkdocs(repoRoot) {
  const read = (rel) => readFileSync(join(repoRoot, rel), 'utf8');
  const readme = read('README.md');
  const outputs = {
    'docs/contributing.md': buildContributingPage(read('CONTRIBUTING.md')),
    'docs/install.md': buildInstallPage(readme),
    'docs/features.md': buildFeaturesPage(readme),
  };
  for (const [rel, content] of Object.entries(outputs)) {
    writeFileSync(join(repoRoot, rel), content);
  }
  return Object.keys(outputs);
}

if (process.argv[1] && resolve(fileURLToPath(import.meta.url)) === resolve(process.argv[1])) {
  const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
  const written = prepareMkdocs(repoRoot);
  console.debug(`[prepare-mkdocs] wrote ${written.join(', ')}`);
}
