import { vi } from 'vitest';

import type { ElectronAPI, OutboxEntry, OutboxEntryInput } from '@/shared/electron-api.types';

const outboxMockRows: OutboxEntry[] = [];
let outboxMockIdSeq = 1;

/** Reset in-memory outbox rows between renderer-ui tests. */
export function resetElectronAPIOutboxMock(): void {
  outboxMockRows.length = 0;
  outboxMockIdSeq = 1;
}

function makeOutboxMockRow(entry: OutboxEntryInput): OutboxEntry {
  const now = Date.now();
  return {
    id: outboxMockIdSeq++,
    attemptCount: 0,
    createdAt: now,
    updatedAt: now,
    ...entry,
    priority: entry.priority === 'emergency' ? 'emergency' : 'normal',
  };
}

/** Full typed electronAPI stub for renderer-ui tests (extracted from setup for reuse). */
export function createElectronAPIMock(): ElectronAPI {
  return {
    translation: {
      getStatus: vi.fn().mockResolvedValue({
        enabled: false,
        packs: [],
        progress: [],
        diskBytes: 0,
        libre: { enabled: false, url: '', hasApiKey: false },
      }),
      setEnabled: vi.fn(),
      translate: vi.fn(),
      detect: vi.fn(),
      listPacks: vi.fn(),
      installPack: vi.fn(),
      cancelInstall: vi.fn(),
      deletePack: vi.fn(),
      removeAll: vi.fn(),
      setLibreConfig: vi.fn(),
      testLibreConfig: vi.fn(),
      onPackProgress: vi.fn().mockReturnValue(() => {}),
    },
    db: {
      saveMessage: vi.fn().mockResolvedValue(undefined),
      getMessages: vi.fn().mockResolvedValue([]),
      listMeshtasticDmPeers: vi.fn().mockResolvedValue([]),
      saveNode: vi.fn().mockResolvedValue(undefined),
      saveNodePath: vi.fn().mockResolvedValue(undefined),
      migrateMeshtasticNodeNum: vi.fn().mockResolvedValue({ migrated: false, messagesUpdated: 0 }),
      getNodes: vi.fn().mockResolvedValue([]),
      clearMessages: vi.fn().mockResolvedValue(undefined),
      clearNodes: vi.fn().mockResolvedValue(undefined),
      deleteNode: vi.fn().mockResolvedValue(undefined),
      updateMessageStatus: vi.fn().mockResolvedValue(undefined),
      exportDb: vi.fn().mockResolvedValue(undefined),
      importDb: vi.fn().mockResolvedValue(undefined),
      deleteNodesByAge: vi.fn().mockResolvedValue(0),
      deleteNodesNeverHeard: vi.fn().mockResolvedValue(0),
      pruneNodesByCount: vi.fn().mockResolvedValue({ changes: 0 }),
      pruneMessagesByCount: vi.fn().mockResolvedValue({ changes: 0 }),
      pruneMeshcoreMessagesByCount: vi.fn().mockResolvedValue({ changes: 0 }),
      deleteNodesBatch: vi.fn().mockResolvedValue(0),
      clearMessagesByChannel: vi.fn().mockResolvedValue(undefined),
      backfillChannelKeys: vi.fn().mockResolvedValue({ changes: 0 }),
      getMessageChannels: vi.fn().mockResolvedValue([]),
      setNodeFavorited: vi.fn().mockResolvedValue(undefined),
      getNodeNote: vi.fn().mockResolvedValue(null),
      setNodeNote: vi.fn().mockResolvedValue(undefined),
      deleteNodesBySource: vi.fn().mockResolvedValue(0),
      migrateRfStubNodes: vi.fn().mockResolvedValue(0),
      deleteNodesWithoutLongname: vi.fn().mockResolvedValue(0),
      prunePositionHistory: vi.fn().mockResolvedValue(0),
      prunePositionHistoryPerNode: vi.fn().mockResolvedValue(0),
      clearNodePositions: vi.fn().mockResolvedValue(undefined),
      updateMessageReceivedVia: vi.fn().mockResolvedValue(undefined),
      updateMessagePacketId: vi.fn().mockResolvedValue(undefined),
      getMeshcoreMessages: vi.fn().mockResolvedValue([]),
      listMeshcoreDmPeers: vi.fn().mockResolvedValue([]),
      getBlockedContacts: vi.fn().mockResolvedValue([]),
      blockContact: vi.fn().mockResolvedValue({ changes: 1 }),
      unblockContact: vi.fn().mockResolvedValue({ changes: 1 }),
      exportBlockedContacts: vi.fn().mockResolvedValue([]),
      importBlockedContacts: vi.fn().mockResolvedValue({ imported: 0, skipped: 0 }),
      searchMessages: vi.fn().mockResolvedValue([]),
      searchMeshcoreMessages: vi.fn().mockResolvedValue([]),
      getMeshcoreContacts: vi.fn().mockResolvedValue([]),
      saveMeshcoreMessage: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreMessageSender: vi.fn().mockResolvedValue(undefined),
      saveMeshcoreContact: vi.fn().mockResolvedValue(undefined),
      saveMeshcoreContactsBatch: vi.fn().mockResolvedValue(0),
      updateMeshcoreContactRfTransport: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreContactAdvert: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreContactType: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreContactLastRf: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreMessageStatus: vi.fn().mockResolvedValue(undefined),
      deleteFailedOutboundMessage: vi.fn().mockResolvedValue({ changes: 0 }),
      updateMeshcoreMessageStatusByKey: vi.fn().mockResolvedValue({ changes: 1 }),
      deleteMeshcoreContact: vi.fn().mockResolvedValue(undefined),
      clearMeshcoreMessages: vi.fn().mockResolvedValue(undefined),
      getMeshcoreMessageChannels: vi.fn().mockResolvedValue([]),
      clearMeshcoreMessagesByChannel: vi.fn().mockResolvedValue(undefined),
      clearMeshcoreContacts: vi.fn().mockResolvedValue(undefined),
      deleteMeshcoreContactsNeverAdvertised: vi.fn().mockResolvedValue(0),
      deleteMeshcoreContactsByAge: vi.fn().mockResolvedValue(0),
      pruneMeshcoreContactsByCount: vi.fn().mockResolvedValue({ changes: 0 }),
      clearMeshcoreRepeaters: vi.fn().mockResolvedValue(undefined),
      markAllMeshcoreContactsOffRadio: vi.fn().mockResolvedValue(undefined),
      getMeshcoreContactCount: vi.fn().mockResolvedValue(0),
      deleteMeshcoreContactsWithoutPubkey: vi
        .fn()
        .mockResolvedValue({ deleted: 0, excludedStubCount: 0 }),
      offloadAllMeshcoreContacts: vi.fn().mockResolvedValue(0),
      markMeshcoreContactOffRadio: vi.fn().mockResolvedValue({ changes: 0 }),
      getMeshcoreContactById: vi.fn().mockResolvedValue(null),
      updateMeshcoreContactNickname: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreContactFavorited: vi.fn().mockResolvedValue(undefined),
      savePositionHistory: vi.fn().mockResolvedValue(undefined),
      getPositionHistory: vi.fn().mockResolvedValue([]),
      clearPositionHistory: vi.fn().mockResolvedValue(undefined),
      saveEnvironmentTelemetry: vi.fn().mockResolvedValue({ changes: 1 }),
      getEnvironmentTelemetry: vi.fn().mockResolvedValue([]),
      clearEnvironmentTelemetry: vi.fn().mockResolvedValue({ changes: 0 }),
      pruneEnvironmentTelemetry: vi.fn().mockResolvedValue(0),
      saveMeshcoreHopHistory: vi.fn().mockResolvedValue(true),
      getMeshcoreHopHistory: vi.fn().mockResolvedValue(null),
      getAllMeshcoreHopHistory: vi.fn().mockResolvedValue([]),
      saveMeshcoreTraceHistory: vi.fn().mockResolvedValue(true),
      getMeshcoreTraceHistory: vi.fn().mockResolvedValue([]),
      pruneMeshcorePathHistory: vi.fn().mockResolvedValue(true),
      upsertMeshcorePathHistory: vi.fn().mockResolvedValue(true),
      recordMeshcorePathOutcome: vi.fn().mockResolvedValue(true),
      getMeshcorePathHistory: vi.fn().mockResolvedValue([]),
      getAllMeshcorePathHistory: vi.fn().mockResolvedValue([]),
      deleteMeshcorePathHistoryForNode: vi.fn().mockResolvedValue(true),
      deleteAllMeshcorePathHistory: vi.fn().mockResolvedValue(true),
      getContactGroups: vi.fn().mockResolvedValue([]),
      createContactGroup: vi.fn().mockResolvedValue(1),
      updateContactGroup: vi.fn().mockResolvedValue(undefined),
      deleteContactGroup: vi.fn().mockResolvedValue(undefined),
      addContactToGroup: vi.fn().mockResolvedValue(undefined),
      removeContactFromGroup: vi.fn().mockResolvedValue(undefined),
      getContactGroupMembers: vi.fn().mockResolvedValue([]),
    },
    mqtt: {
      connect: vi.fn().mockResolvedValue(undefined),
      disconnect: vi.fn().mockResolvedValue(undefined),
      powerResume: vi.fn().mockResolvedValue(undefined),
      powerSuspend: vi.fn().mockResolvedValue(undefined),
      onStatus: vi.fn().mockReturnValue(() => {}),
      onError: vi.fn().mockReturnValue(() => {}),
      onWarning: vi.fn().mockReturnValue(() => {}),
      onNodeUpdate: vi.fn().mockReturnValue(() => {}),
      onMessage: vi.fn().mockReturnValue(() => {}),
      onBrokerRaw: vi.fn().mockReturnValue(() => {}),
      onTraceRouteReply: vi.fn().mockReturnValue(() => {}),
      onClientId: vi.fn().mockReturnValue(() => {}),
      getClientId: vi.fn().mockResolvedValue(''),
      getCachedNodes: vi.fn().mockResolvedValue([]),
      getChannelNameToIndex: vi.fn().mockResolvedValue({}),
      updateChannelKeys: vi.fn().mockResolvedValue(undefined),
      updateTopicPrefix: vi.fn().mockResolvedValue(undefined),
      publish: vi.fn().mockResolvedValue(1),
      publishProxy: vi.fn().mockResolvedValue(undefined),
      publishNodeInfo: vi.fn().mockResolvedValue(1),
      publishPosition: vi.fn().mockResolvedValue(1),
      publishWaypoint: vi.fn().mockResolvedValue(1),
      publishMeshcore: vi.fn().mockResolvedValue(undefined),
      publishMeshcorePacketLog: vi.fn().mockResolvedValue(undefined),
      onMeshcoreChat: vi.fn().mockReturnValue(() => {}),
      refreshMeshcoreToken: vi.fn().mockResolvedValue(null),
      updateMeshcoreToken: vi.fn().mockResolvedValue(undefined),
      onRequestTokenRefresh: vi.fn().mockReturnValue(() => {}),
    },
    onGattAdapterState: vi.fn().mockReturnValue(() => {}),
    onGattDeviceDiscovered: vi.fn().mockReturnValue(() => {}),
    onGattLinkRssi: vi.fn().mockReturnValue(() => {}),
    onGattConnected: vi.fn().mockReturnValue(() => {}),
    onGattDisconnected: vi.fn().mockReturnValue(() => {}),
    onGattConnectAborted: vi.fn().mockReturnValue(() => {}),
    onGattIssue: vi.fn().mockReturnValue(() => {}),
    onGattFromRadio: vi.fn().mockReturnValue(() => {}),
    startGattScanning: vi.fn().mockResolvedValue({ ok: true }),
    stopGattScanning: vi.fn().mockResolvedValue(undefined),
    connectGatt: vi.fn().mockResolvedValue({ ok: true }),
    disconnectGatt: vi.fn().mockResolvedValue(undefined),
    releaseGattBleCentral: vi.fn().mockResolvedValue(undefined),
    clearGattBondRecoveryExclusive: vi.fn().mockResolvedValue(undefined),
    isGattConnected: vi.fn().mockResolvedValue(true),
    gattToRadio: vi.fn().mockResolvedValue(undefined),
    gattPairState: vi.fn().mockResolvedValue({ ok: false, code: 'unsupported', error: 'mock' }),
    gattPair: vi.fn().mockResolvedValue({ ok: false, code: 'unsupported', error: 'mock' }),
    gattUnpair: vi.fn().mockResolvedValue({ ok: false, code: 'unsupported', error: 'mock' }),
    onSerialPortsDiscovered: vi.fn().mockReturnValue(() => {}),
    selectSerialPort: vi.fn(),
    cancelSerialSelection: vi.fn(),
    bluetoothUnpair: vi.fn().mockResolvedValue(undefined),
    bluetoothStartScan: vi.fn().mockResolvedValue(undefined),
    bluetoothStopScan: vi.fn().mockResolvedValue(undefined),
    bluetoothPair: vi.fn().mockResolvedValue(undefined),
    bluetoothConnect: vi.fn().mockResolvedValue(undefined),
    bluetoothUntrust: vi.fn().mockResolvedValue(undefined),
    bluetoothGetInfo: vi.fn().mockResolvedValue(''),
    onBluetoothPinRequired: vi.fn().mockReturnValue(() => {}),
    provideBluetoothPin: vi.fn(),
    cancelBluetoothPairing: vi.fn(),
    resetBlePairingRetryCount: vi.fn(),
    clearSessionData: vi.fn().mockResolvedValue(undefined),
    getGpsFix: vi.fn().mockResolvedValue({ lat: 0, lon: 0, source: 'ip' }),
    update: {
      check: vi.fn().mockResolvedValue(undefined),
      download: vi.fn().mockResolvedValue(undefined),
      install: vi.fn().mockResolvedValue(undefined),
      openReleases: vi.fn().mockResolvedValue(undefined),
      onAvailable: vi.fn().mockReturnValue(() => {}),
      onNotAvailable: vi.fn().mockReturnValue(() => {}),
      onChecking: vi.fn().mockReturnValue(() => {}),
      onProgress: vi.fn().mockReturnValue(() => {}),
      onDownloaded: vi.fn().mockReturnValue(() => {}),
      onError: vi.fn().mockReturnValue(() => {}),
      onOffline: vi.fn().mockReturnValue(() => {}),
    },
    serviceAnnouncements: {
      fetch: vi.fn().mockResolvedValue({ status: 'ok', announcements: [] }),
      openUrl: vi.fn().mockResolvedValue(true),
    },
    offlineMaps: {
      estimate: vi.fn().mockResolvedValue({ tileCount: 0, sizeEstimateBytes: 0, withinCaps: true }),
      download: vi.fn().mockResolvedValue({ jobId: 'test-job' }),
      cancel: vi.fn().mockResolvedValue({ cancelled: true }),
      status: vi.fn().mockResolvedValue({
        activeJobs: [],
        stats: { tileCount: 0, diskBytes: 0 },
        regions: [],
        sources: {},
      }),
      clear: vi.fn().mockResolvedValue({ ok: true }),
      onProgress: vi.fn().mockReturnValue(() => {}),
      onDone: vi.fn().mockReturnValue(() => {}),
      onError: vi.fn().mockReturnValue(() => {}),
    },
    notifyDeviceConnected: vi.fn(),
    notifyDeviceDisconnected: vi.fn(),
    setTrayUnread: vi.fn(),
    quitApp: vi.fn().mockResolvedValue(undefined),
    restartApp: vi.fn().mockResolvedValue(undefined),
    notify: {
      show: vi.fn().mockResolvedValue(undefined),
    },
    getPlatform: vi.fn().mockReturnValue('linux'),
    showEmojiPanel: vi.fn().mockResolvedValue(undefined),
    media: {
      ensureMicrophoneAccess: vi.fn().mockResolvedValue({ granted: true, status: 'granted' }),
      ensureCameraAccess: vi.fn().mockResolvedValue({ granted: true, status: 'granted' }),
    },
    clipboard: {
      writeText: vi.fn().mockResolvedValue(undefined),
    },
    safeStorage: {
      encrypt: vi.fn().mockResolvedValue(null),
      decrypt: vi.fn().mockResolvedValue(null),
      isAvailable: vi.fn().mockResolvedValue(false),
    },
    notificationSounds: {
      choose: vi.fn().mockResolvedValue(null),
      save: vi.fn().mockResolvedValue({ id: 'a'.repeat(64), name: 'tone.wav' }),
      read: vi.fn().mockResolvedValue(null),
    },
    appSettings: {
      getLoginItem: vi.fn().mockResolvedValue({ openAtLogin: false }),
      setLoginItem: vi.fn().mockResolvedValue(undefined),
      getAll: vi.fn().mockResolvedValue({}),
      set: vi.fn().mockResolvedValue({ changes: 1 }),
    },
    onPowerSuspend: vi.fn().mockReturnValue(() => {}),
    onPowerResume: vi.fn().mockReturnValue(() => {}),
    sendRendererHeartbeat: vi.fn().mockResolvedValue(undefined),
    getProcessUptimeSec: vi.fn().mockResolvedValue(0),
    app: {
      getRendererLiveness: vi.fn().mockResolvedValue({
        mainUptimeSec: 0,
        lastRendererHeartbeatAgeMs: null,
        rendererUnresponsiveSeen: false,
        rss: 0,
        heapUsed: 0,
      }),
      focusWindow: vi.fn().mockResolvedValue(undefined),
      requestAttention: vi.fn().mockResolvedValue(undefined),
    },
    onSpellcheckReplace: vi.fn().mockReturnValue(() => {}),
    meshcore: {
      tcp: {
        connect: vi.fn().mockResolvedValue(undefined),
        write: vi.fn().mockResolvedValue(undefined),
        disconnect: vi.fn().mockResolvedValue(undefined),
        onData: vi.fn().mockReturnValue(() => {}),
        onDisconnected: vi.fn().mockReturnValue(() => {}),
      },
      openJsonFile: vi.fn().mockResolvedValue(null),
    },
    http: {
      preflight: vi.fn().mockResolvedValue(undefined),
      connect: vi.fn().mockResolvedValue(undefined),
      write: vi.fn().mockResolvedValue(undefined),
      disconnect: vi.fn().mockResolvedValue(undefined),
      onData: vi.fn().mockReturnValue(() => {}),
    },
    hostLink: {
      probeHttpRtt: vi.fn().mockResolvedValue(null),
      probeTcpRtt: vi.fn().mockResolvedValue(null),
      getSessionMeter: vi.fn().mockResolvedValue(null),
    },
    meshtastic: {
      tcp: {
        connect: vi.fn().mockResolvedValue(undefined),
        write: vi.fn().mockResolvedValue(undefined),
        disconnect: vi.fn().mockResolvedValue(undefined),
        onData: vi.fn().mockReturnValue(() => {}),
        onDisconnected: vi.fn().mockReturnValue(() => {}),
      },
    },
    chat: {
      export: vi.fn().mockResolvedValue({ success: false }),
      linkPreview: {
        fetch: vi.fn().mockResolvedValue(null),
      },
      outbox: {
        list: vi
          .fn()
          .mockImplementation((protocol: string) =>
            Promise.resolve(outboxMockRows.filter((r) => r.protocol === protocol)),
          ),
        add: vi.fn().mockImplementation((entry: OutboxEntryInput) => {
          const row = makeOutboxMockRow(entry);
          outboxMockRows.push(row);
          return Promise.resolve(row);
        }),
        updateStatus: vi
          .fn()
          .mockImplementation(
            (
              id: number,
              status: OutboxEntry['status'],
              error?: string,
              nextRetryAt?: number | null,
              attemptCount?: number,
            ) => {
              const row = outboxMockRows.find((r) => r.id === id);
              if (row) {
                row.status = status;
                if (error !== undefined) row.error = error ?? null;
                if (nextRetryAt !== undefined) row.nextRetryAt = nextRetryAt ?? null;
                if (attemptCount !== undefined) row.attemptCount = attemptCount;
                row.updatedAt = Date.now();
              }
              return Promise.resolve(undefined);
            },
          ),
        remove: vi.fn().mockImplementation((id: number) => {
          const idx = outboxMockRows.findIndex((r) => r.id === id);
          if (idx >= 0) outboxMockRows.splice(idx, 1);
          return Promise.resolve(undefined);
        }),
      },
    },
    meshtasticXmodem: {
      pickUploadFile: vi.fn().mockResolvedValue(null),
      saveDownloadFile: vi.fn().mockResolvedValue({ success: false }),
    },
    support: {
      exportBundle: vi.fn().mockResolvedValue(null),
    },
    log: {
      getPath: vi.fn().mockResolvedValue('/tmp/test.log'),
      getRecentLines: vi.fn().mockResolvedValue([]),
      clear: vi.fn().mockResolvedValue(undefined),
      export: vi.fn().mockResolvedValue(null),
      onLine: vi.fn().mockReturnValue(() => {}),
      logDeviceConnection: vi.fn().mockResolvedValue(undefined),
    },
    tak: {
      start: vi.fn().mockResolvedValue(undefined),
      stop: vi.fn().mockResolvedValue(undefined),
      getStatus: vi.fn().mockResolvedValue({ running: false, port: 8089, clientCount: 0 }),
      getConnectedClients: vi.fn().mockResolvedValue([]),
      generateDataPackage: vi.fn().mockResolvedValue(undefined),
      regenerateCertificates: vi.fn().mockResolvedValue(undefined),
      pushNodeUpdates: vi.fn().mockResolvedValue(undefined),
      onStatus: vi.fn().mockReturnValue(() => {}),
      onClientConnected: vi.fn().mockReturnValue(() => {}),
      onClientDisconnected: vi.fn().mockReturnValue(() => {}),
      onClientUpdated: vi.fn().mockReturnValue(() => {}),
      getContacts: vi.fn().mockResolvedValue([]),
      onContacts: vi.fn().mockReturnValue(() => {}),
      remoteStart: vi.fn().mockResolvedValue(undefined),
      remoteStop: vi.fn().mockResolvedValue(undefined),
      remoteGetStatus: vi.fn().mockResolvedValue({ state: 'disconnected', host: '', port: 8089 }),
      remoteGetSettings: vi.fn().mockResolvedValue(null),
      remoteGetCredentials: vi.fn().mockResolvedValue({ caSubjects: [] }),
      remoteImportCredentials: vi.fn().mockResolvedValue(null),
      remoteEnroll: vi.fn().mockResolvedValue({ caSubjects: [] }),
      remoteClearCredentials: vi.fn().mockResolvedValue({ caSubjects: [] }),
      onRemoteStatus: vi.fn().mockReturnValue(() => {}),
      getStyleSettings: vi.fn().mockResolvedValue({ filters: [], sendUnmatched: true }),
      setStyleSettings: vi.fn().mockImplementation((s: unknown) => Promise.resolve(s)),
      pushChatMessage: vi.fn().mockResolvedValue(undefined),
    },
    bleCoexistence: {
      register: vi.fn().mockResolvedValue({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      unregister: vi.fn().mockResolvedValue({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      assertCanConnect: vi.fn().mockResolvedValue({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      getState: vi.fn().mockResolvedValue({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
      acquireScan: vi.fn().mockResolvedValue({
        ok: true,
        connections: [],
        scanOwner: 'gatt',
        nobleYieldDecisionPending: false,
      }),
      releaseScan: vi.fn().mockResolvedValue({
        connections: [],
        scanOwner: null,
        nobleYieldDecisionPending: false,
      }),
    },
    deepLink: {
      onOpenUrl: vi.fn().mockReturnValue(() => {}),
    },
    geo: {
      resolvePlace: vi.fn().mockResolvedValue(null),
    },
    gps: {
      exportGpx: vi.fn().mockResolvedValue({ success: false, reason: 'cancelled' }),
    },
    mecp: {
      appendReceived: vi.fn().mockResolvedValue({ ok: true }),
      exportReceivedLog: vi.fn().mockResolvedValue({ success: false }),
    },
  } satisfies ElectronAPI;
}
