import { vi } from 'vitest';

import type { ElectronAPI } from '@/shared/electron-api.types';

/** Full typed electronAPI stub for renderer-ui tests (extracted from setup for reuse). */
export function createElectronAPIMock(): ElectronAPI {
  return {
    db: {
      saveMessage: vi.fn().mockResolvedValue(undefined),
      getMessages: vi.fn().mockResolvedValue([]),
      saveNode: vi.fn().mockResolvedValue(undefined),
      saveNodePath: vi.fn().mockResolvedValue(undefined),
      getNodes: vi.fn().mockResolvedValue([]),
      clearMessages: vi.fn().mockResolvedValue(undefined),
      clearNodes: vi.fn().mockResolvedValue(undefined),
      deleteNode: vi.fn().mockResolvedValue(undefined),
      updateMessageStatus: vi.fn().mockResolvedValue(undefined),
      exportDb: vi.fn().mockResolvedValue(undefined),
      importDb: vi.fn().mockResolvedValue(undefined),
      deleteNodesByAge: vi.fn().mockResolvedValue(0),
      deleteNodesNeverHeard: vi.fn().mockResolvedValue(0),
      pruneNodesByCount: vi.fn().mockResolvedValue({ changes: 0 }),
      pruneMessagesByCount: vi.fn().mockResolvedValue({ changes: 0 }),
      pruneMeshcoreMessagesByCount: vi.fn().mockResolvedValue({ changes: 0 }),
      deleteNodesBatch: vi.fn().mockResolvedValue(0),
      clearMessagesByChannel: vi.fn().mockResolvedValue(undefined),
      getMessageChannels: vi.fn().mockResolvedValue([]),
      setNodeFavorited: vi.fn().mockResolvedValue(undefined),
      getNodeNote: vi.fn().mockResolvedValue(null),
      setNodeNote: vi.fn().mockResolvedValue(undefined),
      deleteNodesBySource: vi.fn().mockResolvedValue(0),
      migrateRfStubNodes: vi.fn().mockResolvedValue(0),
      deleteNodesWithoutLongname: vi.fn().mockResolvedValue(0),
      prunePositionHistory: vi.fn().mockResolvedValue(0),
      prunePositionHistoryPerNode: vi.fn().mockResolvedValue(0),
      clearNodePositions: vi.fn().mockResolvedValue(undefined),
      updateMessageReceivedVia: vi.fn().mockResolvedValue(undefined),
      updateMessagePacketId: vi.fn().mockResolvedValue(undefined),
      getMeshcoreMessages: vi.fn().mockResolvedValue([]),
      getReticulumMessages: vi.fn().mockResolvedValue([]),
      searchReticulumMessages: vi.fn().mockResolvedValue([]),
      deleteReticulumMessage: vi.fn().mockResolvedValue({ changes: 1 }),
      saveReticulumMessage: vi.fn().mockResolvedValue(undefined),
      getReticulumDestinations: vi.fn().mockResolvedValue([]),
      upsertReticulumDestination: vi.fn().mockResolvedValue(undefined),
      searchMessages: vi.fn().mockResolvedValue([]),
      searchMeshcoreMessages: vi.fn().mockResolvedValue([]),
      getMeshcoreContacts: vi.fn().mockResolvedValue([]),
      saveMeshcoreMessage: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreMessageSender: vi.fn().mockResolvedValue(undefined),
      saveMeshcoreContact: vi.fn().mockResolvedValue(undefined),
      saveMeshcoreContactsBatch: vi.fn().mockResolvedValue(0),
      updateMeshcoreContactRfTransport: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreContactAdvert: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreContactType: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreContactLastRf: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreMessageStatus: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreMessageStatusByKey: vi.fn().mockResolvedValue({ changes: 1 }),
      deleteMeshcoreContact: vi.fn().mockResolvedValue(undefined),
      clearMeshcoreMessages: vi.fn().mockResolvedValue(undefined),
      getMeshcoreMessageChannels: vi.fn().mockResolvedValue([]),
      clearMeshcoreMessagesByChannel: vi.fn().mockResolvedValue(undefined),
      clearMeshcoreContacts: vi.fn().mockResolvedValue(undefined),
      deleteMeshcoreContactsNeverAdvertised: vi.fn().mockResolvedValue(0),
      deleteMeshcoreContactsByAge: vi.fn().mockResolvedValue(0),
      pruneMeshcoreContactsByCount: vi.fn().mockResolvedValue({ changes: 0 }),
      clearMeshcoreRepeaters: vi.fn().mockResolvedValue(undefined),
      markAllMeshcoreContactsOffRadio: vi.fn().mockResolvedValue(undefined),
      getMeshcoreContactCount: vi.fn().mockResolvedValue(0),
      deleteMeshcoreContactsWithoutPubkey: vi
        .fn()
        .mockResolvedValue({ deleted: 0, excludedStubCount: 0 }),
      offloadAllMeshcoreContacts: vi.fn().mockResolvedValue(0),
      getMeshcoreContactById: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreContactNickname: vi.fn().mockResolvedValue(undefined),
      updateMeshcoreContactFavorited: vi.fn().mockResolvedValue(undefined),
      savePositionHistory: vi.fn().mockResolvedValue(undefined),
      getPositionHistory: vi.fn().mockResolvedValue([]),
      clearPositionHistory: vi.fn().mockResolvedValue(undefined),
      saveMeshcoreHopHistory: vi.fn().mockResolvedValue(true),
      getMeshcoreHopHistory: vi.fn().mockResolvedValue(null),
      getAllMeshcoreHopHistory: vi.fn().mockResolvedValue([]),
      saveMeshcoreTraceHistory: vi.fn().mockResolvedValue(true),
      getMeshcoreTraceHistory: vi.fn().mockResolvedValue([]),
      pruneMeshcorePathHistory: vi.fn().mockResolvedValue(true),
      upsertMeshcorePathHistory: vi.fn().mockResolvedValue(true),
      recordMeshcorePathOutcome: vi.fn().mockResolvedValue(true),
      getMeshcorePathHistory: vi.fn().mockResolvedValue([]),
      getAllMeshcorePathHistory: vi.fn().mockResolvedValue([]),
      deleteMeshcorePathHistoryForNode: vi.fn().mockResolvedValue(true),
      deleteAllMeshcorePathHistory: vi.fn().mockResolvedValue(true),
      getContactGroups: vi.fn().mockResolvedValue([]),
      createContactGroup: vi.fn().mockResolvedValue(1),
      updateContactGroup: vi.fn().mockResolvedValue(undefined),
      deleteContactGroup: vi.fn().mockResolvedValue(undefined),
      addContactToGroup: vi.fn().mockResolvedValue(undefined),
      removeContactFromGroup: vi.fn().mockResolvedValue(undefined),
      getContactGroupMembers: vi.fn().mockResolvedValue([]),
    },
    mqtt: {
      connect: vi.fn().mockResolvedValue(undefined),
      disconnect: vi.fn().mockResolvedValue(undefined),
      powerResume: vi.fn().mockResolvedValue(undefined),
      powerSuspend: vi.fn().mockResolvedValue(undefined),
      onStatus: vi.fn().mockReturnValue(() => {}),
      onError: vi.fn().mockReturnValue(() => {}),
      onWarning: vi.fn().mockReturnValue(() => {}),
      onNodeUpdate: vi.fn().mockReturnValue(() => {}),
      onMessage: vi.fn().mockReturnValue(() => {}),
      onBrokerRaw: vi.fn().mockReturnValue(() => {}),
      onTraceRouteReply: vi.fn().mockReturnValue(() => {}),
      onClientId: vi.fn().mockReturnValue(() => {}),
      getClientId: vi.fn().mockResolvedValue(''),
      getCachedNodes: vi.fn().mockResolvedValue([]),
      updateChannelKeys: vi.fn().mockResolvedValue(undefined),
      publish: vi.fn().mockResolvedValue(1),
      publishProxy: vi.fn().mockResolvedValue(undefined),
      publishNodeInfo: vi.fn().mockResolvedValue(1),
      publishPosition: vi.fn().mockResolvedValue(1),
      publishWaypoint: vi.fn().mockResolvedValue(1),
      publishMeshcore: vi.fn().mockResolvedValue(undefined),
      publishMeshcorePacketLog: vi.fn().mockResolvedValue(undefined),
      onMeshcoreChat: vi.fn().mockReturnValue(() => {}),
      refreshMeshcoreToken: vi.fn().mockResolvedValue(null),
      updateMeshcoreToken: vi.fn().mockResolvedValue(undefined),
      onRequestTokenRefresh: vi.fn().mockReturnValue(() => {}),
    },
    onNobleBleAdapterState: vi.fn().mockReturnValue(() => {}),
    onNobleBleDeviceDiscovered: vi.fn().mockReturnValue(() => {}),
    onNobleBleConnected: vi.fn().mockReturnValue(() => {}),
    onNobleBleDisconnected: vi.fn().mockReturnValue(() => {}),
    onNobleBleConnectAborted: vi.fn().mockReturnValue(() => {}),
    onNobleBleFromRadio: vi.fn().mockReturnValue(() => {}),
    startNobleBleScanning: vi.fn().mockResolvedValue(undefined),
    stopNobleBleScanning: vi.fn().mockResolvedValue(undefined),
    connectNobleBle: vi.fn().mockResolvedValue({ ok: true }),
    disconnectNobleBle: vi.fn().mockResolvedValue(undefined),
    isNobleBleConnected: vi.fn().mockResolvedValue(true),
    nobleBleToRadio: vi.fn().mockResolvedValue(undefined),
    onSerialPortsDiscovered: vi.fn().mockReturnValue(() => {}),
    selectSerialPort: vi.fn(),
    cancelSerialSelection: vi.fn(),
    onBluetoothDevicesDiscovered: vi.fn().mockReturnValue(() => {}),
    selectBluetoothDevice: vi.fn(),
    cancelBluetoothSelection: vi.fn(),
    bluetoothUnpair: vi.fn().mockResolvedValue(undefined),
    bluetoothStartScan: vi.fn().mockResolvedValue(undefined),
    bluetoothStopScan: vi.fn().mockResolvedValue(undefined),
    bluetoothPair: vi.fn().mockResolvedValue(undefined),
    bluetoothConnect: vi.fn().mockResolvedValue(undefined),
    bluetoothUntrust: vi.fn().mockResolvedValue(undefined),
    bluetoothGetInfo: vi.fn().mockResolvedValue(''),
    onBluetoothPinRequired: vi.fn().mockReturnValue(() => {}),
    provideBluetoothPin: vi.fn(),
    cancelBluetoothPairing: vi.fn(),
    resetBlePairingRetryCount: vi.fn(),
    clearSessionData: vi.fn().mockResolvedValue(undefined),
    getGpsFix: vi.fn().mockResolvedValue({ lat: 0, lon: 0, source: 'ip' }),
    update: {
      check: vi.fn().mockResolvedValue(undefined),
      download: vi.fn().mockResolvedValue(undefined),
      install: vi.fn().mockResolvedValue(undefined),
      openReleases: vi.fn().mockResolvedValue(undefined),
      onAvailable: vi.fn().mockReturnValue(() => {}),
      onNotAvailable: vi.fn().mockReturnValue(() => {}),
      onChecking: vi.fn().mockReturnValue(() => {}),
      onProgress: vi.fn().mockReturnValue(() => {}),
      onDownloaded: vi.fn().mockReturnValue(() => {}),
      onError: vi.fn().mockReturnValue(() => {}),
    },
    notifyDeviceConnected: vi.fn(),
    notifyDeviceDisconnected: vi.fn(),
    setTrayUnread: vi.fn(),
    quitApp: vi.fn().mockResolvedValue(undefined),
    getPlatform: vi.fn().mockReturnValue('linux'),
    showEmojiPanel: vi.fn().mockResolvedValue(undefined),
    clipboard: {
      writeText: vi.fn().mockResolvedValue(undefined),
    },
    notify: {
      show: vi.fn().mockResolvedValue(undefined),
    },
    safeStorage: {
      encrypt: vi.fn().mockResolvedValue(null),
      decrypt: vi.fn().mockResolvedValue(null),
      isAvailable: vi.fn().mockResolvedValue(false),
    },
    appSettings: {
      getLoginItem: vi.fn().mockResolvedValue({ openAtLogin: false }),
      setLoginItem: vi.fn().mockResolvedValue(undefined),
      getAll: vi.fn().mockResolvedValue({}),
      set: vi.fn().mockResolvedValue({ changes: 1 }),
    },
    onPowerSuspend: vi.fn().mockReturnValue(() => {}),
    onPowerResume: vi.fn().mockReturnValue(() => {}),
    onSpellcheckReplace: vi.fn().mockReturnValue(() => {}),
    meshcore: {
      tcp: {
        connect: vi.fn().mockResolvedValue(undefined),
        write: vi.fn().mockResolvedValue(undefined),
        disconnect: vi.fn().mockResolvedValue(undefined),
        onData: vi.fn().mockReturnValue(() => {}),
        onDisconnected: vi.fn().mockReturnValue(() => {}),
      },
      openJsonFile: vi.fn().mockResolvedValue(null),
    },
    http: {
      preflight: vi.fn().mockResolvedValue(undefined),
      connect: vi.fn().mockResolvedValue(undefined),
      write: vi.fn().mockResolvedValue(undefined),
      disconnect: vi.fn().mockResolvedValue(undefined),
      onData: vi.fn().mockReturnValue(() => {}),
    },
    chat: {
      export: vi.fn().mockResolvedValue({ success: false }),
      linkPreview: {
        fetch: vi.fn().mockResolvedValue(null),
      },
      outbox: {
        list: vi.fn().mockResolvedValue([]),
        add: vi.fn().mockResolvedValue(null),
        updateStatus: vi.fn().mockResolvedValue(undefined),
        remove: vi.fn().mockResolvedValue(undefined),
      },
    },
    meshtasticXmodem: {
      pickUploadFile: vi.fn().mockResolvedValue(null),
      saveDownloadFile: vi.fn().mockResolvedValue({ success: false }),
    },
    log: {
      getPath: vi.fn().mockResolvedValue('/tmp/test.log'),
      getRecentLines: vi.fn().mockResolvedValue([]),
      clear: vi.fn().mockResolvedValue(undefined),
      export: vi.fn().mockResolvedValue(null),
      onLine: vi.fn().mockReturnValue(() => {}),
      logDeviceConnection: vi.fn().mockResolvedValue(undefined),
    },
    tak: {
      start: vi.fn().mockResolvedValue(undefined),
      stop: vi.fn().mockResolvedValue(undefined),
      getStatus: vi.fn().mockResolvedValue({ running: false, port: 8089, clientCount: 0 }),
      getConnectedClients: vi.fn().mockResolvedValue([]),
      generateDataPackage: vi.fn().mockResolvedValue(undefined),
      regenerateCertificates: vi.fn().mockResolvedValue(undefined),
      pushNodeUpdate: vi.fn().mockResolvedValue(undefined),
      onStatus: vi.fn().mockReturnValue(() => {}),
      onClientConnected: vi.fn().mockReturnValue(() => {}),
      onClientDisconnected: vi.fn().mockReturnValue(() => {}),
    },
    reticulum: {
      start: vi.fn().mockResolvedValue({ running: true, port: 19437, pid: 1 }),
      stop: vi.fn().mockResolvedValue(undefined),
      getStatus: vi.fn().mockResolvedValue({ running: false, port: 0, pid: null }),
      proxyGet: vi.fn().mockResolvedValue({ status: 'ok' }),
      proxyPost: vi.fn().mockResolvedValue({ ok: true }),
      proxyPut: vi.fn().mockResolvedValue({ ok: true }),
      readDefaultConfigFile: vi.fn().mockResolvedValue({ path: null, content: null }),
      showConfigImportDialog: vi.fn().mockResolvedValue({ path: null, content: null }),
      onEvent: vi.fn().mockReturnValue(() => {}),
      onStatus: vi.fn().mockReturnValue(() => {}),
    },
  } satisfies ElectronAPI;
}
